services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stududu-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.stududu.io.vn}
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL:-https://api.stududu.io.vn}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-727708804027-nuqmr75gl405o0794q8il97r42scoh3f.apps.googleusercontent.com}
    container_name: stududu-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
