const fs = require('fs');
const path = require('path');

const esFull = {
  "metadata": {
    "title": "stududu — Practica idiomas extranjeros",
    "description": "Plataforma de intercambio de idiomas y práctica oral 1:1"
  },
  "nav": {
    "discover": "Descubrir",
    "messages": "Mensajes",
    "vocabulary": "Vocabulario",
    "community": "Comunidad",
    "profile": "Perfil"
  },
  "menu": {
    "profile": "Perfil",
    "settings": "Configuración",
    "admin": "Panel de administración",
    "logout": "Cerrar sesión"
  },
  "settings": {
    "title": "Configuración",
    "language": "Idioma de la interfaz",
    "language_hint": "Solo interfaz — el contenido generado por usuarios permanece en su idioma original.",
    "password": "Cambiar contraseña",
    "shareActivity": "Compartir actividad",
    "blocked": "Usuarios bloqueados",
    "share_activity_enabled": "Compartir actividad activado",
    "share_activity_disabled": "Compartir actividad desactivado",
    "password_mismatch": "Las contraseñas no coinciden.",
    "password_success": "Contraseña actualizada con éxito",
    "unblock_success": "{name} ha sido desbloqueado/a",
    "password_hint": "Mínimo 8 caracteres, incluyendo letras y números.",
    "curr_password_placeholder": "Contraseña actual",
    "new_password_placeholder": "Nueva contraseña",
    "confirm_password_placeholder": "Confirmar nueva contraseña",
    "updating": "Actualizando...",
    "update_password": "Actualizar contraseña",
    "share_activity_hint": "Publicar automáticamente en la Comunidad cuando agregues una palabra o alcances un objetivo.",
    "enabled": "Activado",
    "disabled": "Desactivado",
    "no_blocked": "No has bloqueado a nadie.",
    "unblock": "Desbloquear",
    "logout": "Cerrar sesión"
  },
  "common": {
    "save": "Guardar cambios",
    "cancel": "Cancelar",
    "loading": "Cargando...",
    "retry": "Reintentar",
    "or": "o",
    "error_generic": "Ocurrió un error. Por favor inténtalo de nuevo."
  },
  "home": {
    "login": "Iniciar sesión",
    "register": "Registrarse",
    "title_part1": "Practica idiomas extranjeros con",
    "title_part2": "hablantes nativos reales",
    "description": "Encuentra tu compañero ideal de intercambio de idiomas. Tú enseñas tu idioma, ellos te enseñan el suyo. Totalmente gratis y mutuo.",
    "get_started": "Empieza ahora"
  },
  "login": {
    "title": "Iniciar sesión",
    "welcome": "Bienvenido a stududu",
    "email": "Correo electrónico",
    "password": "Contraseña",
    "remember": "Recordarme",
    "forgot": "¿Olvidaste tu contraseña?",
    "submit": "Iniciar sesión",
    "submitting": "Iniciando sesión...",
    "google": "Continuar con Google",
    "google_notice": "Inicio de sesión con Google: La interfaz está lista. La integración de la API se configurará una vez completado el backend.",
    "no_account": "¿No tienes una cuenta?",
    "register_link": "Regístrate ahora",
    "hero_title": "Aprende idiomas con nativos reales.",
    "hero_sub": "Tú enseñas tu idioma, ellos te enseñan el suyo. Un intercambio justo — sin calificaciones ni tarifas.",
    "hero_p1": "Emparejado por idiomas complementarios, no por puntuación",
    "hero_p2": "Conversación directa 1:1, entrena tus reflejos todos los días",
    "hero_p3": "Contribuciones reconocidas con felicitaciones, no clasificaciones",
    "hero_footer": "stududu — intercambio de idiomas al estilo Tandem"
  },
  "register": {
    "title": "Crear una cuenta",
    "subtitle": "Comienza tu viaje lingüístico",
    "hero_title": "Practica hablar con nativos reales.",
    "hero_subtitle": "Tú enseñas tu idioma, ellos te enseñan el suyo.",
    "display_name": "Nombre visible",
    "first_name": "Nombre",
    "surname": "Apellido",
    "dob": "Fecha de nacimiento",
    "day": "Día",
    "month": "Mes",
    "year": "Año",
    "gender": "Género",
    "gender_placeholder": "Selecciona tu género",
    "gender_female": "Mujer",
    "gender_male": "Hombre",
    "gender_custom": "Otro",
    "country": "País",
    "select_country": "Selecciona un país",
    "email": "Número de teléfono o correo electrónico",
    "password": "Contraseña",
    "password_hint": "Mínimo 8 caracteres, incluyendo letras y números.",
    "password_error": "La contraseña debe tener al menos 8 caracteres.",
    "google": "Continuar con Google",
    "google_notice": "Inicio de sesión con Google: La interfaz está lista.",
    "submit": "Registrarse",
    "submitting": "Creando cuenta...",
    "has_account": "¿Ya tienes una cuenta?",
    "login_link": "Iniciar sesión"
  },
  "discover": {
    "hero_label": "Solo para ti",
    "title": "Descubrir",
    "subtitle": "Encuentra compañeros para practicar e intercambiar idiomas.",
    "tab_suggest": "Mejores coincidencias",
    "tab_all": "Todos los miembros",
    "search_placeholder": "Buscar por nombre, idioma, intereses...",
    "filter_title": "Filtros",
    "filter_level_label": "Nivel del compañero (idioma enseñado)",
    "filter_level_all": "Todos los niveles",
    "filter_level_native": "Hablante nativo",
    "filter_level_fluent": "Fluido",
    "filter_interests": "Intereses comunes",
    "filter_online": "Solo en línea",
    "filter_reset": "Restablecer filtros",
    "sort_best": "Mejor coincidencia",
    "sort_recent": "Activo recientemente",
    "result_count": "compañeros coincidentes",
    "load_more": "Cargar más ({remaining} restantes)",
    "loading_more": "Cargando...",
    "loading_search": "Buscando mejores coincidencias...",
    "error_load": "Error al cargar sugerencias",
    "error_load_members": "Error al cargar miembros",
    "tip_title": "Consejo de emparejamiento",
    "tip_text": "¡Los perfiles con foto y presentación detallada reciben muchas más conexiones!",
    "insufficient_pool": "La comunidad está creciendo — aún no hay suficientes compañeros coincidentes, intenta explorar \"Todos los miembros\".",
    "empty_no_members": "No hay otros miembros por el momento",
    "empty_insufficient": "No hay suficientes compañeros coincidentes",
    "empty_no_match": "No hay compañeros coincidentes por ahora",
    "empty_no_filter": "No hay resultados para estos filtros",
    "empty_invite": "¡Invita a tus amigos a unirse a stududu!",
    "empty_suggest_tip": "Intenta cambiar a Todos los miembros o actualiza tus idiomas e intereses.",
    "empty_filter_tip": "Intenta relajar tus filtros para ver más compañeros.",
    "refresh_list": "Actualizar lista",
    "liked_toast": "Te ha gustado {name} — ¡envíale un mensaje en Mensajes!",
    "card_online": "En línea",
    "card_recent": "Activo recientemente",
    "card_speaks": "Habla:",
    "card_native": "(Nativo)",
    "card_fluent": "(Fluido)",
    "card_learns": "Aprende:",
    "card_interests": "Intereses comunes",
    "card_liked": "Me gusta",
    "card_like": "Me gusta",
    "card_unlike": "Ya no me gusta",
    "card_unliked_toast": "Se eliminó Me gusta para {name}",
    "match_title": "🎉 ¡Es un Match!",
    "match_desc": "¡Genial! A ti y a {name} os habéis gustado mutuamente. Empiecen a chatear y practicar juntos.",
    "match_chat_now": "Enviar mensaje",
    "match_continue": "Seguir descubriendo"
  },
  "community": {
    "title": "Comunidad",
    "subtitle": "Comparte tus momentos de aprendizaje, haz preguntas y conecta con miembros de todo el mundo.",
    "add_image": "Agregar foto",
    "post_placeholder": "Comparte una idea o haz una pregunta sobre el aprendizaje...",
    "post_share": "Publicar",
    "post_word": "¡Palabra dominada!",
    "post_word_generic": "Palabra agregada al vocabulario",
    "post_milestone": "Logro de aprendizaje alcanzado",
    "comment_placeholder": "Escribe un comentario...",
    "reply_placeholder": "Escribe una respuesta...",
    "reply": "Responder",
    "delete": "Eliminar",
    "unlike": "Ya no me gusta",
    "report": "Reportar",
    "comment_error": "No se pudo agregar el comentario.",
    "image_too_large": "La foto es demasiado grande (máx 5MB).",
    "char_count": "{count}/500 caracteres",
    "edit": "Editar",
    "confirm_delete": "¿Estás seguro de que quieres eliminar esta publicación?",
    "confirm_yes": "Sí, eliminar",
    "confirm_no": "Cancelar",
    "editing": "Editando...",
    "update": "Actualizar",
    "cancel_edit": "Cancelar",
    "empty_feed": "No hay publicaciones por el momento.",
    "empty_feed_hint": "¡Sé el primero en compartir algo con la comunidad!",
    "time_just_now": "Ahora mismo",
    "time_minutes_ago": "hace {m} min",
    "time_hours_ago": "hace {h} h",
    "report_post_target": "Reportar publicación",
    "attach_image": "Adjuntar foto",
    "image_size_error": "Tamaño de foto excedido.",
    "eyebrow": "Espacio de intercambio y aprendizaje",
    "page_subtitle": "Descubre consejos, haz preguntas y celebra tus progresos.",
    "tab_feed": "Muro",
    "tab_groups": "Grupos",
    "tab_events": "Eventos",
    "tag_partner": "Compañero",
    "tag_milestone": "Objetivo",
    "tag_question": "Pregunta",
    "daily_vocab_title": "Vocabulario del día",
    "save_word": "Guardar palabra",
    "saved_word": "Guardada",
    "next_word": "Siguiente palabra",
    "already_know": "Ya la conozco",
    "suggested_groups": "Grupos sugeridos",
    "join_group": "Unirse",
    "joined_group": "Unido",
    "members_count": "{count} miembros",
    "groups_coming_soon": "¡La función de Grupos llegará pronto!",
    "events_coming_soon": "¡Los Eventos llegarán pronto!",
    "groups_title": "Grupos de conversación",
    "group_en_desc": "Práctica diaria de inglés para todos los niveles.",
    "group_ja_desc": "Intercambio de idioma y cultura japonesa.",
    "group_fr_desc": "Club de conversación en francés.",
    "group_ko_desc": "Club de idioma y cultura coreana.",
    "create_group": "Crear un grupo",
    "events_title": "Próximos eventos",
    "event_1_title": "Sesión de conversación en inglés en vivo",
    "event_1_desc": "Intercambio oral 1:1 en línea con nativos.",
    "event_2_title": "Taller de gramática francesa",
    "event_2_desc": "Consejos prácticos y errores comunes a evitar.",
    "event_date_today": "Hoy · 20:00",
    "event_date_tomorrow": "Mañana · 19:30",
    "attend": "Asistir",
    "attending": "Inscrito/a"
  },
  "langSwitcher": {
    "vi": "Tiếng Việt",
    "en": "English",
    "fr": "Français",
    "es": "Español"
  },
  "vocabulary": {
    "title": "Mi vocabulario",
    "subtitle": "Guarda las nuevas palabras descubiertas en tus intercambios y repásalas en cualquier momento.",
    "empty_list": "Tu cuaderno de vocabulario está vacío.",
    "empty_hint": "Guarda palabras durante tus chats o agrégalas manualmente.",
    "add_word_btn": "Agregar palabra",
    "search_placeholder": "Buscar una palabra, significado...",
    "modal_title": "Agregar nueva palabra",
    "term_label": "Palabra / Expresión",
    "term_placeholder": "Ej: Hola",
    "definition_label": "Definición / Traducción",
    "definition_placeholder": "Ej: Hello / Good day",
    "example_label": "Frase de ejemplo",
    "example_placeholder": "Ej: ¡Hola a todos!",
    "notes_label": "Notas",
    "notes_placeholder": "Ej: Saludo común",
    "lang_label": "Idioma de la palabra",
    "submitting": "Guardando...",
    "submit_add": "Agregar al cuaderno",
    "delete_title": "Eliminar palabra",
    "delete_confirm": "¿Estás seguro de que quieres eliminar la palabra \"{term}\"?",
    "delete_yes": "Sí, eliminar",
    "delete_no": "Cancelar",
    "practice_flashcards": "Práctica con tarjetas de memoria",
    "practice_hint": "Repasa tu vocabulario guardado gracias a las flashcards.",
    "ai_lookup_title": "Búsqueda inteligente con IA",
    "ai_lookup_hint": "Busca definiciones, pronunciaciones y ejemplos con la IA.",
    "term_required": "Por favor ingresa al menos la palabra.",
    "add_success": "¡Palabra agregada al vocabulario!",
    "delete_success": "Palabra eliminada.",
    "status_mastered": "Dominada",
    "status_learning": "En aprendizaje",
    "toggle_mastered": "Marcar como dominada",
    "toggle_learning": "Marcar como en aprendizaje",
    "mastered_count": "{count} dominadas",
    "learning_count": "{count} en aprendizaje"
  },
  "profile": {
    "title": "Perfil de usuario",
    "empty_name_error": "El nombre visible no puede estar vacío.",
    "lang_selection_error": "Por favor selecciona al menos 1 idioma nativo y 1 idioma para aprender.",
    "timezone_label": "Tu zona horaria",
    "slots_title": "Disponibilidad (máx. 2)",
    "slots_selected": "{count}/2 seleccionados",
    "slots_time": "Hora",
    "slots_hint": "Tus horarios disponibles ayudan a tus compañeros a planificar intercambios.",
    "matching_criteria": "Criterios de emparejamiento",
    "preferred_language": "Idioma preferido",
    "no_preference": "Sin preferencia",
    "desired_level": "Nivel deseado del compañero",
    "any_level": "Todos los niveles",
    "edit_subtitle": "Un perfil completo te ayuda a conseguir más coincidencias.",
    "this_is_you": "Este es tu perfil",
    "your_name": "Tu nombre",
    "change_avatar": "Cambiar foto de perfil",
    "preview": "Vista previa",
    "preview_hint": "Así te ven los demás en Descubrir.",
    "preview_speaks": "Habla:",
    "preview_learns": "Aprende:",
    "preview_not_added": "No agregado",
    "preview_online": "En línea",
    "preview_like": "Me gusta",
    "shared_interests": "Intereses comunes",
    "interests_hint": "Elige los temas que te gusta tratar.",
    "intent_hint": "Nos ayuda a sugerirte mejores compañeros.",
    "no_posts_other": "No hay publicaciones compartidas por el momento.",
    "edit_profile": "Editar perfil",
    "save_profile": "Guardar perfil",
    "saving": "Guardando...",
    "native_language": "Idioma nativo",
    "learning_languages": "Idiomas en aprendizaje",
    "bio": "Sobre mí",
    "no_bio": "Sin biografía escrita por el momento.",
    "endorsements": "Felicitaciones",
    "hours": "horas",
    "words": "palabras",
    "sessions": "sesiones",
    "member_since": "Miembro desde",
    "follow": "Seguir",
    "following": "Siguiendo",
    "followers": "Seguidores",
    "message": "Mensaje",
    "give_endorsement": "Dar una felicitación",
    "select_compliment": "Selecciona un cumplido para {name}"
  },
  "chat": {
    "say_hi": "Di hola para iniciar la conversación 👋",
    "you": "Tú: ",
    "photo": "📷 Foto",
    "schedule_invite": "📅 Invitación de intercambio",
    "translate_fail": "Error al traducir, inténtalo más tarde",
    "schedule_fail": "No se pudo enviar la invitación",
    "respond_fail": "No se pudo responder a la invitación",
    "title": "Mensajes",
    "search_placeholder": "Buscar una conversación...",
    "no_match": "No se encontró ninguna conversación",
    "empty_conversations": "No hay conversaciones por el momento",
    "empty_hint": "Ve a Descubrir para encontrar compañeros de práctica.",
    "go_discover": "Ir a Descubrir",
    "select_chat": "Seleccionar una conversación",
    "select_chat_hint": "Empieza a practicar con tu compañero.",
    "user_local_time": "(tu hora)",
    "schedule_btn_tooltip": "Planificar un intercambio",
    "trans_modal_tooltip": "Panel de traducción",
    "view_profile": "Ver perfil",
    "report": "Reportar",
    "block": "Bloquear",
    "partner_availability": "Horarios libres de {name}:",
    "overlap_badge": "✓ ¡Horarios libres coincidentes!",
    "reconnecting": "Reconectando...",
    "save_word_popup": "Guardar palabra",
    "matched_title": "¡Es un Match!",
    "matched_desc": "Envía un saludo para empezar a practicar.",
    "invite_sent": "Has enviado una invitación",
    "invite_received": "{name} te ha invitado a intercambiar",
    "local_time_hint": "(basado en la zona horaria de tu computadora)",
    "accept": "Aceptar",
    "decline": "Rechazar",
    "cancel": "Cancelar",
    "status_accepted": "✅ Aceptado — recordatorio 30 min antes",
    "status_expired": "⌛ Expirado (sin respuesta en 48h)",
    "status_declined": "❌ Rechazado",
    "status_cancelled": "🚫 Cancelado",
    "cancel_reason_label": "Razón: {reason}",
    "cancel_modal_title": "Cancelar intercambio planificado",
    "cancel_modal_placeholder": "Ingresa la razón de la cancelación...",
    "cancel_success_toast": "Intercambio planificado cancelado con éxito",
    "status_sending": "Enviando...",
    "status_read": "Visto",
    "status_sent": "Enviado",
    "react_tooltip": "Agregar reacción",
    "emoji_tooltip": "Emojis",
    "send_img_tooltip": "Enviar una foto",
    "input_placeholder": "Escribe un mensaje...",
    "report_success": "Reporte enviado. ¡Gracias!",
    "block_success": "{name} ha sido bloqueado/a",
    "word_save_exists": "\"{term}\" ya está en tu cuaderno",
    "word_save_success": "✅ \"{term}\" guardada en tu cuaderno de vocabulario",
    "translating": "Traduciendo...",
    "hide": "Ocultar",
    "translate": "Traducir",
    "save_word": "Guardar palabra"
  },
  "forgot": {
    "title": "¿Olvidaste tu contraseña?",
    "subtitle": "Ingresa tu correo para recibir un enlace de restablecimiento",
    "success_message": "Si el correo es válido, se ha enviado un enlace de restablecimiento (válido durante 30 minutos).",
    "back_to_login": "Volver a iniciar sesión",
    "email_placeholder": "Tu correo electrónico",
    "sending": "Enviando...",
    "submit": "Enviar enlace de restablecimiento"
  },
  "onboarding": {
    "step_languages": "Idiomas",
    "step_interests": "Intereses",
    "step_complete": "Finalización",
    "error_lang_selection": "Por favor selecciona al menos 1 idioma nativo y 1 idioma para aprender.",
    "error_bio_empty": "Por favor escribe una presentación personal.",
    "teach_title": "Hablo (idioma nativo / fluido)",
    "select_lang": "Seleccionar un idioma",
    "add_btn": "Agregar",
    "learn_title": "Me gustaría aprender",
    "loading": "Guardando...",
    "continue_btn": "Continuar",
    "interests_title": "Tus intereses",
    "interests_subtitle": "Selecciona los temas que te interesan (opcional).",
    "back_btn": "Atrás",
    "profile_title": "Completa tu perfil",
    "profile_subtitle": "Unas palabras sobre ti te ayudarán a encontrar coincidencias fácilmente.",
    "bio_label": "Presentación personal (Bio)",
    "bio_placeholder": "Ej: Estoy aprendiendo español para mis estudios. Me gusta el café y leer los fines de semana...",
    "intent_label": "Objetivo principal de aprendizaje",
    "finish_btn": "Terminar y Descubrir",
    "level_1": "Principiante (A1)",
    "level_2": "Elemental (A2)",
    "level_3": "Intermedio (B1)",
    "level_4": "Avanzado (B2)",
    "level_5": "Dominio (C1/C2)",
    "intent_casual": "Conversación informal",
    "intent_exam": "Preparación para exámenes (DELE, IELTS...)",
    "intent_travel": "Viajes",
    "intent_work": "Trabajo / Negocios"
  },
  "notifications": {
    "title": "Notificaciones",
    "empty": "No tienes notificaciones.",
    "mark_all_read": "Marcar todo como leído",
    "follow_message": "{name} ha comenzado a seguirte.",
    "new_post_message": "{name} ha publicado una actualización.",
    "like_message": "A {name} le has gustado.",
    "match_message": "¡Tú y {name} habéis hecho Match!"
  },
  "topics": {
    "travel": "Viajes",
    "music": "Música",
    "movies": "Películas y Series",
    "food": "Gastronomía y Cocina",
    "sports": "Deportes y Fitness",
    "tech": "Tecnología",
    "books": "Libros y Lectura",
    "game": "Videojuegos",
    "culture": "Cultura e Idiomas",
    "exams": "Exámenes (DELE, IELTS...)"
  },
  "call": {
    "start_tooltip": "Llamada de voz",
    "start_video_tooltip": "Videollamada",
    "calling": "Llamando…",
    "incoming_title": "{name} te está llamando",
    "incoming_audio": "Llamada de voz entrante",
    "incoming_video": "Videollamada entrante",
    "accept": "Aceptar",
    "accept_audio_only": "Responder sin cámara",
    "decline": "Rechazar",
    "hang_up": "Colgar",
    "mute": "Silenciar",
    "unmute": "Activar micrófono",
    "camera_off": "Desactivar cámara",
    "camera_on": "Activar cámara",
    "switch_camera": "Cambiar cámara",
    "partner_camera_off": "Tu compañero ha desactivado su cámara",
    "network_unstable": "Conexión inestable…",
    "rejected": "Tu compañero ha rechazado la llamada",
    "no_answer": "Sin respuesta",
    "partner_busy": "{name} ya está en una llamada",
    "partner_offline": "{name} no está en línea",
    "failed": "Conexión perdida, llamada finalizada",
    "ended_max_duration": "La llamada ha alcanzado el límite de 30 minutos",
    "timeout_warning": "La llamada finalizará automáticamente en {minutes} minutos",
    "error_insecure": "Tu navegador ha bloqueado el micrófono porque la página no usa HTTPS",
    "error_permission": "Permite el acceso al micrófono en la configuración de tu navegador",
    "error_no_device": "No se detectó ningún micrófono",
    "error_camera_busy": "La cámara está siendo utilizada por otra aplicación",
    "error_camera_permission": "El acceso a la cámara está bloqueado",
    "error_unknown": "No se pudo realizar la llamada"
  }
};

// Merging missing keys from en.json / fr.json if any exist
const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const frPath = path.join(__dirname, '../../frontend/messages/fr.json');
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

function mergeKeys(target, source) {
  for (const key of Object.keys(source)) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      mergeKeys(target[key], source[key]);
    } else {
      if (!target[key]) {
        target[key] = source[key];
      }
    }
  }
}

mergeKeys(esFull, en);

// Update langSwitcher in en.json and fr.json and vi.json to also include es
const viPath = path.join(__dirname, '../../frontend/messages/vi.json');
const vi = JSON.parse(fs.readFileSync(viPath, 'utf8'));
if (!vi.langSwitcher) vi.langSwitcher = {};
vi.langSwitcher.es = "Tiếng Tây Ban Nha";
fs.writeFileSync(viPath, JSON.stringify(vi, null, 2), 'utf8');

const fr = JSON.parse(fs.readFileSync(frPath, 'utf8'));
if (!fr.langSwitcher) fr.langSwitcher = {};
fr.langSwitcher.es = "Español";
fs.writeFileSync(frPath, JSON.stringify(fr, null, 2), 'utf8');

if (!en.langSwitcher) en.langSwitcher = {};
en.langSwitcher.es = "Spanish";
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');

const targetPath = path.join(__dirname, '../../frontend/messages/es.json');
fs.writeFileSync(targetPath, JSON.stringify(esFull, null, 2), 'utf8');
console.log('Successfully created complete es.json!');
