const fs = require('fs');
const path = require('path');

const frTranslations = {
  metadata: {
    title: 'stududu — Pratiquez les langues étrangères',
    description: 'Plateforme d\'échange linguistique et de pratique orale 1:1'
  },
  nav: {
    discover: 'Découvrir',
    messages: 'Messages',
    vocabulary: 'Vocabulaire',
    community: 'Communauté',
    profile: 'Profil'
  },
  menu: {
    profile: 'Profil',
    settings: 'Paramètres',
    admin: 'Panneau d\'administration',
    logout: 'Déconnexion'
  },
  settings: {
    title: 'Paramètres',
    language: 'Langue de l\'interface',
    language_hint: 'Interface uniquement — le contenu généré par les utilisateurs reste dans sa langue d\'origine.',
    password: 'Changer le mot de passe',
    shareActivity: 'Partager l\'activité',
    blocked: 'Utilisateurs bloqués',
    share_activity_enabled: 'Partage d\'activité activé',
    share_activity_disabled: 'Partage d\'activité désactivé',
    password_mismatch: 'Les mots de passe ne correspondent pas.',
    password_success: 'Mot de passe mis à jour avec succès',
    unblock_success: '{name} a été débloqué(e)',
    password_hint: 'Minimum 8 caractères, incluant lettres et chiffres.',
    curr_password_placeholder: 'Mot de passe actuel',
    new_password_placeholder: 'Nouveau mot de passe',
    confirm_password_placeholder: 'Confirmer le nouveau mot de passe',
    updating: 'Mise à jour...',
    update_password: 'Mettre à jour le mot de passe',
    share_activity_hint: 'Publier automatiquement sur la Communauté lorsque vous ajoutez un mot ou atteignez un objectif.',
    enabled: 'Activé',
    disabled: 'Désactivé',
    no_blocked: 'Vous n\'avez bloqué personne.',
    unblock: 'Débloquer',
    logout: 'Se déconnecter'
  },
  common: {
    save: 'Enregistrer',
    cancel: 'Annuler',
    loading: 'Chargement...',
    retry: 'Réessayer',
    or: 'ou',
    error_generic: 'Une erreur s\'est produite. Veuillez réessayer.'
  },
  home: {
    login: 'Connexion',
    register: 'Inscription',
    title_part1: 'Pratiquez les langues étrangères avec de',
    title_part2: 'vrais locuteurs natifs',
    description: 'Trouvez votre partenaire d\'échange linguistique idéal. Vous enseignez votre langue, ils vous enseignent la leur. Entièrement gratuit et mutuel.',
    get_started: 'Commencer maintenant'
  },
  login: {
    title: 'Connexion',
    welcome: 'Bienvenue sur stududu',
    email: 'E-mail',
    password: 'Mot de passe',
    remember: 'Se souvenir de moi',
    forgot: 'Mot de passe oublié ?',
    submit: 'Se connecter',
    submitting: 'Connexion en cours...',
    google: 'Continuer avec Google',
    google_notice: 'Connexion Google : l\'interface est prête. L\'intégration API sera configurée une fois le backend terminé.',
    no_account: 'Vous n\'avez pas de compte ?',
    register_link: 'Inscrivez-vous maintenant',
    hero_title: 'Apprenez les langues avec de vrais natifs.',
    hero_sub: 'Vous enseignez votre langue, ils vous enseignent la leur. Un échange équitable — sans notes ni frais.',
    hero_p1: 'Mis en relation par langues complémentaires, pas par note',
    hero_p2: 'Discussion directe 1:1, entraînez vos réflexes chaque jour',
    hero_p3: 'Contributions reconnues par des félicitations, pas des classements',
    hero_footer: 'stududu — échange linguistique style Tandem'
  },
  register: {
    title: 'Créer un compte',
    subtitle: 'Commencez votre voyage linguistique',
    hero_title: 'Pratiquez l\'oral avec de vrais natifs.',
    hero_subtitle: 'Vous enseignez votre langue, ils vous enseignent la leur.',
    display_name: 'Nom d\'affichage',
    first_name: 'Prénom',
    surname: 'Nom',
    dob: 'Date de naissance',
    day: 'Jour',
    month: 'Mois',
    year: 'Année',
    gender: 'Genre',
    gender_placeholder: 'Sélectionnez votre genre',
    gender_female: 'Femme',
    gender_male: 'Homme',
    gender_custom: 'Autre',
    country: 'Pays',
    select_country: 'Sélectionnez un pays',
    email: 'Numéro de téléphone ou e-mail',
    password: 'Mot de passe',
    password_hint: 'Minimum 8 caractères, incluant lettres et chiffres.',
    password_error: 'Le mot de passe doit comporter au moins 8 caractères.',
    google: 'Continuer avec Google',
    google_notice: 'Connexion avec Google : L\'interface est prête.',
    submit: 'S\'inscrire',
    submitting: 'Création du compte...',
    has_account: 'Vous avez déjà un compte ?',
    login_link: 'Se connecter'
  },
  discover: {
    title: 'Découvrir des partenaires',
    subtitle: 'Trouvez des partenaires de conversation correspondant à vos objectifs d\'apprentissage.',
    hero_label: 'Trouvez votre partenaire d\'échange linguistique idéal',
    tab_suggest: 'Recommandations',
    tab_all: 'Tous les membres',
    filter_title: 'Filtres de recherche',
    filter_level_label: 'Niveau de maîtrise',
    filter_level_all: 'Tous les niveaux',
    filter_level_native: 'Langue maternelle',
    filter_level_fluent: 'Courant',
    filter_interests: 'Centres d\'intérêt',
    filter_online: 'En ligne uniquement',
    filter_reset: 'Réinitialiser',
    sort_best: 'Meilleure correspondance',
    sort_recent: 'Récemment actif',
    result_count: '{count} membres trouvés',
    load_more: 'Charger plus',
    loading_more: 'Chargement...',
    loading_search: 'Recherche de partenaires...',
    error_load_members: 'Impossible de charger les membres.',
    tip_title: 'Conseil pour de meilleures correspondances',
    tip_text: 'Complétez votre profil avec vos langues maternelle et d\'apprentissage pour des suggestions plus précises.',
    insufficient_pool: 'Base de membres insuffisante pour le matching. Affichage des membres disponibles ci-dessous.',
    empty_no_members: 'Aucun membre enregistré pour le moment.',
    empty_insufficient: 'Pas assez de membres pour afficher des recommandations.',
    empty_no_match: 'Aucun partenaire ne correspond à vos critères.',
    empty_no_filter: 'Aucun partenaire trouvé avec ces filtres.',
    empty_invite: 'Invitez vos amis à rejoindre stududu !',
    empty_suggest_tip: 'Remplissez vos langues dans le profil pour obtenir des recommandations.',
    empty_filter_tip: 'Essayez d\'ajuster vos filtres pour voir plus de membres.',
    refresh_list: 'Actualiser la liste',
    liked_toast: 'Aimé !',
    card_online: 'En ligne',
    card_recent: 'Récemment actif',
    card_speaks: 'Parle :',
    card_native: 'Langue maternelle',
    card_fluent: 'Courant',
    card_learns: 'Apprend :',
    card_interests: 'Sujets :',
    card_liked: 'Aimé',
    card_like: 'J\'aime',
    card_unlike: 'Retirer j\'aime',
    card_unliked_toast: 'J\'aime retiré',
    match_title: 'C\'est un Match !',
    match_desc: 'Vous et {name} souhaitez apprendre la langue de l\'autre. Lancez la conversation dès maintenant !',
    match_chat_now: 'Discuter maintenant',
    match_continue: 'Continuer à parcourir'
  },
  community: {
    title: 'Communauté',
    subtitle: 'Partagez vos progrès, posez des questions et échangez avec des apprenants du monde entier.',
    add_image: 'Ajouter une photo',
    post_placeholder: 'Partagez une pensée ou posez une question sur l\'apprentissage...',
    post_share: 'Publier',
    post_word: 'Mot maîtrisé !',
    post_word_generic: 'Mot ajouté au vocabulaire',
    post_milestone: 'Étape d\'apprentissage atteinte',
    comment_placeholder: 'Écrire un commentaire...',
    reply_placeholder: 'Écrire une réponse...',
    reply: 'Répondre',
    delete: 'Supprimer',
    unlike: 'Ne plus aimer',
    report: 'Signaler',
    comment_error: 'Impossible d\'ajouter le commentaire.',
    image_too_large: 'La photo est trop lourde (max 5Mo).',
    char_count: '{count}/500 caractères',
    edit: 'Modifier',
    confirm_delete: 'Êtes-vous sûr de vouloir supprimer cette publication ?',
    confirm_yes: 'Oui, supprimer',
    confirm_no: 'Annuler',
    editing: 'Modification...',
    update: 'Mettre à jour',
    cancel_edit: 'Annuler',
    empty_feed: 'Aucune publication pour le moment.',
    empty_feed_hint: 'Soyez le premier à partager quelque chose avec la communauté !',
    time_just_now: 'À l\'instant',
    time_minutes_ago: 'il y a {m} min',
    time_hours_ago: 'il y a {h} h',
    report_post_target: 'Signaler la publication',
    attach_image: 'Joindre une photo',
    image_size_error: 'Taille de photo dépassée.',
    eyebrow: 'Espace d\'échange & de partage',
    page_subtitle: 'Découvrez des astuces, posez des questions et célébrez vos progrès.',
    tab_feed: 'Fil d\'actualité',
    tab_groups: 'Groupes',
    tab_events: 'Événements',
    tag_partner: 'Partenaire',
    tag_milestone: 'Objectif',
    tag_question: 'Question',
    daily_vocab_title: 'Vocabulaire du jour',
    save_word: 'Enregistrer le mot',
    saved_word: 'Enregistré',
    next_word: 'Mot suivant',
    already_know: 'Je connais déjà',
    suggested_groups: 'Groupes suggérés',
    join_group: 'Rejoindre',
    joined_group: 'Rejoint',
    members_count: '{count} membres',
    groups_coming_soon: 'La fonctionnalité Groupes arrive bientôt !',
    events_coming_soon: 'Les Événements arrivent bientôt !',
    groups_title: 'Groupes de discussion',
    group_en_desc: 'Pratique quotidienne de l\'anglais pour tous les niveaux.',
    group_ja_desc: 'Échange linguistique et culture japonaise.',
    group_fr_desc: 'Club de discussion francophone.',
    group_ko_desc: 'Club de langue et culture coréenne.',
    create_group: 'Créer un groupe',
    events_title: 'Événements à venir',
    event_1_title: 'Session de conversation anglaise en direct',
    event_1_desc: 'Échange oral 1:1 en ligne avec des natifs.',
    event_2_title: 'Atelier de grammaire française',
    event_2_desc: 'Conseils pratiques et erreurs fréquentes à éviter.',
    event_date_today: 'Aujourd\'hui · 20:00',
    event_date_tomorrow: 'Demain · 19:30',
    attend: 'Participer',
    attending: 'Inscrit(e)'
  },
  langSwitcher: {
    vi: 'Tiếng Việt',
    en: 'English',
    fr: 'Français'
  },
  vocabulary: {
    title: 'Mon vocabulaire',
    subtitle: 'Enregistrez les nouveaux mots découverts lors de vos échanges et révisez-les à tout moment.',
    empty_list: 'Votre carnet de vocabulaire est vide.',
    empty_hint: 'Enregistrez des mots lors de vos discussions ou ajoutez-les manuellement.',
    add_word_btn: 'Ajouter un mot',
    search_placeholder: 'Rechercher un mot, un sens...',
    modal_title: 'Ajouter un nouveau mot',
    term_label: 'Mot / Expression',
    term_placeholder: 'Ex: Bonjour',
    definition_label: 'Définition / Traduction',
    definition_placeholder: 'Ex: Hello / Good day',
    example_label: 'Exemple de phrase',
    example_placeholder: 'Ex: Bonjour tout le monde !',
    notes_label: 'Notes',
    notes_placeholder: 'Ex: Formule de salutation courante',
    lang_label: 'Langue du mot',
    submitting: 'Enregistrement...',
    submit_add: 'Ajouter au carnet',
    delete_title: 'Supprimer le mot',
    delete_confirm: 'Êtes-vous sûr de vouloir supprimer le mot "{term}" ?',
    delete_yes: 'Oui, supprimer',
    delete_no: 'Annuler',
    practice_flashcards: 'Entraînement aux cartes mémoire',
    practice_hint: 'Révisez votre vocabulaire enregistrez grâce aux flashcards.',
    ai_lookup_title: 'Recherche intelligente IA',
    ai_lookup_hint: 'Recherchez les définitions, prononciations et exemples grâce à l\'IA.',
    term_required: 'Veuillez saisir au moins le mot.',
    add_success: 'Mot ajouté au vocabulaire !',
    delete_success: 'Mot supprimé.',
    status_mastered: 'Maîtrisé',
    status_learning: 'En cours',
    toggle_mastered: 'Marquer comme maîtrisé',
    toggle_learning: 'Marquer comme en cours',
    mastered_count: '{count} maîtrisés',
    learning_count: '{count} en cours'
  },
  profile: {
    title: 'Profil utilisateur',
    empty_name_error: 'Le nom d\'affichage ne peut pas être vide.',
    lang_selection_error: 'Veuillez sélectionner au moins 1 langue maternelle et 1 langue à apprendre.',
    timezone_label: 'Votre fuseau horaire',
    slots_title: 'Disponibilités (max 2)',
    slots_selected: '{count}/2 sélectionnés',
    slots_time: 'Heure',
    slots_hint: 'Vos créneaux de disponibilité aident vos partenaires à planifier des échanges.',
    matching_criteria: 'Critères de mise en relation',
    preferred_language: 'Langue préférée',
    no_preference: 'Pas de préférence',
    desired_level: 'Niveau de partenaire souhaité',
    any_level: 'Tous niveaux',
    edit_subtitle: 'Un profil complet vous permet d\'obtenir plus de correspondances.',
    this_is_you: 'C\'est votre profil',
    your_name: 'Votre nom',
    change_avatar: 'Changer la photo de profil',
    preview: 'Aperçu',
    preview_hint: 'Voici comment les autres vous voient dans Découvrir.',
    preview_speaks: 'Parle :',
    preview_learns: 'Apprend :',
    preview_not_added: 'Non ajouté',
    preview_online: 'En ligne',
    preview_like: 'J\'aime',
    shared_interests: 'Centres d\'intérêt communs',
    interests_hint: 'Choisissez les sujets que vous aimez aborder.',
    intent_hint: 'Nous aide à vous suggérer de meilleurs partenaires.',
    no_posts_other: 'Aucune publication partagée pour le moment.',
    edit_profile: 'Modifier le profil',
    save_profile: 'Enregistrer le profil',
    saving: 'Enregistrement...',
    native_language: 'Langue maternelle',
    learning_languages: 'Langues d\'apprentissage',
    bio: 'À propos de moi',
    no_bio: 'Aucune biographie rédigée pour le moment.',
    endorsements: 'Félicitations',
    hours: 'heures',
    words: 'mots',
    sessions: 'sessions',
    member_since: 'Membre depuis',
    follow: 'S\'abonner',
    following: 'Abonnements',
    followers: 'Abonnés',
    message: 'Message',
    give_endorsement: 'Offrir une félicitation',
    select_compliment: 'Sélectionnez un compliment pour {name}'
  },
  chat: {
    say_hi: 'Dites bonjour pour lancer la conversation 👋',
    you: 'Vous : ',
    photo: '📷 Photo',
    schedule_invite: '📅 Invitation d\'échange',
    translate_fail: 'Échec de la traduction, réessayez plus tard',
    schedule_fail: 'Impossible d\'envoyer l\'invitation',
    respond_fail: 'Impossible de répondre à l\'invitation',
    title: 'Messages',
    search_placeholder: 'Rechercher une conversation...',
    no_match: 'Aucune conversation trouvée',
    empty_conversations: 'Aucune conversation pour le moment',
    empty_hint: 'Rendez-vous dans Découvrir pour trouver des partenaires d\'entraînement.',
    go_discover: 'Aller dans Découvrir',
    select_chat: 'Sélectionner une conversation',
    select_chat_hint: 'Commencez à pratiquer avec votre partenaire.',
    user_local_time: '(votre heure)',
    schedule_btn_tooltip: 'Planifier un échange',
    trans_modal_tooltip: 'Tableau de traduction',
    view_profile: 'Voir le profil',
    report: 'Signaler',
    block: 'Bloquer',
    partner_availability: 'Créneaux libres de {name} :',
    overlap_badge: '✓ Créneaux libres en commun !',
    reconnecting: 'Reconnexion en cours...',
    save_word_popup: 'Enregistrer le mot',
    matched_title: 'C\'est un Match !',
    matched_desc: 'Envoyez une salutation pour commencer à pratiquer.',
    invite_sent: 'Vous avez envoyé une invitation',
    invite_received: '{name} vous a invité(e) à échanger',
    local_time_hint: '(basé sur le fuseau horaire de votre ordinateur)',
    accept: 'Accepter',
    decline: 'Refuser',
    cancel: 'Annuler',
    status_accepted: '✅ Accepté — rappel 30 min avant',
    status_expired: '⌛ Expiré (sans réponse sous 48h)',
    status_declined: '❌ Refusé',
    status_cancelled: '🚫 Annulé',
    cancel_reason_label: 'Raison : {reason}',
    cancel_modal_title: 'Annuler l\'échange planifié',
    cancel_modal_placeholder: 'Entrez la raison de l\'annulation...',
    cancel_success_toast: 'Échange planifié annulé avec succès',
    status_sending: 'Envoi...',
    status_read: 'Lu',
    status_sent: 'Envoyé',
    react_tooltip: 'Ajouter une réaction',
    emoji_tooltip: 'Émojis',
    send_img_tooltip: 'Envoyer une photo',
    input_placeholder: 'Écrivez un message...',
    report_success: 'Signalement envoyé. Merci !',
    block_success: '{name} a été bloqué(e)',
    word_save_exists: '\"{term}\" est déjà dans votre carnet',
    word_save_success: '✅ \"{term}\" enregistré dans votre carnet de vocabulaire',
    translating: 'Traduction...',
    hide: 'Masquer',
    translate: 'Traduire',
    save_word: 'Enregistrer le mot'
  },
  forgot: {
    title: 'Mot de passe oublié',
    subtitle: 'Entrez votre e-mail pour recevoir un lien de réinitialisation',
    success_message: 'Si l\'e-mail est valide, un lien de réinitialisation a été envoyé (valable 30 minutes).',
    back_to_login: 'Retour à la connexion',
    email_placeholder: 'Votre e-mail',
    sending: 'Envoi en cours...',
    submit: 'Envoyer le lien de réinitialisation'
  },
  onboarding: {
    step_languages: 'Langues',
    step_interests: 'Centres d\'intérêt',
    step_complete: 'Finalisation',
    error_lang_selection: 'Veuillez sélectionner au moins 1 langue maternelle et 1 langue à apprendre.',
    error_bio_empty: 'Veuillez rédiger une présentation personnelle.',
    teach_title: 'Je parle (langue maternelle / fluide)',
    select_lang: 'Sélectionner une langue',
    add_btn: 'Ajouter',
    learn_title: 'J\'aimerais apprendre',
    loading: 'Enregistrement...',
    continue_btn: 'Continuer',
    interests_title: 'Vos centres d\'intérêt',
    interests_subtitle: 'Sélectionnez les sujets qui vous intéressent (optionnel).',
    back_btn: 'Retour',
    profile_title: 'Complétez votre profil',
    profile_subtitle: 'Quelques mots sur vous vous aideront à trouver des correspondances facilement.',
    bio_label: 'Présentation personnelle (Bio)',
    bio_placeholder: 'Ex: J\'apprends le français pour mes études. J\'aime le café et la lecture le week-end...',
    intent_label: 'Objectif principal d\'apprentissage',
    finish_btn: 'Terminer & Découvrir',
    level_1: 'Débutant (A1)',
    level_2: 'Élémentaire (A2)',
    level_3: 'Intermédiaire (B1)',
    level_4: 'Avancé (B2)',
    level_5: 'Maîtrise (C1/C2)',
    intent_casual: 'Discussion informelle',
    intent_exam: 'Préparation aux examens (IELTS, DELF...)',
    intent_travel: 'Voyages',
    intent_work: 'Travail / Affaires'
  },
  notifications: {
    title: 'Notifications',
    empty: 'Vous n\'avez aucune notification.',
    mark_all_read: 'Tout marquer comme lu',
    follow_message: '{name} a commencé à vous suivre.',
    new_post_message: '{name} a publié une mise à jour.',
    like_message: '{name} vous a aimé(e).',
    match_message: 'Vous et {name} êtes en Match !'
  },
  topics: {
    travel: 'Voyages',
    music: 'Musique',
    movies: 'Films & Séries',
    food: 'Gastronomie & Cuisine',
    sports: 'Sports & Fitness',
    tech: 'Technologie',
    books: 'Livres & Lecture',
    game: 'Jeux vidéo',
    culture: 'Culture & Langues',
    exams: 'Examens (DELF, IELTS...)'
  },
  call: {
    start_tooltip: 'Appel vocal',
    start_video_tooltip: 'Appel vidéo',
    calling: 'Appel en cours…',
    incoming_title: '{name} vous appelle',
    incoming_audio: 'Appel vocal entrant',
    incoming_video: 'Appel vidéo entrant',
    accept: 'Accepter',
    accept_audio_only: 'Répondre sans caméra',
    decline: 'Refuser',
    hang_up: 'Raccrocher',
    mute: 'Muet',
    unmute: 'Activer le micro',
    camera_off: 'Désactiver la caméra',
    camera_on: 'Activer la caméra',
    switch_camera: 'Changer de caméra',
    partner_camera_off: 'Votre partenaire a désactivé sa caméra',
    network_unstable: 'Connexion faible…',
    rejected: 'Votre partenaire a refusé l\'appel',
    no_answer: 'Pas de réponse',
    partner_busy: '{name} est déjà en appel',
    partner_offline: '{name} n\'est pas en ligne',
    failed: 'Connexion perdue, appel terminé',
    ended_max_duration: 'L\'appel a atteint la limite de 30 minutes',
    timeout_warning: 'L\'appel se terminera automatiquement dans {minutes} minutes',
    error_insecure: 'Votre navigateur a bloqué le microphone car la page n\'est pas en HTTPS',
    error_permission: 'Autorisez l\'accès au microphone dans les paramètres de votre navigateur',
    error_no_device: 'Aucun microphone détecté',
    error_camera_busy: 'La caméra est utilisée par une autre application',
    error_camera_permission: 'L\'accès à la caméra est bloqué',
    error_unknown: 'Impossible d\'effectuer l\'appel',
    log_ended: 'Appel vocal · {duration}',
    log_ended_video: 'Appel vidéo · {duration}',
    log_rejected: 'Appel refusé',
    log_missed_outgoing: 'Appel sans réponse',
    log_missed_incoming: 'Appel manqué'
  }
};

const targetPath = path.join(__dirname, '../../frontend/messages/fr.json');
fs.writeFileSync(targetPath, JSON.stringify(frTranslations, null, 2), 'utf8');
console.log('Successfully written fr.json!');
