const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const zhPath = path.join(__dirname, '../../frontend/messages/zh.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Delete existing zh.json
if (fs.existsSync(zhPath)) {
  fs.unlinkSync(zhPath);
  console.log('Deleted existing zh.json');
}

// Complete English to Chinese dictionary
const dict = {
  // Metadata & Nav
  "stududu — Practice speaking foreign languages": "stududu — 外语口语练习",
  "Language exchange and 1:1 speaking practice platform": "语言交换与 1:1 口语练习平台",
  "Discover": "探索",
  "Messages": "消息",
  "Vocabulary": "词汇",
  "Community": "社区",
  "Profile": "个人资料",
  "Settings": "设置",
  "Admin panel": "管理面板",
  "Log out": "退出登录",
  "Log Out": "退出登录",

  // Common
  "Save changes": "保存更改",
  "Cancel": "取消",
  "Loading...": "加载中...",
  "Retry": "重试",
  "or": "或",
  "Something went wrong. Please try again.": "出错了，请重试。",

  // Home
  "Login": "登录",
  "Register": "注册",
  "Practice speaking foreign languages with": "与真正的母语者",
  "real native speakers": "练习外语口语",
  "Find your perfect language exchange partner. You teach your language, they teach yours. Entirely free, mutual-based.": "寻找您理想的语言交换伙伴。你教 your 母语，对方教对方的母语。完全免费，互帮互助。",
  "Get started now": "立即开始",

  // Settings
  "Interface language": "界面语言",
  "UI chrome only — user-generated content stays in its original language.": "仅更改界面显示语言 — 用户生成的内容保留原语言。",
  "Change password": "修改密码",
  "Share activity": "分享动态",
  "Blocked users": "已屏蔽用户",
  "Activity sharing enabled": "已启用动态分享",
  "Activity sharing disabled": "已禁用动态分享",
  "Passwords do not match.": "两次输入的密码不一致。",
  "Password updated successfully": "密码更新成功",
  "Unblocked {name}": "已解除屏蔽 {name}",
  "Minimum 8 characters, including both letters and numbers.": "至少 8 个字符，包含字母和数字。",
  "Current password": "当前密码",
  "New password": "新密码",
  "Confirm new password": "确认新密码",
  "Updating...": "更新中...",
  "Update password": "更新密码",
  "Automatically post to Community when you add a word or reach conversation milestones.": "当您添加新词汇或达到对话里程碑时，自动发布到社区。",
  "Enabled": "已启用",
  "Disabled": "已禁用",
  "You haven't blocked anyone.": "您尚未屏蔽任何用户。",
  "Unblock": "解除屏蔽",

  // Login
  "Welcome back to stududu": "欢迎回到 stududu",
  "Email": "电子邮箱",
  "Password": "密码",
  "Remember me": "记住我",
  "Forgot password?": "忘记密码？",
  "Signing in...": "正在登录...",
  "Continue with Google": "使用 Google 账号登录",
  "Sign in with Google: UI is ready. API integration will be configured once the Backend is complete.": "使用 Google 登录：界面已准备就绪。",
  "Don't have an account?": "还没有账号？",
  "Sign up now": "立即注册",
  "Learn languages with real native speakers.": "与母语者一起学习语言。",
  "You teach your language, they teach theirs. A fair exchange — no scores, no fees.": "你教 your 母语，对方教对方的母语。公平交换 — 无需积分，无需付费。",
  "Matched by complementary languages, not by score": "根据互补语言匹配，而非根据分数",
  "Direct 1:1 chat, practise your reflexes every day": "一对一直接聊天，每天练习反应能力",
  "Contributions recognised with praise, not rankings": "通过赞扬认可贡献，而非排名",
  "stududu — language exchange, Tandem style": "stududu — Tandem 风格的语言交换",

  // Register
  "Create an account": "创建账号",
  "Start your language journey": "开启您的语言学习之旅",
  "Practice speaking with real native speakers.": "与真正的母语者练习口语。",
  "You teach your language, they teach yours.": "你教 your 母语，对方教对方的母语。",
  "Display name": "显示名称",
  "First name": "名",
  "Surname": "姓",
  "Date of birth": "出生日期",
  "Day": "日",
  "Month": "月",
  "Year": "年",
  "Gender": "性别",
  "Select your gender": "选择您的性别",
  "Female": "女",
  "Male": "男",
  "Custom / Other": "自定义 / 其他",
  "Country": "国家/地区",
  "Select country": "选择国家/地区",
  "Mobile number or email address": "手机号码或电子邮箱",
  "Confirm password": "确认密码",
  "Signing up...": "正在注册...",
  "Creating account...": "正在创建账号...",
  "Sign up": "注册",
  "Sign up with Google: UI is ready. API integration will be configured once the Backend is complete.": "使用 Google 注册：界面已准备就绪。",
  "At least 8 characters": "至少 8 个字符",
  "Already have an account?": "已有账号？",
  "Login now": "立即登录",
  "Native language": "母语",
  "Learning language": "正在学习的语言",
  "Target level": "目标水平",
  "Registration successful!": "注册成功！",
  "By clicking Register, you agree to our Terms of Service and Privacy Policy.": "点击注册即表示您同意我们的服务条款和隐私政策。",
  "Password must be at least 8 characters.": "密码长度必须至少为 8 个字符。",

  // Discover
  "Find Language Partners": "探索语伴",
  "Find exchange partners to practice speaking": "寻找适合您练习口语的语言交换伙伴",
  "Just for you": "为您推荐",
  "Find someone to learn and teach languages with you.": "寻找适合与您互相学习口语的语伴。",
  "Search by name, language, or interest...": "按姓名、语言或兴趣搜索...",
  "Search by name, language, interests...": "按姓名、语言、兴趣搜索...",
  "Native": "母语",
  "Learning": "学习中",
  "Filters": "筛选",
  "All languages": "所有语言",
  "Online only": "仅看在线",
  "No partners found.": "未找到匹配的语伴。",
  "Try adjusting your search or filter options.": "尝试调整您的搜索条件或筛选器。",
  "Connect": "联系",
  "Chat now": "发起聊天",
  "Compatibility": "匹配度",
  "Shared topics": "共同话题",
  "Recommended": "推荐匹配",
  "Best matches": "最佳匹配",
  "All Members": "所有成员",
  "All members": "所有成员",
  "Level": "水平",
  "All levels": "所有水平",
  "Native speaker": "母语者",
  "Fluent": "精通",
  "Reset filters": "重置筛选",
  "Best match": "最佳匹配",
  "Showing {count} partners": "正在显示 {count} 位语伴",
  "Loading more...": "加载更多...",
  "Searching...": "搜索中...",
  "Failed to load language partners. Please try again.": "加载语伴列表失败，请重试。",
  "Failed to load members": "加载成员列表失败",
  "Match Tip": "匹配提示",
  "Match tip": "匹配提示",
  "Matching tip": "匹配提示",
  "Complete your profile to get better recommendations!": "完善您的个人资料以获取更好的匹配推荐！",
  "Profiles with a photo and full bio get way more connections!": "带照片和完整简介的个人资料能获得更多练习连接！",
  "No language partners available yet.": "暂无可用语伴。",
  "Not enough language partners to display.": "可显示的语伴数量不足。",
  "The community is growing — not enough matching partners yet, try browsing \"All members\".": "社区正在成长中 — 契合语伴不足，尝试浏览 “所有成员”。",
  "No other members yet": "暂无其他成员",
  "Not enough matching partners": "契合语伴数量不足",
  "No matching partners yet": "暂无契合语伴",
  "No filter matches": "无符合筛选条件的伙伴",
  "No partners match your criteria.": "没有符合您条件的语伴。",
  "No partners match your active filters.": "没有符合您当前筛选条件的语伴。",
  "Be the first to invite a friend!": "成为第一个邀请朋友的人吧！",
  "Try clearing your search or filters to see more members.": "尝试清除搜索或筛选器以查看更多成员。",
  "Try resetting filters or searching with a different term.": "尝试重置筛选器或更换搜索关键词。",
  "Invite your friends to join stududu!": "邀请您的朋友加入 stududu！",
  "Try switching to All members, or update your languages and interests.": "尝试切换到“所有成员”，或更新您的语言和兴趣。",
  "Try loosening your filters to see more partners.": "尝试放宽筛选条件以查看更多语伴。",
  "Refresh list": "刷新列表",
  "Active now": "当前在线",
  "Online now": "当前在线",
  "Active recently": "最近在线",
  "Recently active": "最近活跃",
  "Speaks": "教授/母语",
  "Learns": "学习中",
  "Liked": "已赞",
  "Like": "赞",
  "Unlike": "取消赞",
  "It's a Match! 🎉": "成功匹配！🎉",
  "🎉 It's a match!": "🎉 成功匹配！",
  "Message now": "立即发消息",
  "Keep discovering": "继续浏览",
  "Continue browsing": "继续浏览",
  "Load more ({remaining} left)": "加载更多 (还剩 {remaining} 人)",
  "Liked {name} — message them now in Messages!": "赞了 {name} — 现在去消息中与对方聊天吧！",
  "Unliked {name}": "已取消赞 {name}",
  "Awesome! You and {name} liked each other. Let's start chatting and practicing together.": "太棒了！您和 {name} 互相赞了对方。开始一起聊天练习吧。",
  "Partner level (language they teach)": "语伴水平（其教授语言）",
  "matching partners": "位匹配语伴",
  "Finding your best matches...": "正在为您寻找最佳匹配...",
  "Failed to load suggestions": "加载推荐失败",
  "(Native)": "(母语)",
  "(Fluent)": "(精通)",
  "Learning:": "学习中:",

  // Community
  "Language Community": "语言社区",
  "Share experiences and ask questions with learners worldwide": "与全球学习者交流经验、提出问题",
  "Create post": "发布帖子",
  "Share your language learning experience or ask a question...": "分享您的语言学习经验或提出问题...",
  "Post": "发布",
  "Posting...": "正在发布...",
  "Likes": "赞",
  "Comments": "评论",
  "Share": "分享",
  "Write a comment...": "撰写评论...",
  "No posts yet. Be the first to share!": "暂无帖子。成为第一个发布动态的人吧！",
  "All": "全部",
  "Following": "正在关注",
  "Popular": "热门",
  "Topic": "话题",
  "Community Feed": "动态大厅",
  "Connect, share experiences, and learn together.": "交流经验、寻找语伴、回答学习疑问。",
  "Search posts or topics...": "搜索帖子、话题...",
  "Feed": "最新帖子",
  "Groups": "语言小组",
  "Events": "线上活动",
  "Partner": "语伴",
  "Milestone": "里程碑",
  "Question": "提问",
  "Daily Vocab": "📚 每日词汇",
  "Save Word": "存入词汇本",
  "Saved": "已保存",
  "Next Word": "下一个词",
  "I Know This": "我已掌握",
  "Suggested Groups": "推荐语言小组",
  "Groups functionality is coming soon!": "语言小组功能即将上线！",
  "Events functionality is coming soon!": "线上活动功能即将上线！",
  "Language Groups": "语言交流小组",
  "English Practice Club": "英语口语俱乐部",
  "Japanese Beginners Corner": "日语初学交流角",
  "Korean Conversation Lounge": "韩语会话沙龙",
  "French Culture & Language": "法语文化与语言",
  "Upcoming Events": "近期线上活动",
  "Upcoming": "即将来临",
  "Sat, 8:00 PM": "周六 20:00",
  "English Speaking Practice Hour": "英语口语练习一小时",
  "Join native speakers for a relaxed conversation session via voice call.": "加入母语者语音通话，进行轻松愉快的口语交流。",
  "Join Event": "参加活动",
  "Sun, 3:00 PM": "周日 15:00",
  "Language Exchange Speed Matching": "语言交换快速匹配会",
  "Meet multiple language partners in 5-minute round-robin chats.": "在 5 分钟轮流会话中结识多位语言伙伴。",
  "Remind Me": "设置提醒",
  "Event reminder set! We'll notify you when it starts.": "已设置活动提醒！开始时我们将通知您。",
  "Previous": "上一个",
  "Translate post": "翻译帖子",
  "See translation": "查看翻译",
  "Translated": "已翻译",
  "Translation": "翻译内容",
  "Hide translation": "隐藏翻译",
  "contributed the word \"{term}\" ({language}) to the Public Library 🌐": "向公共词汇库贡献了词汇 “{term}” ({language}) 🌐",
  "just hit {hours} hours of conversation practice 🎉": "刚刚达到了 {hours} 小时的口语练习里程碑 🎉",
  "Reply to {name}...": "回复 {name}...",
  "Reply": "回复",
  "Delete": "删除",
  "Comment failed to post.": "发布评论失败。",
  "Image file is too large (max 5MB).": "图片文件过大（最大 5MB）。",
  "Edit": "编辑",
  "Are you sure you want to delete this post? This action cannot be undone.": "确定要删除此帖子吗？此操作无法撤销。",
  "Yes, delete": "是的，删除",
  "No, keep": "取消保留",
  "Editing...": "编辑中...",
  "Update": "更新",
  "Cancel edit": "取消编辑",
  "No posts in this feed yet.": "该动态列表中暂无帖子。",
  "Be the first to share your language learning journey!": "成为第一个分享语言学习心得的人吧！",
  "Just now": "刚刚",
  "Attach Image": "添加图片",
  "Attach image": "添加图片",
  "Image must be smaller than 5MB.": "图片大小必须小于 5MB。",
  "Image size must not exceed 2MB": "图片大小不能超过 2MB",
  "⚠️ Image size cannot exceed 2MB": "⚠️ 图片大小不能超过 2MB",
  "{name}'s post": "{name} 的帖子",
  "{count} members": "{count} 名成员",
  "Share what's on your mind — highlights from the community.": "分享您的想法 — 社区精选动态。",
  "What would you like to share? (tips, milestones, stories...)": "你想分享什么？（技巧、里程碑、故事...）",
  "shared:": "分享了:",
  "contributed a word to the Public Library 🌐": "向公共词汇库贡献了一个词汇 🌐",
  "Failed to send comment": "发送评论失败",
  "{count}/500": "{count}/500",
  "Delete post": "删除帖子",
  "Editing post": "正在编辑帖子",
  "No activity yet": "暂无动态",
  "Share something with the community!": "与社区分享一些想法吧！",
  "{count} min ago": "{count} 分钟前",
  "{count}h ago": "{count} 小时前",
  "STUDUDU COMMUNITY": "STUDUDU 社区",
  "Share your journey, find practice partners, and join events.": "分享您的旅程、寻找口语伙伴、参加线上活动。",
  "Newsfeed": "动态大厅",
  "Find Partner": "寻找语伴",
  "Share Achievement": "分享成就",
  "Ask Practice": "求助练习",
  "TODAY'S NEW VOCABULARY": "今天的每日词汇",
  "Already Know": "我已掌握",
  "Join": "加入",
  "Joined": "已加入",
  "Language Groups feature is currently in development. Explore suggested groups on the right rail!": "语言小组功能正在开发中。探索右侧栏中的推荐小组！",
  "Events is where Admins will host exams and competitions for users to practice together. Coming soon!": "活动是管理员举办考试和比赛以供用户一起练习的地方。即将推出！",
  "Daily English speaking practice community with native speakers.": "与母语者一起进行的每日英语口语练习社区。",
  "Japanese Kaiwa speaking practice and cultural exchange group.": "日语会话练习与文化交流小组。",
  "Korean speaking practice and K-Culture exchange group.": "韩语口语练习与韩流文化交流小组。",
  "French conversation exchange group from basic to advanced levels.": "从基础到高级水平的法语会话交流小组。",
  "Events & Exam Competitions": "线上活动与考试竞赛",
  "UPCOMING": "即将来临",
  "15:00 - This Sunday": "本周日 15:00",
  "🏆 IELTS Speaking Reflex Competition (OJT Round 1)": "🏆 雅思考官口语应变赛 (第一轮)",
  "Admins host live exam rooms to compete in speaking reflex scores together.": "管理员举办实时考场，共同比拼口语反应分数。",
  "Register Exam": "报名考试",
  "20:00 - Every Wednesday": "每周三 20:00",
  "🌸 N3 Vocabulary & Kaiwa Kanji Challenge": "🌸 N3 词汇与会话汉字挑战赛",
  "Fast-paced 20 Kanji questions pairing students with Native Speakers.": "紧凑的 20 道汉字题目，将学生与母语者配对。",
  "Interested": "感兴趣",
  "ℹ️ Event registration feature is coming soon!": "ℹ️ 活动报名功能即将推出！",
  "Previous Word": "上一个词",
  "Auto Translation": "自动翻译",
  "Tiếng Việt": "Tiếng Việt",
  "English": "English",
  "Spanish": "Español",

  // Language Switcher
  "Select language": "选择语言",

  // Vocabulary
  "My Notebook": "我的词汇本",
  "My notebook": "我的词汇本",
  "Public Library": "公共词汇库",
  "Public library": "公共词汇库",
  "Search my vocabulary...": "搜索我的词汇...",
  "Search public library...": "搜索公共词汇库...",
  "Search words, notes...": "搜索单词、笔记...",
  "Add word": "添加新词",
  "Explore words contributed by the community. Add them to your notebook in one click.": "探索社区成员贡献的词汇，一键添加到您的词汇本。",
  "Words saved by ≥3 members automatically enter the public library — sorted by save count.": "被 3 名及以上成员保存的词汇自动进入公共词汇库 — 按保存次数排序。",
  "Chat": "聊天",
  "From chat": "来自聊天",
  "Notebook": "词汇本",
  "Manual": "手动添加",
  "In Library": "已在库中",
  "In public library": "已在公共库中",
  "No definition available.": "暂无定义。",
  "No definition or notes yet": "暂无定义或笔记",
  "Deleted from vocabulary notebook.": "已从词汇本中删除。",
  "Word removed from your notebook": "已从您的词汇本中移除该单词",
  "Definition": "定义",
  "Example": "例句",
  "Personal Note": "个人笔记",
  "Personal note": "个人笔记",
  "No vocabulary words yet!": "暂无词汇！",
  "Vocabulary notebook is empty": "词汇本为空",
  "No words match your search.": "没有符合您搜索条件的词汇。",
  "No words found": "未找到相关词汇",
  "Try searching for a different word.": "尝试搜索其他单词。",
  "Highlight words during chats or add manually to grow your vocabulary.": "在聊天中高亮选择单词或手动添加以扩大词汇量。",
  "Try searching with a different keyword.": "尝试使用其他关键词搜索。",
  "Add your first word": "添加您的第一个单词",
  "Successfully contributed word to public library!": "成功向公共词汇库贡献词汇！",
  "🙌 Thank you for your contribution!": "🙌 感谢您的贡献！",
  "Contribute to Library": "贡献至公共库",
  "Contribute": "贡献",
  "Please provide a definition for this word.": "请为此单词提供定义。",
  "⏳ Need definition": "⏳ 需要定义",
  "Add Word to Vocabulary": "添加单词到词汇本",
  "Save to Vocabulary Notebook": "保存到词汇本",
  "Language": "语言",
  "Term / Word": "单词 / 词汇",
  "Word / phrase (max 100 characters)": "单词 / 短语（最多 100 个字符）",
  "Type word here...": "在此输入单词...",
  "Enter word to save...": "输入要保存的单词...",
  "Enter definition...": "输入定义...",
  "Explain the meaning of the word...": "解释单词的含义...",
  "Enter an example sentence using this word...": "输入使用该单词的例句...",
  "Select the correct definition below:": "请在下方选择正确的定义:",
  "Choose the most accurate translation below:": "请在下方选择最准确的翻译:",
  "Vocabulary Practice": "词汇练习",
  "VOCABULARY QUIZ & PRACTICE": "词汇测验与练习",
  "Vocabulary & Quiz": "词汇 & 测验",
  "Manage and review your saved words": "管理并复习您保存的词汇",
  "Practice with multiple choice quizzes and manage your personal vocabulary notebook.": "通过多项选择测验进行练习，并管理您的个人词汇本。",
  "Total Words": "总词汇量",
  "Total words": "总词汇量",
  "Mastered": "已掌握",
  "Need Review": "需要复习",
  "Needs review": "需要复习",
  "Quiz Practice": "测验练习",
  "Quiz Review": "测验复习",
  "Loading quiz questions...": "正在加载测验题目...",
  "Loading quiz data...": "正在加载测验数据...",
  "Quiz Results": "测验结果",
  "Quiz Session Result": "测验环节结果",
  "Total Score": "总得分",
  "+10 pts / correct answer": "答对每题 +10 分",
  "Correct Answers": "正确回答",
  "Moved to Mastered": "已移至已掌握",
  "Accuracy Rate": "正确率",
  "Accuracy": "正确率",
  "Start New Quiz": "开始新测验",
  "Contribute for \"{term}\"": "为 “{term}” 提供贡献",
  "{count} saves": "{count} 次保存",
  "✅ Saved \"{term}\"": "✅ 已保存 “{term}”",
  "\"{term}\" already in notebook — note updated": "“{term}” 已在词汇本中 — 已更新笔记",
  "Notebook ({count})": "词汇本 ({count})",
  "Review unmastered ({count})": "复习未掌握 ({count})",
  "Review all ({count})": "复习全部 ({count})",
  "You completed the review session with {count} questions.": "您完成了共 {count} 道题目的复习。",
  "Question {current} / {total}": "题目 {current} / {total}",
  "{points} pts": "{points} 分",
  "{streak} Streak!": "{streak} 连胜！",
  "Review all words ({count})": "复习所有单词 ({count})",
  "Total: {count} words": "共计: {count} 个词",
  "Source: {source}": "来源: {source}",
  "Deleted \"{term}\" from vocabulary notebook.": "已从词汇本中删除 “{term}”。",
  "🌐 {count} people saved this": "🌐 {count} 人保存了此词",
  "{count} people saved this word": "{count} 人保存了此词汇",
  "View Vocabulary Notebook": "查看词汇本",
  "Listen to pronunciation": "收听发音",
  "Next Question": "下一题",
  "View Quiz Results": "查看测验结果",
  "You've mastered all words in review!": "您已掌握复习中的所有单词！",
  "Great job! Switch to 'Review All' to reinforce your knowledge.": "干得好！切换到“复习全部”以进一步巩固知识。",
  "No vocabulary words in notebook yet!": "词汇本中暂无单词！",
  "Add new words to your notebook when translating or chatting.": "在翻译或聊天时添加新词汇到您的词汇本。",
  "Personal Vocabulary Notebook": "个人词汇本",
  "All saved words from translation, chat, and manual entries.": "所有从翻译、聊天和手动添加的保存单词。",
  "New": "新词",
  "Search vocabulary...": "搜索词汇...",
  "Delete word": "删除单词",
  "No matching vocabulary words found.": "未找到匹配的词汇。",
  "Excellent! 🌟": "太棒了！🌟",
  "Great! 👏": "很好！👏",
  "Good! 👍": "不错！👍",
  "Keep Trying! 💡": "继续加油！💡",
  "👉 Select the correct definition below:": "👉 请在下方选择正确的定义:",
  "Translate:": "翻译:",
  "📝 Definition": "📝 定义",
  "💡 Example": "💡 例句",
  "No information found for this word.": "未找到该单词的相关信息。",
  "Unable to look up word right now. Try again later.": "暂时无法查询该单词，请稍后再试。",
  "Save to Notebook": "存入词汇本",

  // Profile
  "My Profile": "我的个人资料",
  "Edit profile": "编辑资料",
  "Posts": "动态",
  "About": "关于",
  "{count} posts": "{count} 条动态",
  "You haven't posted anything yet.": "您尚未发布任何动态。",
  "Share a post with the community!": "与社区分享一条动态吧！",
  "Create post": "发布动态",
  "What's on your mind, {name}?": "{name}，您在想什么？",
  "Lives in": "现居",
  "Gender": "性别",
  "Timezone": "时区",
  "Speaks": "教授/母语",
  "Learns": "学习中",
  "Level": "水平",
  "Native": "母语",
  "Fluent": "精通",
  "Edit": "编辑",
  "Profile completion": "资料完成度",
  "Trust & activity": "信任与活跃度",
  "Languages": "语言",
  "Can teach": "可以教授",
  "Wants to learn": "想要学习",
  "None": "无",
  "About me": "个人简介",
  "You haven't written an introduction yet — add a few lines to get matched easily.": "您尚未填写个人简介 — 添加几句话可以让您更容易匹配到语伴。",
  "Member hasn't written an introduction yet.": "该成员尚未填写个人简介。",
  "Intent": "学习目标",
  "Not specified": "未指定",
  "Availability & Timezone": "空闲时间与时区",
  "Availability not set": "未设置空闲时间",
  "Interests": "兴趣爱好",
  "Interests not chosen": "未选择兴趣",
  "Failed to load profile": "加载个人资料失败",
  "Add avatar photo": "添加头像照片",
  "Write personal introduction": "填写个人简介",
  "Add language you can teach": "添加您可以教授的语言",
  "Add language you want to learn": "添加您想要学习的语言",
  "Choose interests": "选择兴趣爱好",
  "Choose learning intent": "选择学习目标",
  "Report": "举报",
  "Block": "屏蔽",
  "Recognize": "认可/赞扬",
  "🏅 Recognition submitted. Thank you!": "🏅 认可提交成功，感谢您的反馈！",
  "No endorsements yet": "暂无社区认可",
  "{count} hours of practice": "{count} 小时练习",
  "{count} conversations": "{count} 次对话",
  "Endorse {name}": "认可 {name}",
  "Choose what you'd like to endorse after talking with {name} — no rating, just qualitative appreciation.": "选择您在与 {name} 交流后的评价 — 无需评分，给与正面认可。",
  "✓ already endorsed": "✓ 已完成认可",
  "Sending...": "发送中...",
  "Submit endorsement": "提交认可",
  "Native proficiency": "母语/精通水平",
  "Cultural/Social knowledge": "文化/社会知识",
  "Deep expertise": "专业领域知识",
  "Friendly": "友善热情",
  "Recognition from community": "来自社区的认可",
  "Report submitted. Thank you!": "举报已提交，感谢您的反馈！",
  "Blocked {name}": "已屏蔽 {name}",
  "💜 Liked {name} — start a conversation!": "💜 赞了 {name} — 发起对话吧！",
  "User not found": "未找到该用户",
  "Message": "发消息",
  "Basic Information": "基本信息",
  "Avatar image": "头像图片",
  "Select photo": "选择照片",
  "Delete photo": "删除照片",
  "JPG/PNG — image will be compressed automatically.": "JPG/PNG — 图片将自动压缩。",
  "Cannot read this photo, try another one.": "无法读取此照片，请尝试其他照片。",
  "Date of Birth": "出生日期",
  "Do not disclose": "保密",
  "Other": "其他",
  "City": "城市",
  "E.g. Hanoi": "例如：北京",
  "Display Name": "显示名称",
  "Display name cannot be empty.": "显示名称不能为空。",
  "Please select at least 1 teachable language and 1 language to learn.": "请至少选择 1 门母语/精通语言和 1 门学习语言。",
  "Your timezone": "您的时区",
  "Availability (max 2)": "空闲时段（最多 2 个）",
  "{count}/2 selected": "{count}/2 已选择",
  "Time": "时间",
  "Availability slots help partners request chat schedule more easily (timezone auto-converted).": "设置空闲时段有助于语伴更方便地与您预约练习（时区将自动转换）。",
  "Matching Criteria": "匹配偏好",
  "Preferred language": "偏好语言",
  "No preference": "无偏好",
  "Desired partner level": "期望语伴水平",
  "Any": "不限",
  "A complete profile gets you more matches — update it any time.": "完整的资料有助于获取更多匹配 — 可随时更新。",
  "This is your profile": "这是您的个人资料",
  "Your name": "您的姓名",
  "Change profile photo": "更换头像照片",
  "Preview": "预览",
  "This is how others see you in Discover.": "这是其他人在探索页面中看到您的样子。",
  "Speaks:": "教授/母语:",
  "Learns:": "学习中:",
  "Not added": "未添加",
  "Shared interests": "共同兴趣",
  "Pick topics you enjoy talking about.": "选择您喜欢交流的话题。",
  "Helps us suggest better partners.": "有助于我们为您推荐更合适的语伴。",
  "No posts shared yet.": "尚未发布任何动态。",

  // Chat
  "Say hi to start the conversation 👋": "发送打招呼开启对话 👋",
  "You: ": "你: ",
  "📷 Photo": "📷 照片",
  "📅 Time Invitation": "📅 练习预约邀请",
  "Translation failed, try again later": "翻译失败，请稍后再试",
  "Failed to send time invitation": "发送预约邀请失败",
  "Failed to respond to invitation": "回应邀请失败",
  "Search conversations...": "搜索对话...",
  "No conversations found": "未找到相关对话",
  "No conversations yet": "暂无对话",
  "Go to Discover to find practice partners.": "去探索页面寻找口语练习伙伴吧。",
  "Go to Discover": "前往探索",
  "Select a conversation": "选择一个对话",
  "Start practicing with your partner.": "开始与您的语伴练习口语。",
  "(your time)": "(您的本地时间)",
  "Schedule chat": "预约练习时间",
  "Translation board": "翻译面板",
  "View profile": "查看资料",
  "{name}'s free slots:": "{name} 的空闲时段:",
  "✓ Common free slots!": "✓ 存在共同空闲时间！",
  "Reconnecting...": "正在重新连接...",
  "Save word": "存入词汇本",
  "You matched!": "成功匹配！",
  "Send a greeting to start practicing.": "发送问候语开始口语练习吧。",
  "You sent an invitation": "您发送了一份预约邀请",
  "{name} invited you to chat": "{name} 邀请您进行练习",
  "(based on your computer's timezone)": "(基于您电脑的时区)",
  "Accept": "接受",
  "Decline": "拒绝",
  "✅ Accepted — will remind 30m prior": "✅ 已接受 — 将在开始前 30 分钟提醒",
  "⌛ Expired (no response in 48h)": "⌛ 已过期 (48 小时内未回应)",
  "❌ Declined": "❌ 已拒绝",
  "🚫 Cancelled": "🚫 已取消",
  "Reason: {reason}": "原因: {reason}",
  "Cancel Scheduled Chat": "取消已预约的练习",
  "Enter a reason for cancellation...": "请输入取消原因...",
  "Successfully cancelled scheduled chat": "已成功取消预约练习",
  "Read": "已读",
  "Notifications": "通知",
  "Mute": "静音",
  "Unmute": "取消静音",
  "Sent": "已发送",
  "Add reaction": "添加回应",
  "Emoji": "表情符号",
  "Send photo": "发送照片",
  "Type a message...": "输入消息...",
  "Report submitted. Thank you!": "举报已提交，感谢您的反馈！",
  "Blocked {name}": "已屏蔽 {name}",
  "\"{term}\" already in your notebook": "“{term}” 已存在于您的词汇本中",
  "✅ Saved \"{term}\" to Vocabulary Notebook": "✅ 已保存 “{term}” 到词汇本",
  "Translating...": "翻译中...",
  "Hide": "隐藏",
  "Translate": "翻译",

  // Forgot password
  "Forgot Password": "重置密码",
  "Enter your email to receive a password reset link": "输入您的邮箱地址以接收密码重置链接",
  "If the email is valid, we have sent a password reset link. The link will expire in 30 minutes.": "如果邮箱有效，我们已发送重置链接，请在 30 分钟内查收。",
  "Back to login": "返回登录",
  "Your email": "您的电子邮箱",
  "Send reset link": "发送重置链接",

  // Onboarding
  "Languages": "语言",
  "Interests": "兴趣",
  "Completion": "完成",
  "Please select at least 1 teachable language and 1 language to learn.": "请至少选择 1 门母语/精通语言和 1 门学习语言。",
  "Please write a personal bio.": "请填写个人简介 (Bio)。",
  "I speak (can teach)": "我会说 (可教授)",
  "Select language": "选择语言",
  "Add": "添加",
  "I want to learn": "我想学习",
  "Saving...": "保存中...",
  "Continue": "继续",
  "Your interests": "您的兴趣爱好",
  "Select topics that interest you (optional).": "选择您感兴趣的话题（可选）。",
  "Back": "返回",
  "Complete your profile": "完成您的个人资料",
  "A little bit about yourself will help you get matched easily.": "填写一点关于自己的信息有助于更轻松地匹配语伴。",
  "Personal introduction (Bio)": "个人简介 (Bio)",
  "E.g. I am learning English for study abroad. I love coffee on weekends...": "例如：我正在学习英语以便出国留学。周末喜欢喝咖啡...",
  "Primary learning intent": "主要学习目标",
  "Finish & Discover": "完成并探索",
  "Beginner": "零基础/初学者",
  "Elementary": "基础",
  "Intermediate": "中级",
  "Upper Intermediate": "中高级",
  "Casual conversation": "日常交流",
  "Exam prep (IELTS, JLPT...)": "备考 (IELTS, JLPT...)",
  "Travel": "旅游出行",
  "Work": "工作职场",

  // Notifications & Topics & Call
  "You have no notifications.": "您暂无通知。",
  "Mark all as read": "全部标记为已读",
  "{name} started following you.": "{name} 开始关注了您。",
  "{name} posted a new update.": "{name} 发布了新动态。",
  "{name} liked you.": "{name} 赞了您。",
  "You and {name} have matched!": "您与 {name} 成功匹配！",
  "Popular Topics": "热门话题",
  "Select topics you are interested in": "选择您感兴趣的话题",
  "Music": "音乐",
  "Movies": "电影影视",
  "Food": "美食烹饪",
  "Sports": "体育运动",
  "Technology": "科技数码",
  "Books": "阅读书籍",
  "Gaming": "游戏电竞",
  "Culture": "文化历史",
  "Exams (IELTS/TOEIC...)": "语言考试 (IELTS/TOEIC...)",
  "Voice call": "语音通话",
  "Calling…": "正在呼叫...",
  "{name} is calling": "{name} 向您发起通话",
  "Incoming voice call": "语音通话来电",
  "Incoming video call": "视频通话来电",
  "Answer without camera": "仅语音接听",
  "Hang up": "挂断",
  "Turn camera off": "关闭摄像头",
  "Turn camera on": "开启摄像头",
  "Switch front/back camera": "切换前/后摄像头",
  "Your partner turned their camera off": "对方关闭了摄像头",
  "Weak connection…": "网络连接不稳定...",
  "Your partner declined the call": "对方拒绝了通话",
  "No answer": "无人接听",
  "{name} is on another call": "{name} 正在通话中",
  "{name} is not online": "{name} 当前不在线",
  "Connection lost, the call ended": "连接中断，通话已结束",
  "The call reached the 30-minute limit": "通话已达到 30 分钟时长限制",
  "The call will end automatically in {minutes} minutes": "通话将在 {minutes} 分钟后自动结束",
  "Your browser blocked the microphone because the page is not on HTTPS": "由于页面未处于 HTTPS 环境，浏览器阻止了麦克风使用",
  "Allow microphone access in your browser settings": "请在浏览器设置中允许使用麦克风",
  "No microphone found": "未检测到麦克风设备",
  "Camera is currently used by another app or tab — continuing with audio call": "摄像头正在被其他应用或标签页使用 — 继续进行语音通话",
  "Camera is blocked — the call continues, your partner just won't see you": "摄像头已被阻止 — 通话继续，但对方无法看到您",
  "Could not start the call": "无法发起通话",
  "Voice call · {duration}": "语音通话 · {duration}",
  "Video call · {duration}": "视频通话 · {duration}",
  "Call declined": "已拒绝通话",
  "You called but nobody answered": "呼出无人接听",
  "Missed call": "未接来电",
  "Video call": "视频通话",
  "Voice call": "语音通话"
};

// Recursive function to map en.json to zh.json
function translateObject(source) {
  if (typeof source === 'string') {
    if (dict[source]) {
      return dict[source];
    }
    console.warn('Missing translation string:', JSON.stringify(source));
    return source;
  }
  if (Array.isArray(source)) {
    return source.map(translateObject);
  }
  if (typeof source === 'object' && source !== null) {
    const res = {};
    for (const k in source) {
      res[k] = translateObject(source[k]);
    }
    return res;
  }
  return source;
}

const newZh = translateObject(en);

// Ensure exact langSwitcher values
newZh.langSwitcher = {
  label: "选择语言",
  en: "English",
  vi: "Tiếng Việt",
  fr: "Français",
  es: "Español",
  zh: "中文"
};

fs.writeFileSync(zhPath, JSON.stringify(newZh, null, 2), 'utf8');
console.log('Successfully created brand new zh.json mapped from en.json!');
