const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const zhPath = path.join(__dirname, '../../frontend/messages/zh.json');

// Delete existing zh.json first as requested by user
if (fs.existsSync(zhPath)) {
  fs.unlinkSync(zhPath);
  console.log('Deleted old zh.json');
}

const zhData = {
  "metadata": {
    "title": "stududu — 外语口语练习",
    "description": "语言交换与 1:1 口语练习平台"
  },
  "nav": {
    "discover": "探索",
    "messages": "消息",
    "vocabulary": "词汇",
    "community": "社区",
    "profile": "个人资料"
  },
  "menu": {
    "profile": "个人资料",
    "settings": "设置",
    "admin": "管理面板",
    "logout": "退出登录"
  },
  "settings": {
    "title": "设置",
    "language": "界面语言",
    "language_hint": "仅更改界面显示语言 — 用户生成的内容保留原语言。",
    "password": "修改密码",
    "shareActivity": "分享动态",
    "blocked": "已屏蔽用户",
    "share_activity_enabled": "已启用动态分享",
    "share_activity_disabled": "已禁用动态分享",
    "password_mismatch": "两次输入的密码不一致。",
    "password_success": "密码更新成功",
    "unblock_success": "已解除屏蔽 {name}",
    "password_hint": "至少 8 个字符，包含字母和数字。",
    "curr_password_placeholder": "当前密码",
    "new_password_placeholder": "新密码",
    "confirm_password_placeholder": "确认新密码",
    "updating": "更新中...",
    "update_password": "更新密码",
    "share_activity_hint": "当您添加新词汇或达到对话里程碑时，自动发布到社区。",
    "enabled": "已启用",
    "disabled": "已禁用",
    "no_blocked": "您尚未屏蔽任何用户。",
    "unblock": "解除屏蔽",
    "logout": "退出登录"
  },
  "common": {
    "save": "保存更改",
    "cancel": "取消",
    "loading": "加载中...",
    "retry": "重试",
    "or": "或",
    "error_generic": "出错了，请重试。"
  },
  "home": {
    "login": "登录",
    "register": "注册",
    "title_part1": "与真正的母语者",
    "title_part2": "练习外语口语",
    "description": "寻找您理想的语言交换伙伴。你教 your 母语，对方教对方的母语。完全免费，互帮互助。",
    "get_started": "立即开始"
  },
  "login": {
    "title": "登录",
    "welcome": "欢迎回到 stududu",
    "email": "电子邮箱",
    "password": "密码",
    "remember": "记住我",
    "forgot": "忘记密码？",
    "submit": "登录",
    "submitting": "正在登录...",
    "google": "使用 Google 账号登录",
    "google_notice": "使用 Google 登录：界面已准备就绪。",
    "no_account": "还没有账号？",
    "register_link": "立即注册",
    "hero_title": "与母语者一起学习语言。",
    "hero_sub": "你教 your 母语，对方教对方的母语。公平交换 — 无需积分，无需付费。",
    "hero_p1": "根据互补语言匹配，而非根据分数",
    "hero_p2": "一对一直接聊天，每天练习反应能力",
    "hero_p3": "通过赞扬认可贡献，而非排名",
    "hero_footer": "stududu — Tandem 风格的语言交换"
  },
  "register": {
    "title": "创建账号",
    "subtitle": "开启您的语言学习之旅",
    "hero_title": "与真正的母语者练习口语。",
    "hero_subtitle": "你教 your 母语，对方教对方的母语。",
    "display_name": "显示名称",
    "first_name": "名",
    "surname": "姓",
    "dob": "出生日期",
    "day": "日",
    "month": "月",
    "year": "年",
    "gender": "性别",
    "gender_placeholder": "选择您的性别",
    "gender_female": "女",
    "gender_male": "男",
    "gender_custom": "自定义 / 其他",
    "country": "国家/地区",
    "select_country": "选择国家/地区",
    "email": "手机号码或电子邮箱",
    "password": "密码",
    "password_confirm": "确认密码",
    "submit": "注册",
    "submitting": "正在注册...",
    "google": "使用 Google 账号注册",
    "has_account": "已有账号？",
    "login_link": "登录",
    "native_language": "母语",
    "learning_language": "正在学习的语言",
    "target_level": "目标水平",
    "password_hint": "至少 8 个字符，包含字母和数字。",
    "password_mismatch": "两次输入的密码不一致。",
    "register_success": "注册成功！",
    "terms_notice": "点击注册即表示您同意我们的服务条款和隐私政策。"
  },
  "discover": {
    "title": "探索语伴",
    "subtitle": "寻找适合您练习口语的语言交换伙伴",
    "search_placeholder": "按姓名、语言或兴趣搜索...",
    "native_lang": "母语",
    "learning_lang": "学习中",
    "filters": "筛选",
    "all_languages": "所有语言",
    "online_only": "仅看在线",
    "no_partners": "未找到匹配的语伴。",
    "try_adjusting": "尝试调整您的搜索条件或筛选器。",
    "connect": "联系",
    "chat_now": "发起聊天",
    "compatibility": "匹配度",
    "topics": "共同话题",
    "card_native": "母语",
    "card_fluent": "精通",
    "card_learning": "学习中",
    "filter_all": "全部",
    "filter_native": "母语",
    "filter_learning": "学习中",
    "filter_gender": "性别",
    "gender_any": "不限",
    "filter_sort": "排序方式",
    "sort_recommended": "推荐匹配",
    "sort_recent": "最新注册",
    "sort_active": "最近活跃",
    "active_now": "在线",
    "active_recent": "最近在线",
    "active_days": "{days}天前在线",
    "like_btn": "赞",
    "liked_btn": "已赞",
    "match_tag": "契合度高",
    "shared_topics_count": "{count} 个共同话题",
    "location_unk": "未知地点",
    "error_generic": "加载伙伴失败，请稍后重试。",
    "load_more": "加载更多 (还剩 {remaining} 人)",
    "liked_toast": "赞了 {name} — 现在去消息中与对方聊天吧！",
    "card_unliked_toast": "已取消赞 {name}",
    "match_desc": "太棒了！您和 {name} 互相赞了对方。开始一起聊天练习吧。"
  },
  "community": {
    "title": "语言社区",
    "subtitle": "与全球学习者交流经验、提出问题",
    "create_post": "发布帖子",
    "post_placeholder": "分享您的语言学习经验或提出问题...",
    "post": "发布",
    "posting": "正在发布...",
    "likes": "赞",
    "comments": "评论",
    "share": "分享",
    "write_comment": "撰写评论...",
    "no_posts": "暂无帖子。成为第一个发布动态的人吧！",
    "filter_all": "全部",
    "filter_following": "正在关注",
    "filter_popular": "热门",
    "topic_tag": "话题",
    "heading": "学习社区",
    "subheading": "交流经验、寻找语伴、回答学习疑问。",
    "search_placeholder": "搜索帖子、话题...",
    "tab_all": "最新帖子",
    "tab_following": "关注的动态",
    "tab_popular": "热门讨论",
    "create_title": "发帖",
    "title_placeholder": "标题（可选）",
    "topic_select": "选择主题（可选）",
    "media_url_placeholder": "图片/视频 URL（可选）",
    "btn_cancel": "取消",
    "btn_post": "发布",
    "btn_posting": "发布中...",
    "author_fallback": "匿名学习者",
    "likes_count": "{count} 赞",
    "comments_count": "{count} 评论",
    "btn_like": "赞",
    "btn_liked": "已赞",
    "btn_comment": "评论",
    "comments_section_title": "评论 ({count})",
    "comment_input_placeholder": "撰写公开回复...",
    "btn_send_comment": "发送",
    "btn_sending_comment": "发送中...",
    "delete_post": "删除帖子",
    "delete_confirm": "确定要删除此帖子吗？此操作无法撤销。",
    "badge_daily_vocab": "📚 每日词汇成果",
    "badge_milestone": "🎉 达成口语练习里程碑！",
    "empty_posts": "暂无帖子。发帖分享您的学习心得吧！",
    "empty_following": "您关注的人尚未发布任何动态。",
    "sidebar_topics": "热门话题",
    "sidebar_groups": "推荐语言小组",
    "join_group": "加入",
    "joined_group": "已加入",
    "suggested_partners": "为您推荐的语伴",
    "post_created_toast": "帖子发布成功！",
    "post_deleted_toast": "帖子已删除。",
    "like_error_toast": "无法对帖子点赞，请重试。",
    "comment_error_toast": "发布评论失败，请重试。",
    "post_word": "向公共词汇库贡献了词汇 “{term}” ({language}) 🌐",
    "post_milestone": "刚刚达到了 {hours} 小时的口语练习里程碑 🎉",
    "reply_placeholder": "回复 {name}...",
    "char_count": "{count}/500",
    "time_minutes_ago": "{count} 分钟前",
    "time_hours_ago": "{count} 小时前",
    "report_post_target": "{name} 的帖子",
    "members_count": "{count} 名成员"
  },
  "langSwitcher": {
    "label": "选择语言",
    "en": "English",
    "vi": "Tiếng Việt",
    "fr": "Français",
    "es": "Español",
    "zh": "中文"
  },
  "vocabulary": {
    "title": "我的词汇本",
    "subtitle": "在对话中保存并复习新单词",
    "add_word": "添加新词",
    "word_placeholder": "输入单词...",
    "translation_placeholder": "输入翻译...",
    "example_placeholder": "例句（可选）...",
    "save": "保存单词",
    "search": "搜索词汇...",
    "empty": "您的词汇本为空。",
    "empty_hint": "在聊天中长按或选择文本以添加新词。",
    "mastered": "已掌握",
    "learning": "学习中",
    "review": "复习模式",
    "quiz": "词汇测验",
    "delete_confirm": "确定要删除此单词吗？",
    "heading": "每日词汇 & 复习",
    "subheading": "每天学习 5 个精选新词，并通过快速测验巩固复习。",
    "tab_daily": "🔥 每日词汇 (5)",
    "tab_review": "🎯 词汇测验",
    "tab_notebook": "📚 词汇本",
    "daily_card_title": " today 的每日词汇卡片",
    "daily_card_desc": "根据您正在学习的语言为您精准推荐。",
    "btn_mastered": "标记为已掌握",
    "btn_learning": "标记为学习中",
    "btn_audio": "发音",
    "btn_generate_new": "生成新词包",
    "quiz_title": "智能词汇测验",
    "quiz_desc": "从您的词汇本中选择正确定义以提高记忆效果。",
    "quiz_score": "测验得分: {score} / {total}",
    "quiz_complete_title": "测验完成！🎉",
    "quiz_complete_desc": "太棒了！您成功完成了今天的复习。",
    "btn_restart_quiz": "重新测验",
    "btn_view_notebook": "查看词汇本",
    "question_progress": "题目 {current} / {total}",
    "points": "{points} 分",
    "streak": "{streak} 连胜！",
    "status_mastered_label": "已掌握",
    "status_learning_label": "学习中",
    "btn_audio_tooltip": "收听发音",
    "btn_next_question": "下一题",
    "btn_view_score": "查看测验结果",
    "empty_learning_title": "您已掌握复习中的所有单词！",
    "empty_learning_desc": "干得好！切换到“复习全部”以进一步巩固知识。",
    "empty_notebook_title": "词汇本中暂无单词！",
    empty_notebook_desc: "在翻译或聊天时添加新词汇到您的词汇本。",
    "btn_review_all_full": "复习所有单词 ({count})",
    "notebook_heading": "个人词汇本",
    "notebook_subheading": "所有从翻译、聊天和手动添加的保存单词。",
    "total_count_label": "共计: {count} 个词",
    "filter_all": "全部",
    "filter_new": "新词",
    "filter_learning": "学习中",
    "filter_mastered": "已掌握",
    "search_placeholder_notebook": "搜索词汇...",
    "source_chat_label": "聊天",
    "source_manual_label": "词汇本",
    "source_community_label": "社区",
    "source_prefix": "来源: {source}",
    "btn_delete_tooltip": "删除单词",
    "deleted_toast_message": "已从词汇本中删除 “{term}”。",
    "no_words_found": "未找到匹配的词汇。",
    "rank_excellent": "太棒了！🌟",
    "rank_good": "很好！👏",
    "rank_fair": "不错！👍",
    "rank_needs_work": "继续加油！💡",
    "select_correct_def_prompt": "👉 请在下方选择正确的定义:",
    "translation_label": "翻译:",
    "definition_heading": "📝 定义",
    "example_heading": "💡 例句",
    "no_info": "未找到该单词的相关信息。",
    "saved_by_users": "🌐 {count} 人保存了此词",
    "lookup_error": "暂时无法查询该单词，请稍后再试。",
    "saving_btn": "保存中...",
    "save_to_notebook_btn": "存入词汇本",
    "saved_by_count": "{count} 人保存了此词汇",
    "contrib_title": "为 “{term}” 提供贡献",
    "save_count_label": "{count} 次保存",
    "save_success": "✅ 已保存 “{term}”",
    "save_exists": "“{term}” 已在词汇本中 — 已更新笔记",
    "tab_notebook": "词汇本 ({count})",
    "btn_review_learning": "复习未掌握 ({count})",
    "btn_review_all": "复习全部 ({count})",
    "quiz_result_desc": "您完成了共 {count} 道题目的复习。"
  },
  "profile": {
    "title_me": "我的个人资料",
    "edit_profile": "编辑资料",
    "settings": "设置",
    "tab_posts": "动态",
    "tab_about": "关于",
    "posts_title": "动态",
    "posts_count": "{count} 条动态",
    "no_posts_me": "您尚未发布任何动态。",
    "create_post_hint": "与社区分享一条动态吧！",
    "create_post_btn": "发布动态",
    "post_placeholder": "{name}，您在想什么？",
    "lives_in": "现居",
    "gender_label": "性别",
    "timezone_label_short": "时区",
    "speaks_label": "母语/精通",
    "learns_label": "学习中",
    "level_label": "水平",
    "native_label": "母语",
    "fluent_label": "精通",
    "edit_btn": "编辑",
    "completion": "资料完成度",
    "trust_activity": "信任与活跃度",
    "languages": "语言",
    "can_teach": "可以教授",
    "want_learn": "想要学习",
    "none": "无",
    "intro": "个人简介",
    "no_intro_me": "您尚未填写个人简介 — 添加几句话可以让您更容易匹配到语伴。",
    "no_intro_other": "该成员尚未填写个人简介。",
    "intent": "学习目标",
    "not_specified": "未指定",
    "availability": "空闲时间与时区",
    "no_availability": "未设置空闲时间",
    "interests": "兴趣爱好",
    "no_interests": "未选择兴趣",
    "loading_error": "加载个人资料失败",
    "hint_avatar": "添加头像照片",
    "hint_bio": "填写个人简介",
    "hint_teach": "添加您可以教授的语言",
    "hint_learn": "添加您想要学习的语言",
    "hint_interests": "选择兴趣爱好",
    "hint_intent": "选择学习目标",
    "report": "举报",
    "block": "屏蔽",
    "endorse_btn": "认可/赞扬",
    "endorse_success_toast": "🏅 认可提交成功，感谢您的反馈！",
    "no_endorsements": "暂无社区认可",
    "chat_hours": "{count} 小时练习",
    "conversations": "{count} 次对话",
    "endorse_title": "认可 {name}",
    "endorse_desc": "选择您在与 {name} 交流后的评价 — 无需评分，给与正面认可。",
    "endorse_already_given": "✓ 已完成认可",
    "sending": "发送中...",
    "submit_endorse": "提交认可",
    "lang_proficiency": "母语/精通水平",
    "social_knowledge": "文化/社会知识",
    "niche_expertise": "专业领域知识",
    "friendliness": "友善热情",
    "trust_activity_other": "来自社区的认可",
    "report_success_toast": "举报已提交，感谢您的反馈！",
    "block_success_toast": "已屏蔽 {name}",
    "like_success_toast": "💜 赞了 {name} — 发起对话吧！",
    "loading_error_other": "加载个人资料失败",
    "user_not_found": "未找到该用户",
    "message_btn": "发消息",
    "basic_info": "基本信息",
    "avatar": "头像图片",
    "select_image": "选择照片",
    "delete_image": "删除照片",
    "avatar_hint": "JPG/PNG — 图片将自动压缩。",
    "avatar_error": "无法读取此照片，请尝试其他照片。",
    "dob": "出生日期",
    "gender": "性别",
    "gender_private": "保密",
    "gender_male": "男",
    "gender_female": "女",
    "gender_other": "其他",
    "city": "城市",
    "city_placeholder": "例如：北京",
    "display_name": "显示名称",
    "empty_name_error": "显示名称不能为空。",
    "lang_selection_error": "请至少选择 1 门母语/精通语言和 1 门学习语言。",
    "timezone_label": "您的时区",
    "slots_title": "空闲时段（最多 2 个）",
    "slots_selected": "{count}/2 已选择",
    "slots_time": "时间",
    "slots_hint": "设置空闲时段有助于语伴更方便地与您预约练习（时区将自动转换）。",
    "matching_criteria": "匹配偏好",
    "preferred_language": "偏好语言",
    "no_preference": "无偏好",
    "desired_level": "期望语伴水平",
    "any_level": "不限",
    "edit_subtitle": "完整的资料有助于获取更多匹配 — 可随时更新。",
    "this_is_you": "这是您的个人资料",
    "your_name": "您的姓名",
    "change_avatar": "更换头像照片",
    "preview": "预览",
    "preview_hint": "这是其他人在探索页面中看到您的样子。",
    "preview_speaks": "教授/母语:",
    "preview_learns": "学习中:",
    "preview_not_added": "未添加",
    "preview_online": "当前在线",
    "preview_like": "赞",
    "shared_interests": "共同兴趣",
    "interests_hint": "选择您喜欢交流的话题。",
    "intent_hint": "有助于我们为您推荐更合适的语伴。",
    "no_posts_other": "尚未发布任何动态。"
  },
  "chat": {
    "say_hi": "发送打招呼开启对话 👋",
    "you": "你: ",
    "photo": "📷 照片",
    "schedule_invite": "📅 练习预约邀请",
    "translate_fail": "翻译失败，请稍后再试",
    "schedule_fail": "发送预约邀请失败",
    "respond_fail": "回应邀请失败",
    "title": "消息",
    "search_placeholder": "搜索对话...",
    "no_match": "未找到相关对话",
    "empty_conversations": "暂无对话",
    "empty_hint": "去探索页面寻找口语练习伙伴吧。",
    "go_discover": "前往探索",
    "select_chat": "选择一个对话",
    "select_chat_hint": "开始与您的语伴练习口语。",
    "user_local_time": "(您的本地时间)",
    "schedule_btn_tooltip": "预约练习时间",
    "trans_modal_tooltip": "翻译面板",
    "view_profile": "查看资料",
    "report": "举报",
    "block": "屏蔽",
    "partner_availability": "{name} 的空闲时段:",
    "overlap_badge": "✓ 存在共同空闲时间！",
    "reconnecting": "正在重新连接...",
    "save_word_popup": "存入词汇本",
    "matched_title": "成功匹配！",
    "matched_desc": "发送问候语开始口语练习吧。",
    "invite_sent": "您发送了一份预约邀请",
    "invite_received": "{name} 邀请您进行练习",
    "local_time_hint": "(基于您电脑的时区)",
    "accept": "接受",
    "decline": "拒绝",
    "cancel": "取消",
    "status_accepted": "✅ 已接受 — 将在开始前 30 分钟提醒",
    "status_expired": "⌛ 已过期 (48 小时内未回应)",
    "status_declined": "❌ 已拒绝",
    "status_cancelled": "🚫 已取消",
    "cancel_reason_label": "原因: {reason}",
    "cancel_modal_title": "取消已预约的练习",
    "cancel_modal_placeholder": "请输入取消原因...",
    "cancel_success_toast": "已成功取消预约练习",
    "status_sending": "发送中...",
    "status_read": "已读",
    "status_sent": "已发送",
    "react_tooltip": "添加回应",
    "emoji_tooltip": "表情符号",
    "send_img_tooltip": "发送照片",
    "input_placeholder": "输入消息...",
    "report_success": "举报已提交，感谢您的反馈！",
    "block_success": "已屏蔽 {name}",
    "word_save_exists": "“{term}” 已存在于您的词汇本中",
    "word_save_success": "✅ 已保存 “{term}” 到词汇本",
    "translating": "翻译中...",
    "hide": "隐藏",
    "translate": "翻译",
    "save_word": "保存单词"
  },
  "forgot": {
    "title": "重置密码",
    "subtitle": "输入您的邮箱地址以接收密码重置链接",
    "success_message": "如果邮箱有效，我们已发送重置链接，请在 30 分钟内查收。",
    "back_to_login": "返回登录",
    "email_placeholder": "您的电子邮箱",
    "sending": "发送中...",
    "submit": "发送重置链接"
  },
  "onboarding": {
    "step_languages": "语言",
    "step_interests": "兴趣",
    "step_complete": "完成",
    "error_lang_selection": "请至少选择 1 门母语/精通语言和 1 门学习语言。",
    "error_bio_empty": "请填写个人简介 (Bio)。",
    "teach_title": "我会说 (可教授)",
    "select_lang": "选择语言",
    "add_btn": "添加",
    "learn_title": "我想学习",
    "loading": "保存中...",
    "continue_btn": "继续",
    "interests_title": "您的兴趣爱好",
    "interests_subtitle": "选择您感兴趣的话题（可选）。",
    "back_btn": "返回",
    "profile_title": "完成您的个人资料",
    "profile_subtitle": "填写一点关于自己的信息有助于更轻松地匹配语伴。",
    "bio_label": "个人简介 (Bio)",
    "bio_placeholder": "例如：我正在学习英语以便出国留学。周末喜欢喝咖啡...",
    "intent_label": "主要学习目标",
    "finish_btn": "完成并探索",
    "level_1": "零基础/初学者",
    level_2: "基础",
    level_3: "中级",
    level_4: "中高级",
    level_5: "精通/母语",
    intent_casual: "日常交流",
    intent_exam: "备考 (IELTS, JLPT...)",
    intent_travel: "旅游出行",
    intent_work: "工作职场"
  },
  "notifications": {
    "title": "通知",
    "empty": "您暂无通知。",
    "mark_all_read": "全部标记为已读",
    "follow_message": "{name} 开始关注了您。",
    "new_post_message": "{name} 发布了新动态。",
    "like_message": "{name} 赞了您。",
    "match_message": "您与 {name} 成功匹配！"
  },
  "topics": {
    "title": "热门话题",
    "select_topics": "选择您感兴趣的话题",
    "travel": "旅游出行",
    "music": "音乐",
    "movies": "电影影视",
    "food": "美食烹饪",
    "sports": "体育运动",
    "tech": "科技数码",
    "books": "阅读书籍",
    "game": "游戏电竞",
    "culture": "文化历史",
    "exams": "语言考试 (IELTS/TOEIC...)"
  },
  "call": {
    "incoming": "来电...",
    "accept": "接听",
    "decline": "拒绝",
    "mute": "静音",
    "unmute": "取消静音",
    "camera_on": "开启摄像头",
    "camera_off": "关闭摄像头",
    "start_tooltip": "语音通话",
    "calling": "正在呼叫...",
    "incoming_title": "{name} 向您发起通话",
    "incoming_audio": "语音通话来电",
    "incoming_video": "视频通话来电",
    "accept_audio_only": "仅语音接听",
    "hang_up": "挂断",
    "switch_camera": "切换前/后摄像头",
    "partner_camera_off": "对方关闭了摄像头",
    "network_unstable": "网络连接不稳定...",
    "rejected": "对方拒绝了通话",
    "no_answer": "无人接听",
    "partner_busy": "{name} 正在通话中",
    "partner_offline": "{name} 当前不在线",
    "failed": "连接中断，通话已结束",
    "ended_max_duration": "通话已达到 30 分钟时长限制",
    "timeout_warning": "通话将在 {minutes} 分钟后自动结束",
    "error_insecure": "由于页面未处于 HTTPS 环境，浏览器阻止了麦克风使用",
    "error_permission": "请在浏览器设置中允许使用麦克风",
    "error_no_device": "未检测到麦克风设备",
    "error_camera_busy": "摄像头正在被其他应用或标签页使用 — 继续进行语音通话",
    "error_camera_permission": "摄像头已被阻止 — 通话继续，但对方无法看到您",
    "error_unknown": "无法发起通话",
    "log_ended": "语音通话 · {duration}",
    "log_ended_video": "视频通话 · {duration}",
    "log_rejected": "已拒绝通话",
    "log_missed_outgoing": "呼出无人接听",
    "log_missed_incoming": "未接来电"
  }
};

fs.writeFileSync(zhPath, JSON.stringify(zhData, null, 2), 'utf8');
console.log('Brand new zh.json created successfully at ' + zhPath);
