const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const dePath = path.join(__dirname, '../../frontend/messages/de.json');

// Delete existing de.json first if exists as requested by user
if (fs.existsSync(dePath)) {
  fs.unlinkSync(dePath);
  console.log('Deleted old de.json');
}

const deData = {
  "metadata": {
    "title": "stududu — Fremdsprachen Sprechen üben",
    "description": "Plattform für Sprachaustausch und 1:1 Sprechtraining"
  },
  "nav": {
    "discover": "Entdecken",
    "messages": "Nachrichten",
    "vocabulary": "Vokabeln",
    "community": "Community",
    "profile": "Profil"
  },
  "menu": {
    "profile": "Profil",
    "settings": "Einstellungen",
    "admin": "Admin-Bereich",
    "logout": "Abmelden"
  },
  "settings": {
    "title": "Einstellungen",
    "language": "Benutzeroberflächen-Sprache",
    "language_hint": "Nur UI-Sprache — von Benutzern erstellte Inhalte bleiben in ihrer Originalsprache.",
    "password": "Passwort ändern",
    "shareActivity": "Aktivitäten teilen",
    "blocked": "Blockierte Benutzer",
    "share_activity_enabled": "Aktivitätenteilen aktiviert",
    "share_activity_disabled": "Aktivitätenteilen deaktiviert",
    "password_mismatch": "Die Passwörter stimmen nicht überein.",
    "password_success": "Passwort erfolgreich aktualisiert",
    "unblock_success": "{name} wurde entsperrt",
    "password_hint": "Mindestens 8 Zeichen, darunter sowohl Buchstaben als auch Zahlen.",
    "curr_password_placeholder": "Aktuelles Passwort",
    "new_password_placeholder": "Neues Passwort",
    "confirm_password_placeholder": "Neues Passwort bestätigen",
    "updating": "Wird aktualisiert...",
    "update_password": "Passwort aktualisieren",
    "share_activity_hint": "Automatischer Beitrag in der Community, wenn du ein Wort hinzufügst oder ein Gesprächsziel erreichst.",
    "enabled": "Aktiviert",
    "disabled": "Deaktiviert",
    "no_blocked": "Du hast niemanden blockiert.",
    "unblock": "Entsperren",
    "logout": "Abmelden"
  },
  "common": {
    "save": "Änderungen speichern",
    "cancel": "Abbrechen",
    "loading": "Laden...",
    "retry": "Erneut versuchen",
    "or": "oder",
    "error_generic": "Etwas ist schiefgelaufen. Bitte versuche es erneut."
  },
  "home": {
    "login": "Anmelden",
    "register": "Registrieren",
    "title_part1": "Übe Fremdsprachen mit echten",
    "title_part2": "Muttersprachlern",
    "description": "Finde deinen perfekten Sprachaustausch-Partner. Du lehrst deine Sprache, sie lehren ihre. Völlig kostenlos und gegenseitig.",
    "get_started": "Jetzt starten"
  },
  "login": {
    "title": "Anmelden",
    "welcome": "Willkommen zurück bei stududu",
    "email": "E-Mail-Adresse",
    "password": "Passwort",
    "remember": "Angemeldet bleiben",
    "forgot": "Passwort vergessen?",
    "submit": "Anmelden",
    "submitting": "Wird angemeldet...",
    "google": "Mit Google fortfahren",
    "google_notice": "Mit Google anmelden: Benutzeroberfläche bereit. Die API-Integration wird eingerichtet, sobald das Backend fertig ist.",
    "no_account": "Noch kein Konto?",
    "register_link": "Jetzt registrieren",
    "hero_title": "Lerne Sprachen mit echten Muttersprachlern.",
    "hero_sub": "Du lehrst deine Sprache, sie lehren ihre. Ein fairer Austausch — ohne Noten, ohne Gebühren.",
    "hero_p1": "Passend nach ergänzenden Sprachen gematcht, nicht nach Punktezahl",
    "hero_p2": "Direkter 1:1 Chat, trainiere deine Reflexe jeden Tag",
    "hero_p3": "Beiträge werden mit Lob gewürdigt, nicht mit Ranglisten",
    "hero_footer": "stududu — Sprachaustausch im Tandem-Stil"
  },
  "register": {
    "title": "Konto erstellen",
    "subtitle": "Starte deine Sprachreise",
    "hero_title": "Übe das Sprechen mit echten Muttersprachlern.",
    "hero_subtitle": "Du lehrst deine Sprache, sie lehren ihre.",
    "display_name": "Anzeigename",
    "first_name": "Vorname",
    "surname": "Nachname",
    "dob": "Geburtsdatum",
    "day": "Tag",
    "month": "Monat",
    "year": "Jahr",
    "gender": "Geschlecht",
    "gender_placeholder": "Wähle dein Geschlecht",
    "gender_female": "Weiblich",
    "gender_male": "Männlich",
    "gender_custom": "Divers / Andere",
    "country": "Land",
    "select_country": "Land auswählen",
    "email": "Handynummer oder E-Mail-Adresse",
    "password": "Passwort",
    "password_hint": "Mindestens 8 Zeichen",
    "password_error": "Passwort muss mindestens 8 Zeichen lang sein.",
    "submit": "Registrieren",
    "submitting": "Konto wird erstellt...",
    "google": "Mit Google registrieren",
    "google_notice": "Mit Google registrieren: Benutzeroberfläche bereit. Die API-Integration wird eingerichtet, sobald das Backend fertig ist.",
    "has_account": "Hast du bereits ein Konto?",
    "login_link": "Anmelden"
  },
  "discover": {
    "hero_label": "Nur für dich",
    "title": "Entdecken",
    "subtitle": "Finde jemanden, um gemeinsam Sprachen zu lernen und zu lehren.",
    "tab_suggest": "Beste Matches",
    "tab_all": "Alle Mitglieder",
    "search_placeholder": "Nach Name, Sprache, Interessen suchen...",
    "filter_title": "Filter",
    "filter_level_label": "Partner-Niveau (Sprache, die gelehrt wird)",
    "filter_level_all": "Alle Niveaus",
    "filter_level_native": "Muttersprache",
    "filter_level_fluent": "Fließend",
    "filter_interests": "Gemeinsame Interessen",
    "filter_online": "Jetzt online",
    "filter_reset": "Filter zurücksetzen",
    "sort_best": "Bester Match",
    "sort_recent": "Zuletzt aktiv",
    "result_count": "passende Partner",
    "load_more": "Mehr laden (noch {remaining})",
    "loading_more": "Wird geladen...",
    "loading_search": "Suche nach den besten Matches...",
    "error_load": "Vorschläge konnten nicht geladen werden",
    "error_load_members": "Mitglieder konnten nicht geladen werden",
    "tip_title": "Matching-Tipp",
    "tip_text": "Profile mit Foto und vollständiger Beschreibung erhalten deutlich mehr Anfragen!",
    "insufficient_pool": "Die Community wächst — noch nicht genügend passende Partner da. Versuche es unter \"Alle Mitglieder\".",
    "empty_no_members": "Noch keine anderen Mitglieder",
    "empty_insufficient": "Nicht genügend passende Partner",
    "empty_no_match": "Noch keine passenden Partner",
    "empty_no_filter": "Keine Treffer für diese Filter",
    "empty_invite": "Lade deine Freunde ein, stududu beizutreten!",
    "empty_suggest_tip": "Wechsele zu 'Alle Mitglieder' oder aktualisiere deine Sprachen und Interessen.",
    "empty_filter_tip": "Lockere deine Filter, um mehr Partner zu sehen.",
    "refresh_list": "Liste aktualisieren",
    "liked_toast": "{name} gefällt dir — schreibe jetzt eine Nachricht!",
    "card_online": "Jetzt online",
    "card_recent": "Zuletzt aktiv",
    "card_speaks": "Spricht:",
    "card_native": "(Muttersprache)",
    "card_fluent": "(Fließend)",
    "card_learns": "Lernt:",
    "card_interests": "Gemeinsame Interessen",
    "card_liked": "Gefällt mir",
    "card_like": "Gefällt mir",
    "card_unlike": "Gefällt mir nicht mehr",
    "card_unliked_toast": "{name} gefällt dir nicht mehr",
    "match_title": "🎉 Es ist ein Match!",
    "match_desc": "Großartig! Du und {name} mögt euch gegenseitig. Startet ein Gespräch und übt gemeinsam.",
    "match_chat_now": "Jetzt schreiben",
    "match_continue": "Weiter entdecken"
  },
  "community": {
    "title": "Community",
    "add_image": "Bild anhängen",
    "subtitle": "Teile deine Gedanken und Erlebnisse aus der Community.",
    "post_placeholder": "Was möchtest du teilen? (Tipps, Meilensteine, Geschichten...)",
    "post_button": "Beitrag schreiben",
    "post_share": "hat geteilt:",
    "post_word": "hat das Wort \"{term}\" ({language}) zur öffentlichen Bibliothek hinzugefügt 🌐",
    "post_word_generic": "hat ein Wort zur öffentlichen Bibliothek hinzugefügt 🌐",
    "post_milestone": "hat gerade {hours} Stunden Gesprächsübung erreicht 🎉",
    "comment_placeholder": "Schreibe einen Kommentar...",
    "reply_placeholder": "Antworte an {name}...",
    "reply": "Antworten",
    "delete": "Löschen",
    "unlike": "Gefällt mir nicht mehr",
    "like": "Gefällt mir",
    "report": "Melden",
    "comment_error": "Kommentar konnte nicht gesendet werden",
    "image_too_large": "Bildgröße darf 2 MB nicht überschreiten",
    "char_count": "{count}/500",
    "edit": "Bearbeiten",
    "delete_post": "Beitrag löschen",
    "confirm_delete": "Möchtest du diesen Beitrag wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
    "confirm_yes": "Löschen",
    "confirm_no": "Abbrechen",
    "editing": "Beitrag bearbeiten",
    "update": "Aktualisieren",
    "cancel_edit": "Abbrechen",
    "empty_feed": "Noch keine Aktivitäten",
    "empty_feed_hint": "Teile etwas mit der Community!",
    "time_just_now": "Gerade eben",
    "time_minutes_ago": "Vor {count} Min.",
    "time_hours_ago": "Vor {count} Std.",
    "report_post_target": "Beitrag von {name}",
    "attach_image": "Bild anhängen",
    "image_size_error": "⚠️ Bildgröße darf 2 MB nicht überschreiten",
    "eyebrow": "STUDUDU COMMUNITY",
    "page_subtitle": "Teile deine Reise, finde Übungspartner und nimm an Events teil.",
    "tab_feed": "Newsfeed",
    "tab_groups": "Sprachgruppen",
    "tab_events": "Events",
    "tag_partner": "Partner suchen",
    "tag_milestone": "Erfolg teilen",
    "tag_question": "Frage stellen",
    "daily_vocab_title": "HEUTIGE NEUE VOKABELN",
    "save_word": "Wort speichern",
    "saved_word": "Gespeichert",
    "next_word": "Nächstes Wort",
    "already_know": "Kenne ich schon",
    "suggested_groups": "Empfohlene Gruppen",
    "join_group": "Beitreten",
    "joined_group": "Beigetreten",
    "members_count": "{count} Mitglieder",
    "groups_coming_soon": "Das Sprachgruppen-Feature wird derzeit entwickelt. Entdecke empfohlene Gruppen in der rechten Spalte!",
    "events_coming_soon": "In den Events veranstalten Admins Prüfungen und Wettbewerbe zum gemeinsamen Üben. Demnächst verfügbar!",
    "groups_title": "Sprachgruppen",
    "group_en_desc": "Tägliche Englisch-Sprechpraxis-Community mit Muttersprachlern.",
    "group_ja_desc": "Gruppe für japanische Kaiwa-Sprechpraxis und Kulturaustausch.",
    "group_ko_desc": "Gruppe für koreanische Sprechpraxis und K-Kultur-Austausch.",
    "group_fr_desc": "Französisch-Austauschgruppe von Grund- bis Fortgeschrittenenniveau.",
    "events_title": "Events & Prüfungswettbewerbe",
    "status_upcoming": "DEMNÄCHST",
    "event1_time": "15:00 Uhr - Dessen Sonntag",
    "event1_title": "🏆 IELTS Speaking Reflex Wettbewerb (OJT Runde 1)",
    "event1_desc": "Admins veranstalten Live-Prüfungsräume zum gegenseitigen Messen der Sprechreflexe.",
    "event1_btn": "Für Prüfung anmelden",
    "event2_time": "20:00 Uhr - Jeden Mittwoch",
    "event2_title": "🌸 N3 Vokabeln & Kaiwa Kanji Challenge",
    "event2_desc": "Schnelles Kanji-Quiz mit 20 Fragen, das Lernende mit Muttersprachlern verbindet.",
    "event2_btn": "Interessiert",
    "event_toast_notice": "ℹ️ Die Event-Registrierungsfunktion wird demnächst verfügbar sein!",
    "prev_word": "Vorheriges Wort",
    "translate_post": "Beitrag übersetzen",
    "see_translation": "Übersetzung anzeigen",
    "translated": "Übersetzt",
    "translation_title": "Automatische Übersetzung",
    "hide_translation": "Übersetzung verbergen"
  },
  "langSwitcher": {
    "vi": "Tiếng Việt",
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "zh": "中文",
    "ja": "日本語",
    "de": "Deutsch"
  },
  "vocabulary": {
    "title": "Vokabeln",
    "tab_mine": "Mein Vokabelheft",
    "tab_library": "Öffentliche Bibliothek",
    "search_mine_placeholder": "Wörter, Notizen suchen...",
    "search_library_placeholder": "Öffentliche Bibliothek durchsuchen...",
    "add_word": "Wort hinzufügen",
    "library_hint": "Wörter, die von ≥3 Mitgliedern gespeichert werden, gelangen automatisch in die öffentliche Bibliothek — sortiert nach Speicheranzahl.",
    "source_chat": "Aus dem Chat",
    "source_manual": "Manuell",
    "in_library": "In öffentlicher Bibliothek",
    "no_definition": "Noch keine Definition oder Notiz vorhanden",
    "deleted_toast": "Wort aus deinem Vokabelheft entfernt",
    "definition_label": "Definition",
    "example_label": "Beispiel",
    "personal_note_label": "Persönliche Notiz",
    "saved_by_count": "{count} Personen haben dieses Wort gespeichert",
    "empty_title": "Vokabelheft ist leer",
    "empty_no_match": "Keine Wörter gefunden",
    "empty_hint": "Markiere Wörter während des Chats oder füge sie manuell hinzu, um deinen Wortschatz zu erweitern.",
    "empty_no_match_hint": "Versuche es mit einem anderen Suchbegriff.",
    "add_first_word": "Füge dein erstes Wort hinzu",
    "contrib_title": "Beitrag für \"{term}\"",
    "contrib_success": "🙌 Vielen Dank für deinen Beitrag!",
    "contrib_btn": "Beitragen",
    "need_definition": "⏳ Benötigt Definition",
    "save_count_label": "{count} Speicherungen",
    "save_success": "✅ \"{term}\" gespeichert",
    "save_exists": "\"{term}\" ist bereits im Vokabelheft — Notiz aktualisiert",
    "modal_title": "Im Vokabelheft speichern",
    "language_label": "Sprache",
    "term_label": "Wort / Ausdruck (max. 100 Zeichen)",
    "term_placeholder": "Wort zum Speichern eingeben...",
    "definition_placeholder": "Erkläre die Bedeutung des Wortes...",
    "example_placeholder": "Gib einen Beispielsatz mit diesem Wort ein...",
    "quiz_hint_prompt": "Wähle die genaueste Übersetzung unten aus:",
    "header_badge": "VOKABEL-QUIZ & ÜBUNG",
    "page_title": "Vokabeln & Quiz",
    "page_subtitle": "Übe mit Multiple-Choice-Quizzes und verwalte dein persönliches Vokabelheft.",
    "total_words": "Wörter insgesamt",
    "mastered": "Gelernt",
    "need_review": "Wiederholung nötig",
    "tab_quiz": "Quiz-Wiederholung",
    "tab_notebook": "Vokabelheft ({count})",
    "btn_review_learning": "Ungelernt wiederholen ({count})",
    "btn_review_all": "Alle wiederholen ({count})",
    "quiz_loading": "Quizdaten werden geladen...",
    "quiz_result_title": "Quiz-Ergebnis",
    "quiz_result_desc": "Du hast die Wiederholungssitzung mit {count} Fragen abgeschlossen.",
    "total_score": "Gesamtpunkte",
    "score_sub": "+10 Punkte / richtige Antwort",
    "correct_answers": "Richtige Antworten",
    "correct_sub": "Zu 'Gelernt' verschoben",
    "accuracy_rate": "Genauigkeit",
    "accuracy": "Genauigkeit",
    "btn_new_quiz": "Neues Quiz starten",
    "btn_view_notebook": "Vokabelheft anzeigen",
    "question_progress": "Frage {current} / {total}",
    "points": "{points} Pkt.",
    "streak": "{streak}er-Serie!",
    "status_mastered_label": "Gelernt",
    "status_learning_label": "Am Lernen",
    "btn_audio_tooltip": "Aussprache anhören",
    "btn_next_question": "Nächste Frage",
    "btn_view_score": "Ergebnisse anzeigen",
    "empty_learning_title": "Du hast alle Wörter zur Wiederholung gemeistert!",
    "empty_learning_desc": "Toll gemacht! Wechsele zu 'Alle wiederholen', um dein Wissen zu festigen.",
    "empty_notebook_title": "Noch keine Vokabeln im Heft!",
    "empty_notebook_desc": "Füge beim Übersetzen oder Chatten neue Wörter zu deinem Vokabelheft hinzu.",
    "btn_review_all_full": "Alle Wörter wiederholen ({count})",
    "notebook_heading": "Persönliches Vokabelheft",
    "notebook_subheading": "Alle gespeicherten Wörter aus Übersetzung, Chat und manuellen Einträgen.",
    "total_count_label": "Gesamt: {count} Wörter",
    "filter_all": "Alle",
    "filter_new": "Neu",
    "filter_learning": "Am Lernen",
    "filter_mastered": "Gelernt",
    "search_placeholder_notebook": "Vokabeln suchen...",
    "source_chat_label": "Chat",
    "source_manual_label": "Vokabelheft",
    "source_community_label": "Community",
    "source_prefix": "Quelle: {source}",
    "btn_delete_tooltip": "Wort löschen",
    "deleted_toast_message": "\"{term}\" aus dem Vokabelheft gelöscht.",
    "no_words_found": "Keine passenden Vokabeln gefunden.",
    "rank_excellent": "Hervorragend! 🌟",
    "rank_good": "Großartig! 👏",
    "rank_fair": "Gut! 👍",
    "rank_needs_work": "Weiter so! 💡",
    "select_correct_def_prompt": "👉 Wähle die richtige Definition unten:",
    "translation_label": "Übersetzen:",
    "definition_heading": "📝 Definition",
    "example_heading": "💡 Beispiel",
    "no_info": "Keine Informationen zu diesem Wort gefunden.",
    "saved_by_users": "🌐 {count} Personen haben dies gespeichert",
    "lookup_error": "Wort konnte derzeit nicht nachgeschlagen werden. Versuche es später erneut.",
    "saving_btn": "Wird gespeichert...",
    "save_to_notebook_btn": "Im Vokabelheft speichern"
  },
  "profile": {
    "title_me": "Mein Profil",
    "edit_profile": "Profil bearbeiten",
    "settings": "Einstellungen",
    "tab_posts": "Beiträge",
    "tab_about": "Über mich",
    "posts_title": "Beiträge",
    "posts_count": "{count} Beiträge",
    "no_posts_me": "Du hast noch nichts gepostet.",
    "create_post_hint": "Teile einen Beitrag mit der Community!",
    "create_post_btn": "Beitrag erstellen",
    "post_placeholder": "Was geht dir durch den Kopf, {name}?",
    "lives_in": "Wohnt in",
    "gender_label": "Geschlecht",
    "timezone_label_short": "Zeitzone",
    "speaks_label": "Spricht",
    "learns_label": "Lernt",
    "level_label": "Niveau",
    "native_label": "Muttersprache",
    "fluent_label": "Fließend",
    "edit_btn": "Bearbeiten",
    "completion": "Profilvollständigkeit",
    "trust_activity": "Vertrauen & Aktivität",
    "languages": "Sprachen",
    "can_teach": "Kann lehren",
    "want_learn": "Möchte lernen",
    "none": "Keine",
    "intro": "Über mich",
    "no_intro_me": "Du hast noch keine Beschreibung verfasst — füge ein paar Zeilen hinzu, um einfacher gematcht zu werden.",
    "no_intro_other": "Mitglied hat noch keine Beschreibung verfasst.",
    "intent": "Lernziel",
    "not_specified": "Nicht angegeben",
    "availability": "Verfügbarkeit & Zeitzone",
    "no_availability": "Verfügbarkeit nicht festgelegt",
    "interests": "Interessen",
    "no_interests": "Keine Interessen ausgewählt",
    "loading_error": "Profil konnte nicht geladen werden",
    "hint_avatar": "Profilbild hinzufügen",
    "hint_bio": "Persönliche Beschreibung verfassen",
    "hint_teach": "Sprache hinzufügen, die du lehren kannst",
    "hint_learn": "Sprache hinzufügen, die du lernen möchtest",
    "hint_interests": "Interessen auswählen",
    "hint_intent": "Lernziel auswählen",
    "report": "Melden",
    "block": "Blockieren",
    "endorse_btn": "Anerkennen",
    "endorse_success_toast": "🏅 Anerkennung übermittelt. Vielen Dank!",
    "no_endorsements": "Noch keine Empfehlungen",
    "chat_hours": "{count} Stunden Praxis",
    "conversations": "{count} Gespräche",
    "endorse_title": "{name} anerkennen",
    "endorse_desc": "Wähle aus, was du nach dem Gespräch mit {name} lobend hervorheben möchtest — ohne Noten, einfach qualitative Wertschätzung.",
    "endorse_already_given": "✓ Bereits anerkannt",
    "sending": "Wird gesendet...",
    "submit_endorse": "Anerkennung absenden",
    "lang_proficiency": "Muttersprachliche Kompetenz",
    "social_knowledge": "Kulturelles/Soziales Wissen",
    "niche_expertise": "Fachwissen",
    "friendliness": "Freundlich",
    "trust_activity_other": "Anerkennung aus der Community",
    "report_success_toast": "Meldung abgesendet. Vielen Dank!",
    "block_success_toast": "{name} blockiert",
    "like_success_toast": "💜 {name} gefällt dir — starte ein Gespräch!",
    "loading_error_other": "Profil konnte nicht geladen werden",
    "user_not_found": "Benutzer nicht gefunden",
    "message_btn": "Nachricht",
    "basic_info": "Grundlegende Informationen",
    "avatar": "Profilbild",
    "select_image": "Foto auswählen",
    "delete_image": "Foto löschen",
    "avatar_hint": "JPG/PNG — Bild wird automatisch komprimiert.",
    "avatar_error": "Dieses Foto kann nicht gelesen werden. Versuche ein anderes.",
    "dob": "Geburtsdatum",
    "gender": "Geschlecht",
    "gender_private": "Keine Angabe",
    "gender_male": "Männlich",
    "gender_female": "Weiblich",
    "gender_other": "Divers",
    "city": "Stadt",
    "city_placeholder": "Z.B. Berlin",
    "display_name": "Anzeigename",
    "empty_name_error": "Anzeigename darf nicht leer sein.",
    "lang_selection_error": "Bitte wähle mindestens 1 Lehrsprache und 1 Lernsprache aus.",
    "timezone_label": "Deine Zeitzone",
    "slots_title": "Verfügbarkeit (max. 2)",
    "slots_selected": "{count}/2 ausgewählt",
    "slots_time": "Zeit",
    "slots_hint": "Verfügbarkeiten helfen Partnern, Termine einfacher anzufragen (Zeitzone wird automatisch umgerechnet).",
    "matching_criteria": "Matching-Kriterien",
    "preferred_language": "Bevorzugte Sprache",
    "no_preference": "Keine Präferenz",
    "desired_level": "Gewünschtes Niveau des Partners",
    "any_level": "Beliebig",
    "edit_subtitle": "Ein vollständiges Profil bringt mehr Matches — du kannst es jederzeit aktualisieren.",
    "this_is_you": "Das ist dein Profil",
    "your_name": "Dein Name",
    "change_avatar": "Profilbild ändern",
    "preview": "Vorschau",
    "preview_hint": "So sehen dich andere im Entdecken-Bereich.",
    "preview_speaks": "Spricht:",
    "preview_learns": "Lernt:",
    "preview_not_added": "Nicht hinzugefügt",
    "preview_online": "Jetzt aktiv",
    "preview_like": "Gefällt mir",
    "shared_interests": "Gemeinsame Interessen",
    "interests_hint": "Wähle Themen, über die du gerne sprichst.",
    "intent_hint": "Hilft uns, dir bessere Partner vorzuschlagen.",
    "no_posts_other": "Noch keine Beiträge geteilt."
  },
  "chat": {
    "say_hi": "Sage Hallo, um das Gespräch zu beginnen 👋",
    "you": "Du: ",
    "photo": "📷 Foto",
    "schedule_invite": "📅 Einladung zu einer Zeit",
    "translate_fail": "Übersetzung fehlgeschlagen, versuche es später erneut",
    "schedule_fail": "Einladung konnte nicht gesendet werden",
    "respond_fail": "Antwort auf Einladung fehlgeschlagen",
    "title": "Nachrichten",
    "search_placeholder": "Gespräche suchen...",
    "no_match": "Keine Gespräche gefunden",
    "empty_conversations": "Noch keine Gespräche",
    "empty_hint": "Gehe zu Entdecken, um Übungspartner zu finden.",
    "go_discover": "Zu Entdecken gehen",
    "select_chat": "Wähle ein Gespräch aus",
    "select_chat_hint": "Beginne mit deinem Partner zu üben.",
    "user_local_time": "(deine Ortszeit)",
    "schedule_btn_tooltip": "Chat planen",
    "trans_modal_tooltip": "Übersetzungstafel",
    "view_profile": "Profil anzeigen",
    "report": "Melden",
    "block": "Blockieren",
    "partner_availability": "Freie Zeiten von {name}:",
    "overlap_badge": "✓ Gemeinsame freie Zeiten!",
    "reconnecting": "Verbindung wird wiederhergestellt...",
    "save_word_popup": "Wort speichern",
    "matched_title": "Ihr seid ein Match!",
    "matched_desc": "Sende eine Begrüßung, um mit dem Üben zu beginnen.",
    "invite_sent": "Du hast eine Einladung gesendet",
    "invite_received": "{name} hat dich zum Chat eingeladen",
    "local_time_hint": "(basierend auf der Zeitzone deines Computers)",
    "accept": "Annehmen",
    "decline": "Ablehnen",
    "cancel": "Abbrechen",
    "status_accepted": "✅ Angenommen — Erinnerung erfolgt 30 Min. vorher",
    "status_expired": "⌛ Abgelaufen (keine Antwort innerhalb von 48 Std.)",
    "status_declined": "❌ Abgelehnt",
    "status_cancelled": "🚫 Storniert",
    "cancel_reason_label": "Grund: {reason}",
    "cancel_modal_title": "Geplanten Chat stornieren",
    "cancel_modal_placeholder": "Gib einen Grund für die Stornierung ein...",
    "cancel_success_toast": "Geplanter Chat erfolgreich storniert",
    "status_sending": "Wird gesendet...",
    "status_read": "Gelesen",
    "status_sent": "Gesendet",
    "react_tooltip": "Reaktion hinzufügen",
    "emoji_tooltip": "Emoji",
    "send_img_tooltip": "Foto senden",
    "input_placeholder": "Schreibe eine Nachricht...",
    "report_success": "Meldung abgesendet. Vielen Dank!",
    "block_success": "{name} blockiert",
    "word_save_exists": "\"{term}\" ist bereits in deinem Vokabelheft",
    "word_save_success": "✅ \"{term}\" im Vokabelheft gespeichert",
    "translating": "Wird übersetzt...",
    "hide": "Verbergen",
    "translate": "Übersetzen",
    "save_word": "Wort speichern"
  },
  "forgot": {
    "title": "Passwort vergessen",
    "subtitle": "Gib deine E-Mail-Adresse ein, um einen Link zum Zurücksetzen des Passworts zu erhalten",
    "success_message": "Wenn die E-Mail-Adresse gültig ist, haben wir einen Link zum Zurücksetzen gesendet. Der Link läuft in 30 Minuten ab.",
    "back_to_login": "Zurück zur Anmeldung",
    "email_placeholder": "Deine E-Mail-Adresse",
    "sending": "Wird gesendet...",
    "submit": "Reset-Link senden"
  },
  "onboarding": {
    "step_languages": "Sprachen",
    "step_interests": "Interessen",
    "step_complete": "Abschluss",
    "error_lang_selection": "Bitte wähle mindestens 1 Lehrsprache und 1 Lernsprache aus.",
    "error_bio_empty": "Bitte verfasse eine persönliche Beschreibung.",
    "teach_title": "Ich spreche (kann lehren)",
    "select_lang": "Sprache auswählen",
    "add_btn": "Hinzufügen",
    "learn_title": "Ich möchte lernen",
    "loading": "Wird gespeichert...",
    "continue_btn": "Weiter",
    "interests_title": "Deine Interessen",
    "interests_subtitle": "Wähle Themen, die dich interessieren (optional).",
    "back_btn": "Zurück",
    "profile_title": "Vervollständige dein Profil",
    "profile_subtitle": "Ein paar Worte über dich helfen dir, leicht passende Partner zu finden.",
    "bio_label": "Persönliche Beschreibung (Bio)",
    "bio_placeholder": "Z.B. Ich lerne Englisch für mein Auslandsstudium. Am Wochenende liebe ich Kaffee...",
    "intent_label": "Hauptsächliches Lernziel",
    "finish_btn": "Fertigstellen & Entdecken",
    "level_1": "Anfänger (A1)",
    "level_2": "Grundkenntnisse (A2)",
    "level_3": "Mittelstufe (B1)",
    "level_4": "Gute Mittelstufe (B2)",
    "level_5": "Fließend (C1/C2)",
    "intent_casual": "Lockerer Austausch / Konversation",
    "intent_exam": "Prüfungsvorbereitung (IELTS, JLPT...)",
    "intent_travel": "Reisen",
    "intent_work": "Beruf & Arbeit"
  },
  "notifications": {
    "title": "Benachrichtigungen",
    "empty": "Du hast keine Benachrichtigungen.",
    "mark_all_read": "Alle als gelesen markieren",
    "follow_message": "{name} folgt dir jetzt.",
    "new_post_message": "{name} hat einen neuen Beitrag veröffentlicht.",
    "like_message": "{name} hat dir ein Gefällt mir gegeben.",
    "match_message": "Du und {name} seid ein Match!"
  },
  "topics": {
    "travel": "Reisen",
    "music": "Musik",
    "movies": "Filme",
    "food": "Essen & Kulinarik",
    "sports": "Sport",
    "tech": "Technologie",
    "books": "Bücher & Lesen",
    "game": "Gaming",
    "culture": "Kultur & Geschichte",
    "exams": "Prüfungen (IELTS/TOEIC...)"
  },
  "call": {
    "start_tooltip": "Sprachanruf",
    "start_video_tooltip": "Videoanruf",
    "calling": "Anrufen…",
    "incoming_title": "{name} ruft an",
    "incoming_audio": "Eingehender Sprachanruf",
    "incoming_video": "Eingehender Videoanruf",
    "accept": "Annehmen",
    "accept_audio_only": "Ohne Kamera antworten",
    "decline": "Ablehnen",
    "hang_up": "Auflegen",
    "mute": "Stummschalten",
    "unmute": "Stummschaltung aufheben",
    "camera_off": "Kamera ausschalten",
    "camera_on": "Kamera einschalten",
    "switch_camera": "Kamera wechseln",
    "partner_camera_off": "Dein Partner hat die Kamera ausgeschaltet",
    "network_unstable": "Schwache Verbindung…",
    "rejected": "Dein Partner hat den Anruf abgelehnt",
    "no_answer": "Keine Antwort",
    "partner_busy": "{name} ist in einem anderen Gespräch",
    "partner_offline": "{name} ist nicht online",
    "failed": "Verbindung getrennt, Anruf beendet",
    "ended_max_duration": "Der Anruf hat das Limit von 30 Minuten erreicht",
    "timeout_warning": "Der Anruf wird in {minutes} Minuten automatisch beendet",
    "error_insecure": "Dein Browser hat das Mikrofon blockiert, da die Seite nicht über HTTPS läuft",
    "error_permission": "Erlaube den Mikrofonzugriff in deinen Browsereinstellungen",
    "error_no_device": "Kein Mikrofon gefunden",
    "error_camera_busy": "Kamera wird von einer anderen App genutzt — Anruf wird mit Audio fortgesetzt",
    "error_camera_permission": "Kamera ist blockiert — Anruf läuft weiter, dein Partner sieht dich nur nicht",
    "error_unknown": "Anruf konnte nicht gestartet werden",
    "log_ended": "Sprachanruf · {duration}",
    "log_ended_video": "Videoanruf · {duration}",
    "log_rejected": "Anruf abgelehnt",
    "log_missed_outgoing": "Du hast angerufen, aber niemand hat geantwortet",
    "log_missed_incoming": "Entgangener Anruf"
  }
};

// Check key coverage against en.json
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

let missingKeys = 0;
for (const sec in enData) {
  if (!deData[sec]) {
    console.error(`Missing section: ${sec}`);
    missingKeys++;
    continue;
  }
  for (const k in enData[sec]) {
    if (deData[sec][k] === undefined) {
      console.error(`Missing key: ${sec}.${k}`);
      missingKeys++;
    }
  }
}

if (missingKeys > 0) {
  console.error(`Validation failed: ${missingKeys} missing keys.`);
  process.exit(1);
}

fs.writeFileSync(dePath, JSON.stringify(deData, null, 2), 'utf8');
console.log('Successfully written de.json with 100% key match!');
