const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const jaPath = path.join(__dirname, '../../frontend/messages/ja.json');

// Delete existing ja.json first as requested by user
if (fs.existsSync(jaPath)) {
  fs.unlinkSync(jaPath);
  console.log('Deleted old ja.json');
}

const jaData = {
  "metadata": {
    "title": "stududu — 外国語スピーキング練習",
    "description": "言語交換＆1対1オンライン会話練習プラットフォーム"
  },
  "nav": {
    "discover": "発見",
    "messages": "メッセージ",
    "vocabulary": "単語帳",
    "community": "コミュニティ",
    "profile": "プロフィール"
  },
  "menu": {
    "profile": "プロフィール",
    "settings": "設定",
    "admin": "管理者パネル",
    "logout": "ログアウト"
  },
  "settings": {
    "title": "設定",
    "language": "表示言語",
    "language_hint": "UIの表示言語のみを変更します。ユーザーが投稿したコンテンツは元の言語のまま維持されます。",
    "password": "パスワード変更",
    "shareActivity": "アクティビティを共有",
    "blocked": "ブロック中のユーザー",
    "share_activity_enabled": "アクティビティ共有が有効です",
    "share_activity_disabled": "アクティビティ共有が無効です",
    "password_mismatch": "パスワードが一致しません。",
    "password_success": "パスワードを更新しました",
    "unblock_success": "{name} のブロックを解除しました",
    "password_hint": "英数字を含む8文字以上で入力してください。",
    "curr_password_placeholder": "現在のパスワード",
    "new_password_placeholder": "新しいパスワード",
    "confirm_password_placeholder": "新しいパスワード（確認）",
    "updating": "更新中...",
    "update_password": "パスワードを更新",
    "share_activity_hint": "新しい単語を保存した際や会話目標を達成した際に、自動でコミュニティに投稿します。",
    "enabled": "有効",
    "disabled": "無効",
    "no_blocked": "ブロック中のユーザーはいません。",
    "unblock": "ブロック解除",
    "logout": "ログアウト"
  },
  "common": {
    "save": "変更を保存",
    "cancel": "キャンセル",
    "loading": "読み込み中...",
    "retry": "再試行",
    "or": "または",
    "error_generic": "エラーが発生しました。もう一度お試しください。"
  },
  "home": {
    "login": "ログイン",
    "register": "会員登録",
    "title_part1": "ネイティブスピーカーと実践する",
    "title_part2": "外国語スピーキング",
    "description": "あなたにぴったりの言語交換パートナーを見つけましょう。互いに言語を教え合う、完全無料の相互学習プラットフォームです。",
    "get_started": "今すぐ始める"
  },
  "login": {
    "title": "ログイン",
    "welcome": "stududuへおかえりなさい",
    "email": "メールアドレス",
    "password": "パスワード",
    "remember": "ログイン状態を保持",
    "forgot": "パスワードをお忘れですか？",
    "submit": "ログイン",
    "submitting": "ログイン中...",
    "google": "Googleでログイン",
    "google_notice": "Googleでログイン: UI準備完了。バックエンド完了後にAPIが接続されます。",
    "no_account": "アカウントをお持ちでないですか？",
    "register_link": "今すぐ新規登録",
    "hero_title": "本物のネイティブスピーカーと言語を学ぼう。",
    "hero_sub": "あなたが自身の言語を教え、相手から学ぶ。スコアも料金もないフェアな言語交換。",
    "hero_p1": "スコアではなく相性の良い言語でマッチング",
    "hero_p2": "1対1のダイレクトチャットで毎日会話力を磨く",
    "hero_p3": "順位付けではなく賞賛と感謝で繋がるコミュニティ",
    "hero_footer": "stududu — Tandemスタイルの言語交換"
  },
  "register": {
    "title": "アカウント作成",
    "subtitle": "語学学習の旅を始めましょう",
    "hero_title": "ネイティブスピーカーとスピーキングを練習しよう。",
    "hero_subtitle": "あなたが言語を教え、相手から学ぶ。",
    "display_name": "表示名",
    "first_name": "名",
    "surname": "姓",
    "dob": "生年月日",
    "day": "日",
    "month": "月",
    "year": "年",
    "gender": "性別",
    "gender_placeholder": "性別を選択",
    "gender_female": "女性",
    "gender_male": "男性",
    "gender_custom": "その他",
    "country": "国・地域",
    "select_country": "国を選択",
    "email": "電話番号またはメールアドレス",
    "password": "パスワード",
    "password_hint": "8文字以上",
    "password_error": "パスワードは8文字以上で入力してください。",
    "submit": "新規登録",
    "submitting": "アカウント作成中...",
    "google": "Googleで登録",
    "google_notice": "Googleで登録: UI準備完了。バックエンド完了後にAPIが接続されます。",
    "has_account": "すでにアカウントをお持ちですか？",
    "login_link": "ログイン"
  },
  "discover": {
    "hero_label": "あなたへのおすすめ",
    "title": "発見",
    "subtitle": "一緒に学び教え合える言語交換パートナーを見つけましょう。",
    "tab_suggest": "おすすめのマッチ",
    "tab_all": "すべてのメンバー",
    "search_placeholder": "名前、言語、趣味・関心で検索...",
    "filter_title": "フィルター",
    "filter_level_label": "パートナーのレベル (相手が教える言語)",
    "filter_level_all": "すべてのレベル",
    "filter_level_native": "ネイティブ",
    "filter_level_fluent": "流暢",
    "filter_interests": "共通の趣味・関心",
    "filter_online": "オンライン中",
    "filter_reset": "フィルターをリセット",
    "sort_best": "ベストマッチ",
    "sort_recent": "最近のアクティビティ",
    "result_count": "件のパートナーが見つかりました",
    "load_more": "さらに読み込む (残り {remaining} 件)",
    "loading_more": "読み込み中...",
    "loading_search": "最適なパートナーを探しています...",
    "error_load": "おすすめの読み込みに失敗しました",
    "error_load_members": "メンバーの読み込みに失敗しました",
    "tip_title": "マッチングのコツ",
    "tip_text": "プロフィール写真と自己紹介を設定すると、マッチング率が大幅にアップします！",
    "insufficient_pool": "まだおすすめのパートナーが十分にいません。「すべてのメンバー」をチェックしてみてください。",
    "empty_no_members": "メンバーがまだいません",
    "empty_insufficient": "十分なマッチングパートナーが見つかりません",
    "empty_no_match": "まだ一致するパートナーがいません",
    "empty_no_filter": "条件に一致するパートナーが見つかりません",
    "empty_invite": "友達をstududuに招待しましょう！",
    "empty_suggest_tip": "「すべてのメンバー」に切り替えるか、学習言語や趣味を更新してみてください。",
    "empty_filter_tip": "フィルター条件をゆるめて再度検索してみてください。",
    "refresh_list": "リストを更新",
    "liked_toast": "{name} に「いいね！」しました — メッセージを送ってみましょう！",
    "card_online": "オンライン中",
    "card_recent": "最近アクティブ",
    "card_speaks": "話せる言語:",
    "card_native": "(母国語)",
    "card_fluent": "(流暢)",
    "card_learns": "学習中の言語:",
    "card_interests": "共通の趣味",
    "card_liked": "いいね済み",
    "card_like": "いいね",
    "card_unlike": "いいね解除",
    "card_unliked_toast": "{name} の「いいね！」を解除しました",
    "match_title": "🎉 マッチング成立！",
    "match_desc": "素晴らしい！あなたと {name} はお互いに「いいね！」しました。チャットを始めて一緒に練習しましょう。",
    "match_chat_now": "今すぐメッセージを送る",
    "match_continue": "探索を続ける"
  },
  "community": {
    "title": "コミュニティ",
    "add_image": "画像を添付",
    "subtitle": "あなたの出来事や学習の記録をコミュニティに共有しましょう。",
    "post_placeholder": "何を共有しますか？ (コツ、目標達成、ストーリーなど...)",
    "post_button": "投稿する",
    "post_share": "共有しました:",
    "post_word": "単語 \"{term}\" ({language}) をパブリックライブラリに投稿しました 🌐",
    "post_word_generic": "単語をパブリックライブラリに投稿しました 🌐",
    "post_milestone": "会話練習の合計時間が {hours} 時間に達しました 🎉",
    "comment_placeholder": "コメントを入力...",
    "reply_placeholder": "{name} に返信...",
    "reply": "返信",
    "delete": "削除",
    "unlike": "いいね解除",
    "like": "いいね",
    "report": "通報",
    "comment_error": "コメントの送信に失敗しました",
    "image_too_large": "画像サイズは2MB以下にしてください",
    "char_count": "{count}/500",
    "edit": "編集",
    "delete_post": "投稿を削除",
    "confirm_delete": "本当にこの投稿を削除しますか？この操作は取り消せません。",
    "confirm_yes": "削除",
    "confirm_no": "キャンセル",
    "editing": "投稿を編集",
    "update": "更新",
    "cancel_edit": "キャンセル",
    "empty_feed": "まだアクティビティがありません",
    "empty_feed_hint": "最初の投稿をコミュニティに共有しましょう！",
    "time_just_now": "たった今",
    "time_minutes_ago": "{count}分前",
    "time_hours_ago": "{count}時間前",
    "report_post_target": "{name} の投稿",
    "attach_image": "画像を添付",
    "image_size_error": "⚠️ 画像サイズは2MB以下である必要があります",
    "eyebrow": "STUDUDU コミュニティ",
    "page_subtitle": "学習の旅を共有し、練習パートナーを見つけ、イベントに参加しましょう。",
    "tab_feed": "ニュースフィード",
    "tab_groups": "言語グループ",
    "tab_events": "イベント",
    "tag_partner": "パートナー募集",
    "tag_milestone": "実績報告",
    "tag_question": "質問・相談",
    "daily_vocab_title": "今日の新着単語",
    "save_word": "単語を保存",
    "saved_word": "保存済み",
    "next_word": "次の単語",
    "already_know": "知っている",
    "suggested_groups": "おすすめグループ",
    "join_group": "参加",
    "joined_group": "参加中",
    "members_count": "{count} メンバー",
    "groups_coming_soon": "言語グループ機能は現在開発中です。右サイドバーのおすすめグループをご覧ください！",
    "events_coming_soon": "イベントでは管理者が模擬試験やコンテストを開催し、みんなで練習できます。公開をお楽しみに！",
    "groups_title": "言語グループ",
    "group_en_desc": "ネイティブと毎日英語スピーキングを練習するコミュニティ。",
    "group_ja_desc": "日本語の会話練習と文化交流を行うグループ。",
    "group_ko_desc": "韓国語の会話練習とK-Culture交流を行うグループ。",
    "group_fr_desc": "初級から上級まで対応するフランス語会話交流グループ。",
    "events_title": "イベント＆スピーキングコンテスト",
    "status_upcoming": "開催予定",
    "event1_time": "15:00 - 今週日曜日",
    "event1_title": "🏆 IELTS スピーキング即答力コンテスト (OJT ラウンド1)",
    "event1_desc": "管理者がリアルタイム試験ルームを開設し、即答スコアを競い合います。",
    "event1_btn": "試験にエントリー",
    "event2_time": "20:00 - 毎週水曜日",
    "event2_title": "🌸 N3 語彙＆会話漢字チャレンジ",
    "event2_desc": "漢字20問のスピードクイズでネイティブスピーカーとペアを組みます。",
    "event2_btn": "興味あり",
    "event_toast_notice": "ℹ️ イベント登録機能は間もなく公開されます！",
    "prev_word": "前の単語",
    "translate_post": "投稿を翻訳",
    "see_translation": "翻訳を見る",
    "translated": "翻訳済み",
    "translation_title": "自動翻訳",
    "hide_translation": "翻訳を非表示"
  },
  "langSwitcher": {
    "vi": "Tiếng Việt",
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "zh": "中文",
    "ja": "日本語"
  },
  "vocabulary": {
    "title": "単語帳",
    "tab_mine": "私の単語帳",
    "tab_library": "パブリックライブラリ",
    "search_mine_placeholder": "単語やメモを検索...",
    "search_library_placeholder": "パブリックライブラリを検索...",
    "add_word": "単語を追加",
    "library_hint": "3人以上のメンバーが保存した単語は自動的にパブリックライブラリに追加されます（保存数順）。",
    "source_chat": "チャットから",
    "source_manual": "手動入力",
    "in_library": "パブリックライブラリ内",
    "no_definition": "定義やメモはまだありません",
    "deleted_toast": "単語帳から削除しました",
    "definition_label": "定義",
    "example_label": "例文",
    "personal_note_label": "個人メモ",
    "saved_by_count": "{count} 人がこの単語を保存しました",
    "empty_title": "単語帳が空です",
    "empty_no_match": "該当する単語は見つかりませんでした",
    "empty_hint": "チャット中に単語をハイライト表示するか、手動で単語を追加して語彙力を高めましょう。",
    "empty_no_match_hint": "別のキーワードで検索してみてください。",
    "add_first_word": "最初の単語を追加",
    "contrib_title": "\"{term}\" の定義を投稿",
    "contrib_success": "🙌 ご協力ありがとうございます！",
    "contrib_btn": "投稿する",
    "need_definition": "⏳ 定義が必要",
    "save_count_label": "{count} 件の保存",
    "save_success": "✅ \"{term}\" を保存しました",
    "save_exists": "\"{term}\" はすでに単語帳にあります — メモを更新しました",
    "modal_title": "単語帳に保存",
    "language_label": "言語",
    "term_label": "単語 / フレーズ (最大100文字)",
    "term_placeholder": "保存する単語を入力...",
    "definition_placeholder": "単語の意味を説明...",
    "example_placeholder": "この単語を使った例文を入力...",
    "quiz_hint_prompt": "以下から最も正確な訳を選択してください:",
    "header_badge": "語彙クイズ＆復習",
    "page_title": "語彙＆クイズ",
    "page_subtitle": "選択式クイズで復習し、個人の単語帳を管理しましょう。",
    "total_words": "総単語数",
    "mastered": "習得済み",
    "need_review": "要復習",
    "tab_quiz": "クイズ復習",
    "tab_notebook": "単語帳 ({count})",
    "btn_review_learning": "未習得を復習 ({count})",
    "btn_review_all": "すべて復習 ({count})",
    "quiz_loading": "クイズデータを読み込み中...",
    "quiz_result_title": "クイズ結果",
    "quiz_result_desc": "{count} 問の復習セッションを完了しました。",
    "total_score": "獲得スコア",
    "score_sub": "+10点 / 正解",
    "correct_answers": "正解数",
    "correct_sub": "習得済みに移動",
    "accuracy_rate": "正解率",
    "accuracy": "正解率",
    "btn_new_quiz": "新しいクイズを開始",
    "btn_view_notebook": "単語帳を見る",
    "question_progress": "問題 {current} / {total}",
    "points": "{points} pt",
    "streak": "{streak} 連続正解！",
    "status_mastered_label": "習得済み",
    "status_learning_label": "学習中",
    "btn_audio_tooltip": "発音を聞く",
    "btn_next_question": "次の問題",
    "btn_view_score": "結果を見る",
    "empty_learning_title": "復習対象の単語をすべてクリアしました！",
    "empty_learning_desc": "素晴らしい！「すべて復習」に切り替えて知識を定着させましょう。",
    "empty_notebook_title": "単語帳に単語が登録されていません！",
    "empty_notebook_desc": "翻訳時やチャット中に新しい単語を追加してみましょう。",
    "btn_review_all_full": "すべての単語を復習 ({count})",
    "notebook_heading": "個人の単語帳",
    "notebook_subheading": "翻訳、チャット、手動登録で保存されたすべての単語。",
    "total_count_label": "合計: {count} 単語",
    "filter_all": "すべて",
    "filter_new": "新規",
    "filter_learning": "学習中",
    "filter_mastered": "習得済み",
    "search_placeholder_notebook": "単語を検索...",
    "source_chat_label": "チャット",
    "source_manual_label": "単語帳",
    "source_community_label": "コミュニティ",
    "source_prefix": "ソース: {source}",
    "btn_delete_tooltip": "単語を削除",
    "deleted_toast_message": "単語帳から \"{term}\" を削除しました。",
    "no_words_found": "一致する単語が見つかりません。",
    "rank_excellent": "素晴らしい！ 🌟",
    "rank_good": "大変よくできました！ 👏",
    "rank_fair": "グッド！ 👍",
    "rank_needs_work": "その調子で頑張りましょう！ 💡",
    "select_correct_def_prompt": "👉 正しい意味を選択してください:",
    "translation_label": "翻訳:",
    "definition_heading": "📝 定義",
    "example_heading": "💡 例文",
    "no_info": "この単語の情報はありません。",
    "saved_by_users": "🌐 {count} 人が保存",
    "lookup_error": "現在単語を検索できません。後ほど再試行してください。",
    "saving_btn": "保存中...",
    "save_to_notebook_btn": "単語帳に保存"
  },
  "profile": {
    "title_me": "マイプロフィール",
    "edit_profile": "プロフィールを編集",
    "settings": "設定",
    "tab_posts": "投稿",
    "tab_about": "自己紹介",
    "posts_title": "投稿",
    "posts_count": "{count} 件の投稿",
    "no_posts_me": "まだ何も投稿していません。",
    "create_post_hint": "コミュニティに投稿してみましょう！",
    "create_post_btn": "投稿を作成",
    "post_placeholder": "{name} さん、今の気持ちを共有しましょう。",
    "lives_in": "居住地",
    "gender_label": "性別",
    "timezone_label_short": "タイムゾーン",
    "speaks_label": "話せる言語",
    "learns_label": "学習中の言語",
    "level_label": "レベル",
    "native_label": "母国語",
    "fluent_label": "流暢",
    "edit_btn": "編集",
    "completion": "プロフィール完成度",
    "trust_activity": "信頼度＆アクティビティ",
    "languages": "言語",
    "can_teach": "教えられる言語",
    "want_learn": "学びたい言語",
    "none": "なし",
    "intro": "自己紹介",
    "no_intro_me": "まだ自己紹介が記入されていません。数行記入してマッチング率をあげましょう。",
    "no_intro_other": "自己紹介がまだ記入されていません。",
    "intent": "学習目的",
    "not_specified": "未設定",
    "availability": "活動時間・タイムゾーン",
    "no_availability": "活動時間が設定されていません",
    "interests": "趣味・関心",
    "no_interests": "趣味が選択されていません",
    "loading_error": "プロフィールの読み込みに失敗しました",
    "hint_avatar": "プロフィール写真を追加",
    "hint_bio": "自己紹介を記入",
    "hint_teach": "教えられる言語を追加",
    "hint_learn": "学びたい言語を追加",
    "hint_interests": "趣味・関心を選択",
    "hint_intent": "学習目的を選択",
    "report": "通報",
    "block": "ブロック",
    "endorse_btn": "評価・称賛する",
    "endorse_success_toast": "🏅 評価を送信しました。ありがとうございます！",
    "no_endorsements": "まだ評価はありません",
    "chat_hours": "{count} 時間の会話練習",
    "conversations": "{count} 件の会話",
    "endorse_title": "{name} を称賛する",
    "endorse_desc": "{name} と話した感想を選択してください（数値の評価ではなく感謝と賞賛です）。",
    "endorse_already_given": "✓ 評価済み",
    "sending": "送信中...",
    "submit_endorse": "評価を送信",
    "lang_proficiency": "ネイティブレベルの語学力",
    "social_knowledge": "文化・社会への深い理解",
    "niche_expertise": "専門知識",
    "friendliness": "親切・話しやすい",
    "trust_activity_other": "コミュニティからの評価",
    "report_success_toast": "通報を送信しました。ありがとうございます！",
    "block_success_toast": "{name} をブロックしました",
    "like_success_toast": "💜 {name} に「いいね！」しました — 会話を始めましょう！",
    "loading_error_other": "プロフィールの読み込みに失敗しました",
    "user_not_found": "ユーザーが見つかりません",
    "message_btn": "メッセージ",
    "basic_info": "基本情報",
    "avatar": "アバター画像",
    "select_image": "写真を選択",
    "delete_image": "写真を削除",
    "avatar_hint": "JPG/PNG — 画像は自動的に圧縮されます。",
    "avatar_error": "この写真を読み込めません。別の写真を試してください。",
    "dob": "生年月日",
    "gender": "性別",
    "gender_private": "非公開",
    "gender_male": "男性",
    "gender_female": "女性",
    "gender_other": "その他",
    "city": "都市",
    "city_placeholder": "例：東京",
    "display_name": "表示名",
    "empty_name_error": "表示名を入力してください。",
    "lang_selection_error": "教えられる言語と学びたい言語をそれぞれ少なくとも1つ選択してください。",
    "timezone_label": "タイムゾーン",
    "slots_title": "都合の良い時間帯 (最大2つ)",
    "slots_selected": "{count}/2 選択中",
    "slots_time": "時間",
    "slots_hint": "都合の良い時間帯を設定すると、会話のスケジュール予約がスムーズになります（自動タイムゾーン変換）。",
    "matching_criteria": "マッチング希望条件",
    "preferred_language": "希望する言語",
    "no_preference": "指定なし",
    "desired_level": "相手に求めるレベル",
    "any_level": "不問",
    "edit_subtitle": "充実したプロフィールはマッチング率を高めます — いつでも更新可能です。",
    "this_is_you": "これはあなたのプロフィールです",
    "your_name": "あなたの名前",
    "change_avatar": "写真を変更",
    "preview": "プレビュー",
    "preview_hint": "「発見」タブで他のユーザーからこのように見えます。",
    "preview_speaks": "話せる言語:",
    "preview_learns": "学習中の言語:",
    "preview_not_added": "未設定",
    "preview_online": "オンライン中",
    "preview_like": "いいね",
    "shared_interests": "共通の趣味",
    "interests_hint": "話したいトピックを選択してください。",
    "intent_hint": "より良いパートナーをおすすめするために役立ちます。",
    "no_posts_other": "まだ投稿がありません。"
  },
  "chat": {
    "say_hi": "挨拶を送って会話を始めましょう 👋",
    "you": "あなた: ",
    "photo": "📷 写真",
    "schedule_invite": "📅 チャットのスケジュール招待",
    "translate_fail": "翻訳に失敗しました。後ほど再試行してください",
    "schedule_fail": "招待の送信に失敗しました",
    "respond_fail": "招待への返信に失敗しました",
    "title": "メッセージ",
    "search_placeholder": "会話を検索...",
    "no_match": "会話が見つかりません",
    "empty_conversations": "まだメッセージがありません",
    "empty_hint": "「発見」で練習パートナーを探してみましょう。",
    "go_discover": "発見へ行く",
    "select_chat": "会話を選択",
    "select_chat_hint": "パートナーと練習を始めましょう。",
    "user_local_time": "(あなたの現地時間)",
    "schedule_btn_tooltip": "チャットを予約",
    "trans_modal_tooltip": "翻訳ボード",
    "view_profile": "プロフィールを見る",
    "report": "通報",
    "block": "ブロック",
    "partner_availability": "{name} の空き時間:",
    "overlap_badge": "✓ 共通の空き時間あり！",
    "reconnecting": "再接続中...",
    "save_word_popup": "単語を保存",
    "matched_title": "マッチングしました！",
    "matched_desc": "挨拶を送って練習を始めましょう。",
    "invite_sent": "招待を送信しました",
    "invite_received": "{name} からチャット招待が届きました",
    "local_time_hint": "(お使いのコンピューターのタイムゾーンに基づく)",
    "accept": "承諾",
    "decline": "辞退",
    "cancel": "キャンセル",
    "status_accepted": "✅ 承諾済み — 開始30分前にリマインドします",
    "status_expired": "⌛ 期限切れ (48時間以内に返信なし)",
    "status_declined": "❌ 辞退済み",
    "status_cancelled": "🚫 キャンセル済み",
    "cancel_reason_label": "理由: {reason}",
    "cancel_modal_title": "予約チャットのキャンセル",
    "cancel_modal_placeholder": "キャンセルの理由を入力してください...",
    "cancel_success_toast": "予約チャットを正常にキャンセルしました",
    "status_sending": "送信中...",
    "status_read": "既読",
    "status_sent": "送信済み",
    "react_tooltip": "リアクションを追加",
    "emoji_tooltip": "絵文字",
    "send_img_tooltip": "写真を送信",
    "input_placeholder": "メッセージを入力...",
    "report_success": "通報を送信しました。ありがとうございます！",
    "block_success": "{name} をブロックしました",
    "word_save_exists": "\"{term}\" はすでに単語帳にあります",
    "word_save_success": "✅ \"{term}\" を単語帳に保存しました",
    "translating": "翻訳中...",
    "hide": "非表示",
    "translate": "翻訳",
    "save_word": "単語を保存"
  },
  "forgot": {
    "title": "パスワードをお忘れの方",
    "subtitle": "登録したメールアドレスを入力してリセットリンクを受け取ってください",
    "success_message": "メールアドレスが有効な場合、リセットリンクを送信しました。リンクの有効期限は30分です。",
    "back_to_login": "ログイン画面に戻る",
    "email_placeholder": "メールアドレス",
    "sending": "送信中...",
    "submit": "リセットリンクを送信"
  },
  "onboarding": {
    "step_languages": "言語",
    "step_interests": "趣味・関心",
    "step_complete": "完了",
    "error_lang_selection": "教えられる言語と学びたい言語をそれぞれ少なくとも1つ選択してください。",
    "error_bio_empty": "自己紹介を入力してください。",
    "teach_title": "話せる言語 (教えられる言語)",
    "select_lang": "言語を選択",
    "add_btn": "追加",
    "learn_title": "学びたい言語",
    "loading": "保存中...",
    "continue_btn": "次へ進む",
    "interests_title": "趣味・関心",
    "interests_subtitle": "興味のあるトピックを選択してください (任意)。",
    "back_btn": "戻る",
    "profile_title": "プロフィールを完成させましょう",
    "profile_subtitle": "自己紹介を記入するとマッチングしやすくなります。",
    "bio_label": "自己紹介 (Bio)",
    "bio_placeholder": "例：留学のために英語を勉強しています。週末はカフェ巡りが好きです...",
    "intent_label": "主な学習目的",
    "finish_btn": "完了して探索を開始",
    "level_1": "入門 (A1)",
    "level_2": "初級 (A2)",
    "level_3": "中級 (B1)",
    "level_4": "中上級 (B2)",
    "level_5": "上級・流暢 (C1/C2)",
    "intent_casual": "日常会話・フリートーク",
    "intent_exam": "資格対策 (IELTS, JLPT...)",
    "intent_travel": "旅行会話",
    "intent_work": "ビジネス・仕事"
  },
  "notifications": {
    "title": "通知",
    "empty": "通知はありません。",
    "mark_all_read": "すべて既読にする",
    "follow_message": "{name} があなたをフォローし始めました。",
    "new_post_message": "{name} が新しい投稿をしました。",
    "like_message": "{name} があなたに「いいね！」しました。",
    "match_message": "あなたと {name} がマッチングしました！"
  },
  "topics": {
    "travel": "旅行",
    "music": "音楽",
    "movies": "映画",
    "food": "グルメ・料理",
    "sports": "スポーツ",
    "tech": "テクノロジー",
    "books": "読書・本",
    "game": "ゲーム",
    "culture": "文化・歴史",
    "exams": "資格試験 (IELTS/TOEIC...)"
  },
  "call": {
    "start_tooltip": "音声通話",
    "start_video_tooltip": "ビデオ通話",
    "calling": "発信中…",
    "incoming_title": "{name} からの着信",
    "incoming_audio": "音声通話の着信",
    "incoming_video": "ビデオ通話の着信",
    "accept": "応答",
    "accept_audio_only": "カメラオフで応答",
    "decline": "拒否",
    "hang_up": "切断",
    "mute": "ミュート",
    "unmute": "ミュート解除",
    "camera_off": "カメラをオフ",
    "camera_on": "カメラをオン",
    "switch_camera": "カメラ切り替え",
    "partner_camera_off": "相手がカメラをオフにしました",
    "network_unstable": "通信が不安定です…",
    "rejected": "相手が通話を拒否しました",
    "no_answer": "応答がありません",
    "partner_busy": "{name} は他の通話中です",
    "partner_offline": "{name} はオフラインです",
    "failed": "接続が切断され、通話が終了しました",
    "ended_max_duration": "通話の上限時間（30分）に達しました",
    "timeout_warning": "通話はあと {minutes} 分で自動終了します",
    "error_insecure": "ページがHTTPSでないため、マイクアクセスがブロックされました",
    "error_permission": "ブラウザの設定でマイクのアクセスを許可してください",
    "error_no_device": "マイクが見つかりません",
    "error_camera_busy": "カメラが別のアプリで使用されています — 音声のみで継続します",
    "error_camera_permission": "カメラがブロックされています — 通話は継続しますが映像は送信されません",
    "error_unknown": "通話を開始できませんでした",
    "log_ended": "音声通話 · {duration}",
    "log_ended_video": "ビデオ通話 · {duration}",
    "log_rejected": "通話を辞退しました",
    "log_missed_outgoing": "応答なし",
    "log_missed_incoming": "不在着信"
  }
};

// Check key coverage against en.json
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

let missingKeys = 0;
for (const sec in enData) {
  if (!jaData[sec]) {
    console.error(`Missing section: ${sec}`);
    missingKeys++;
    continue;
  }
  for (const k in enData[sec]) {
    if (jaData[sec][k] === undefined) {
      console.error(`Missing key: ${sec}.${k}`);
      missingKeys++;
    }
  }
}

if (missingKeys > 0) {
  console.error(`Validation failed: ${missingKeys} missing keys.`);
  process.exit(1);
}

fs.writeFileSync(jaPath, JSON.stringify(jaData, null, 2), 'utf8');
console.log('Successfully written ja.json with 100% key match!');
