const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../../frontend/messages/en.json');
const esPath = path.join(__dirname, '../../frontend/messages/es.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

// Exact English to Spanish mappings for all sections
const esMap = {
  // Metadata
  "metadata.title": "stududu — Practica idiomas extranjeros",
  "metadata.description": "Plataforma de intercambio lingüístico y práctica oral 1:1",

  // Nav & Menu
  "nav.discover": "Descubrir",
  "nav.messages": "Mensajes",
  "nav.vocabulary": "Vocabulario",
  "nav.community": "Comunidad",
  "nav.profile": "Perfil",
  "menu.profile": "Perfil",
  "menu.settings": "Configuración",
  "menu.admin": "Panel de administración",
  "menu.logout": "Cerrar sesión",

  // Settings
  "settings.title": "Configuración",
  "settings.language": "Idioma de la interfaz",
  "settings.language_hint": "Solo interfaz — el contenido generado por los usuarios permanece en su idioma original.",
  "settings.password": "Cambiar contraseña",
  "settings.shareActivity": "Compartir actividad",
  "settings.blocked": "Usuarios bloqueados",
  "settings.share_activity_enabled": "Compartir actividad activado",
  "settings.share_activity_disabled": "Compartir actividad desactivado",
  "settings.password_mismatch": "Las contraseñas no coinciden.",
  "settings.password_success": "Contraseña actualizada con éxito",
  "settings.unblock_success": "Desbloqueado/a {name}",
  "settings.password_hint": "Mínimo 8 caracteres, incluyendo letras y números.",
  "settings.curr_password_placeholder": "Contraseña actual",
  "settings.new_password_placeholder": "Nueva contraseña",
  "settings.confirm_password_placeholder": "Confirmar nueva contraseña",
  "settings.updating": "Actualizando...",
  "settings.update_password": "Actualizar contraseña",
  "settings.share_activity_hint": "Publicar automáticamente en la Comunidad cuando agregues una palabra o alcances objetivos de conversación.",
  "settings.enabled": "Activado",
  "settings.disabled": "Desactivado",
  "settings.no_blocked": "No has bloqueado a nadie.",
  "settings.unblock": "Desbloquear",
  "settings.logout": "Cerrar sesión",

  // Common
  "common.save": "Guardar cambios",
  "common.cancel": "Cancelar",
  "common.loading": "Cargando...",
  "common.retry": "Reintentar",
  "common.or": "o",
  "common.error_generic": "Ocurrió un error. Por favor inténtalo de nuevo.",

  // Home
  "home.login": "Iniciar sesión",
  "home.register": "Registrarse",
  "home.title_part1": "Practica hablar idiomas extranjeros con",
  "home.title_part2": "hablantes nativos reales",
  "home.description": "Encuentra tu compañero ideal de intercambio de idiomas. Tú enseñas tu idioma, ellos te enseñan el suyo. Totalmente gratis y mutuo.",
  "home.get_started": "Empieza ahora",

  // Login
  "login.title": "Iniciar sesión",
  "login.welcome": "Bienvenido de nuevo a stududu",
  "login.email": "Correo electrónico",
  "login.password": "Contraseña",
  "login.remember": "Recordarme",
  "login.forgot": "¿Olvidaste tu contraseña?",
  "login.submit": "Iniciar sesión",
  "login.submitting": "Iniciando sesión...",
  "login.google": "Continuar con Google",
  "login.google_notice": "Inicio de sesión con Google: La interfaz está lista. La integración de la API se configurará una vez completado el backend.",
  "login.no_account": "¿No tienes una cuenta?",
  "login.register_link": "Regístrate ahora",
  "login.hero_title": "Aprende idiomas con hablantes nativos reales.",
  "login.hero_sub": "Tú enseñas tu idioma, ellos te enseñan el suyo. Un intercambio justo — sin calificaciones ni tarifas.",
  "login.hero_p1": "Emparejado por idiomas complementarios, no por puntuación",
  "login.hero_p2": "Chat directo 1:1, practica tus reflejos todos los días",
  "login.hero_p3": "Contribuciones reconocidas con elogios, no clasificaciones",
  "login.hero_footer": "stududu — intercambio de idiomas al estilo Tandem",

  // Register
  "register.title": "Crear una cuenta",
  "register.subtitle": "Comienza tu viaje lingüístico",
  "register.hero_title": "Practica hablar con hablantes nativos reales.",
  "register.hero_subtitle": "Tú enseñas tu idioma, ellos te enseñan el suyo.",
  "register.display_name": "Nombre visible",
  "register.first_name": "Nombre",
  "register.surname": "Apellido",
  "register.dob": "Fecha de nacimiento",
  "register.day": "Día",
  "register.month": "Mes",
  "register.year": "Año",
  "register.gender": "Género",
  "register.gender_placeholder": "Selecciona tu género",
  "register.gender_female": "Femenino",
  "register.gender_male": "Masculino",
  "register.gender_custom": "Personalizado / Otro",
  "register.country": "País",
  "register.select_country": "Selecciona un país",
  "register.email": "Número de teléfono o correo electrónico",
  "register.password": "Contraseña",
  "register.password_hint": "Al menos 8 caracteres",
  "register.password_error": "La contraseña debe tener al menos 8 caracteres.",
  "register.submit": "Registrarse",
  "register.submitting": "Creando cuenta...",
  "register.google": "Continuar con Google",
  "register.google_notice": "Registro con Google: La interfaz está lista. La integración de la API se configurará una vez completado el backend.",
  "register.has_account": "¿Ya tienes una cuenta?",
  "register.login_link": "Iniciar sesión",

  // Discover
  "discover.hero_label": "Solo para ti",
  "discover.title": "Descubrir",
  "discover.subtitle": "Encuentra a alguien para aprender y enseñar idiomas juntos.",
  "discover.tab_suggest": "Mejores coincidencias",
  "discover.tab_all": "Todos los miembros",
  "discover.search_placeholder": "Buscar por nombre, idioma, intereses...",
  "discover.filter_title": "Filtros",
  "discover.filter_level_label": "Nivel del compañero (idioma que enseña)",
  "discover.filter_level_all": "Todos los niveles",
  "discover.filter_level_native": "Nativo",
  "discover.filter_level_fluent": "Fluido",
  "discover.filter_interests": "Intereses compartidos",
  "discover.filter_online": "En línea ahora",
  "discover.filter_reset": "Restablecer filtros",
  "discover.sort_best": "Mejor coincidencia",
  "discover.sort_recent": "Activo recientemente",
  "discover.result_count": "compañeros coincidentes",
  "discover.load_more": "Cargar más ({remaining} restantes)",
  "discover.loading_more": "Cargando...",
  "discover.loading_search": "Buscando tus mejores coincidencias...",
  "discover.error_load": "Error al cargar sugerencias",
  "discover.error_load_members": "Error al cargar miembros",
  "discover.tip_title": "Consejo de emparejamiento",
  "discover.tip_text": "¡Los perfiles con foto y biografía completa reciben muchas más conexiones!",
  "discover.insufficient_pool": "La comunidad está creciendo — aún no hay suficientes compañeros coincidentes, intenta explorar \"Todos los miembros\".",
  "discover.empty_no_members": "Aún no hay otros miembros",
  "discover.empty_insufficient": "No hay suficientes compañeros coincidentes",
  "discover.empty_no_match": "Aún no hay compañeros coincidentes",
  "discover.empty_no_filter": "Sin coincidencias con los filtros",
  "discover.empty_invite": "¡Invita a tus amigos a unirse a stududu!",
  "discover.empty_suggest_tip": "Intenta cambiar a Todos los miembros o actualiza tus idiomas e intereses.",
  "discover.empty_filter_tip": "Intenta relajar tus filtros para ver más compañeros.",
  "discover.refresh_list": "Actualizar lista",
  "discover.liked_toast": "Le diste me gusta a {name} — ¡envíale un mensaje ahora en Mensajes!",
  "discover.card_online": "En línea ahora",
  "discover.card_recent": "Activo recientemente",
  "discover.card_speaks": "Habla:",
  "discover.card_native": "(Nativo)",
  "discover.card_fluent": "(Fluido)",
  "discover.card_learns": "Aprende:",
  "discover.card_interests": "Intereses compartidos",
  "discover.card_liked": "Le gusta",
  "discover.card_like": "Me gusta",
  "discover.card_unlike": "Ya no me gusta",
  "discover.card_unliked_toast": "Se quitó me gusta a {name}",
  "discover.match_title": "🎉 ¡Es una coincidencia!",
  "discover.match_desc": "¡Genial! A ti y a {name} os habéis gustado mutuamente. Empecemos a chatear y practicar juntos.",
  "discover.match_chat_now": "Enviar mensaje ahora",
  "discover.match_continue": "Seguir descubriendo",

  // Community
  "community.title": "Comunidad",
  "community.add_image": "Adjuntar imagen",
  "community.subtitle": "Comparte lo que piensas — momentos destacados de la comunidad.",
  "community.post_placeholder": "¿Qué te gustaría compartir? (consejos, logros, historias...)",
  "community.post_button": "Publicar",
  "community.post_share": "compartió:",
  "community.post_word": "contribuyó con la palabra \"{term}\" ({language}) a la Biblioteca Pública 🌐",
  "community.post_word_generic": "contribuyó con una palabra a la Biblioteca Pública 🌐",
  "community.post_milestone": "acaba de alcanzar {hours} horas de práctica de conversación 🎉",
  "community.comment_placeholder": "Escribe un comentario...",
  "community.reply_placeholder": "Responder a {name}...",
  "community.reply": "Responder",
  "community.delete": "Eliminar",
  "community.unlike": "Ya no me gusta",
  "community.like": "Me gusta",
  "community.report": "Reportar",
  "community.comment_error": "Error al enviar el comentario",
  "community.image_too_large": "El tamaño de la imagen no debe exceder los 2MB",
  "community.char_count": "{count}/500",
  "community.edit": "Editar",
  "community.delete_post": "Eliminar publicación",
  "community.confirm_delete": "¿Estás seguro de que deseas eliminar esta publicación? Esta acción no se puede deshacer.",
  "community.confirm_yes": "Eliminar",
  "community.confirm_no": "Cancelar",
  "community.editing": "Editando publicación",
  "community.update": "Actualizar",
  "community.cancel_edit": "Cancelar",
  "community.empty_feed": "Aún no hay actividad",
  "community.empty_feed_hint": "¡Comparte algo con la comunidad!",
  "community.time_just_now": "Justo ahora",
  "community.time_minutes_ago": "hace {count} min",
  "community.time_hours_ago": "hace {count}h",
  "community.report_post_target": "Publicación de {name}",
  "community.attach_image": "Adjuntar imagen",
  "community.image_size_error": "⚠️ El tamaño de la imagen no puede exceder los 2MB",
  "community.eyebrow": "COMUNIDAD STUDUDU",
  "community.page_subtitle": "Comparte tu viaje, encuentra compañeros de práctica y únete a eventos.",
  "community.tab_feed": "Muro de noticias",
  "community.tab_groups": "Grupos de idiomas",
  "community.tab_events": "Eventos",
  "community.tag_partner": "Buscar compañero",
  "community.tag_milestone": "Compartir logro",
  "community.tag_question": "Consultar práctica",
  "community.daily_vocab_title": "NUEVO VOCABULARIO DE HOY",
  "community.save_word": "Guardar palabra",
  "community.saved_word": "Guardada",
  "community.next_word": "Siguiente palabra",
  "community.already_know": "Ya la conozco",
  "community.suggested_groups": "Grupos sugeridos",
  "community.join_group": "Unirse",
  "community.joined_group": "Unido",
  "community.members_count": "{count} miembros",
  "community.groups_coming_soon": "La función de Grupos de idiomas está actualmente en desarrollo. ¡Explora los grupos sugeridos a la derecha!",
  "community.events_coming_soon": "Eventos es donde los administradores organizarán exámenes y competencias para practicar juntos. ¡Próximamente!",
  "community.groups_title": "Grupos de idiomas",
  "community.group_en_desc": "Comunidad de práctica diaria de conversación en inglés con hablantes nativos.",
  "community.group_ja_desc": "Grupo de práctica de conversación Kaiwa en japonés e intercambio cultural.",
  "community.group_ko_desc": "Grupo de práctica de conversación en coreano e intercambio K-Culture.",
  "community.group_fr_desc": "Grupo de intercambio de conversación en francés desde niveles básicos hasta avanzados.",
  "community.events_title": "Eventos y competencias de exámenes",
  "community.status_upcoming": "PRÓXIMO",
  "community.event1_time": "15:00 - Este domingo",
  "community.event1_title": "🏆 Competencia de reflejo oral IELTS (Ronda 1 OJT)",
  "community.event1_desc": "Los administradores organizan salas de examen en vivo para competir juntos en puntajes de reflejos orales.",
  "community.event1_btn": "Registrarse en el examen",
  "community.event2_time": "20:00 - Cada miércoles",
  "community.event2_title": "🌸 Desafío de vocabulario N3 y Kaiwa Kanji",
  "community.event2_desc": "20 preguntas rápidas de Kanji emparejando estudiantes con hablantes nativos.",
  "community.event2_btn": "Interesado/a",
  "community.event_toast_notice": "ℹ️ ¡La función de registro en eventos estará disponible pronto!",
  "community.prev_word": "Palabra anterior",
  "community.translate_post": "Traducir publicación",
  "community.see_translation": "Ver traducción",
  "community.translated": "Traducido",
  "community.translation_title": "Traducción automática",
  "community.hide_translation": "Ocultar traducción",

  // Language Switcher
  "langSwitcher.vi": "Tiếng Việt",
  "langSwitcher.en": "English",
  "langSwitcher.es": "Español",
  "langSwitcher.fr": "Français",

  // Vocabulary
  "vocabulary.title": "Vocabulario",
  "vocabulary.tab_mine": "Mi cuaderno",
  "vocabulary.tab_library": "Biblioteca pública",
  "vocabulary.search_mine_placeholder": "Buscar palabras, notas...",
  "vocabulary.search_library_placeholder": "Buscar en biblioteca pública...",
  "vocabulary.add_word": "Agregar palabra",
  "vocabulary.library_hint": "Las palabras guardadas por ≥3 miembros ingresan automáticamente a la biblioteca pública — ordenadas por recuento de guardados.",
  "vocabulary.source_chat": "Desde chat",
  "vocabulary.source_manual": "Manual",
  "vocabulary.in_library": "En biblioteca pública",
  "vocabulary.no_definition": "Aún sin definición o notas",
  "vocabulary.deleted_toast": "Palabra eliminada de tu cuaderno",
  "vocabulary.definition_label": "Definición",
  "vocabulary.example_label": "Ejemplo",
  "vocabulary.personal_note_label": "Nota personal",
  "vocabulary.saved_by_count": "{count} personas guardaron esta palabra",
  "vocabulary.empty_title": "El cuaderno de vocabulario está vacío",
  "vocabulary.empty_no_match": "No se encontraron palabras",
  "vocabulary.empty_hint": "Destaca palabras durante los chats o agrégalas manualmente para ampliar tu vocabulario.",
  "vocabulary.empty_no_match_hint": "Intenta buscar con una palabra clave diferente.",
  "vocabulary.add_first_word": "Agrega tu primera palabra",
  "vocabulary.contrib_title": "Contribuir para \"{term}\"",
  "vocabulary.contrib_success": "🙌 ¡Gracias por tu contribución!",
  "vocabulary.contrib_btn": "Contribuir",
  "vocabulary.need_definition": "⏳ Requiere definición",
  "vocabulary.save_count_label": "{count} guardados",
  "vocabulary.save_success": "✅ Guardada \"{term}\"",
  "vocabulary.save_exists": "\"{term}\" ya está en el cuaderno — nota actualizada",
  "vocabulary.modal_title": "Guardar en el cuaderno de vocabulario",
  "vocabulary.language_label": "Idioma",
  "vocabulary.term_label": "Palabra / frase (máx. 100 caracteres)",
  "vocabulary.term_placeholder": "Ingresa la palabra para guardar...",
  "vocabulary.definition_placeholder": "Explica el significado de la palabra...",
  "vocabulary.example_placeholder": "Ingresa una oración de ejemplo usando esta palabra...",
  "vocabulary.quiz_hint_prompt": "Elige la traducción más precisa a continuación:",
  "vocabulary.header_badge": "CUESTIONARIO Y PRÁCTICA DE VOCABULARIO",
  "vocabulary.page_title": "Vocabulario y cuestionario",
  "vocabulary.page_subtitle": "Practica con cuestionarios de opción múltiple y administra tu cuaderno personal de vocabulario.",
  "vocabulary.total_words": "Total de palabras",
  "vocabulary.mastered": "Dominadas",
  "vocabulary.need_review": "Necesita revisión",
  "vocabulary.tab_quiz": "Repaso con cuestionario",
  "vocabulary.tab_notebook": "Cuaderno ({count})",
  "vocabulary.btn_review_learning": "Repasar no dominadas ({count})",
  "vocabulary.btn_review_all": "Repasar todas ({count})",
  "vocabulary.quiz_loading": "Cargando datos del cuestionario...",
  "vocabulary.quiz_result_title": "Resultado de la sesión de cuestionario",
  "vocabulary.quiz_result_desc": "Completaste la sesión de repaso con {count} preguntas.",
  "vocabulary.total_score": "Puntuación total",
  "vocabulary.score_sub": "+10 pts / respuesta correcta",
  "vocabulary.correct_answers": "Respuestas correctas",
  "vocabulary.correct_sub": "Movidas a Dominadas",
  "vocabulary.accuracy_rate": "Tasa de precisión",
  "vocabulary.accuracy": "Precisión",
  "vocabulary.btn_new_quiz": "Iniciar nuevo cuestionario",
  "vocabulary.btn_view_notebook": "Ver cuaderno de vocabulario",
  "vocabulary.question_progress": "Pregunta {current} / {total}",
  "vocabulary.points": "{points} pts",
  "vocabulary.streak": "¡Racha de {streak}!",
  "vocabulary.status_mastered_label": "Dominada",
  "vocabulary.status_learning.label": "Aprendiendo",
  "vocabulary.status_learning_label": "Aprendiendo",
  "vocabulary.btn_audio_tooltip": "Escuchar pronunciación",
  "vocabulary.btn_next_question": "Siguiente pregunta",
  "vocabulary.btn_view_score": "Ver resultados del cuestionario",
  "vocabulary.empty_learning_title": "¡Has dominado todas las palabras en revisión!",
  "vocabulary.empty_learning_desc": "¡Buen trabajo! Cambia a 'Repasar todas' para reforzar tu conocimiento.",
  "vocabulary.empty_notebook_title": "¡Aún no hay palabras en el cuaderno!",
  "vocabulary.empty_notebook_desc": "Agrega nuevas palabras a tu cuaderno al traducir o chatear.",
  "vocabulary.btn_review_all_full": "Repasar todas las palabras ({count})",
  "vocabulary.notebook_heading": "Cuaderno personal de vocabulario",
  "vocabulary.notebook_subheading": "Todas las palabras guardadas desde traducción, chat y entradas manuales.",
  "vocabulary.total_count_label": "Total: {count} palabras",
  "vocabulary.filter_all": "Todas",
  "vocabulary.filter_new": "Nuevas",
  "vocabulary.filter_learning": "Aprendiendo",
  "vocabulary.filter_mastered": "Dominadas",
  "vocabulary.search_placeholder_notebook": "Buscar vocabulario...",
  "vocabulary.source_chat_label": "Chat",
  "vocabulary.source_manual_label": "Cuaderno",
  "vocabulary.source_community_label": "Comunidad",
  "vocabulary.source_prefix": "Fuente: {source}",
  "vocabulary.btn_delete_tooltip": "Eliminar palabra",
  "vocabulary.deleted_toast_message": "Se eliminó \"{term}\" del cuaderno de vocabulario.",
  "vocabulary.no_words_found": "No se encontraron palabras coincidente.",
  "vocabulary.rank_excellent": "¡Excelente! 🌟",
  "vocabulary.rank_good": "¡Genial! 👏",
  "vocabulary.rank_fair": "¡Bueno! 👍",
  "vocabulary.rank_needs_work": "¡Sigue intentando! 💡",
  "vocabulary.select_correct_def_prompt": "👉 Selecciona la definición correcta a continuación:",
  "vocabulary.translation_label": "Traducir:",
  "vocabulary.definition_heading": "📝 Definición",
  "vocabulary.example_heading": "💡 Ejemplo",
  "vocabulary.no_info": "No se encontró información para esta palabra.",
  "vocabulary.saved_by_users": "🌐 {count} personas guardaron esto",
  "vocabulary.lookup_error": "No se puede buscar la palabra en este momento. Inténtalo de nuevo más tarde.",
  "vocabulary.saving_btn": "Guardando...",
  "vocabulary.save_to_notebook_btn": "Guardar en el cuaderno",

  // Profile
  "profile.title_me": "Mi perfil",
  "profile.edit_profile": "Editar perfil",
  "profile.settings": "Configuración",
  "profile.tab_posts": "Publicaciones",
  "profile.tab_about": "Acerca de",
  "profile.posts_title": "Publicaciones",
  "profile.posts_count": "{count} publicaciones",
  "profile.no_posts_me": "Aún no has publicado nada.",
  "profile.create_post_hint": "¡Comparte una publicación con la comunidad!",
  "profile.create_post_btn": "Crear publicación",
  "profile.post_placeholder": "¿Qué tienes en mente, {name}?",
  "profile.lives_in": "Vive en",
  "profile.gender_label": "Género",
  "profile.timezone_label_short": "Zona horaria",
  "profile.speaks_label": "Habla",
  "profile.learns_label": "Aprende",
  "profile.level_label": "Nivel",
  "profile.native_label": "Nativo",
  "profile.fluent_label": "Fluido",
  "profile.edit_btn": "Editar",
  "profile.completion": "Completitud del perfil",
  "profile.trust_activity": "Confianza y actividad",
  "profile.languages": "Idiomas",
  "profile.can_teach": "Puede enseñar",
  "profile.want_learn": "Desea aprender",
  "profile.none": "Ninguno",
  "profile.intro": "Acerca de mí",
  "profile.no_intro_me": "Aún no has escrito una presentación — agrega unas líneas para ser emparejado fácilmente.",
  "profile.no_intro_other": "El miembro aún no ha escrito una presentación.",
  "profile.intent": "Intención",
  "profile.not_specified": "No especificado",
  "profile.availability": "Disponibilidad y zona horaria",
  "profile.no_availability": "Disponibilidad no configurada",
  "profile.interests": "Intereses",
  "profile.no_interests": "Intereses no elegidos",
  "profile.loading_error": "Error al cargar el perfil",
  "profile.hint_avatar": "Agregar foto de avatar",
  "profile.hint_bio": "Escribir presentación personal",
  "profile.hint_teach": "Agregar idioma que puedes enseñar",
  "profile.hint_learn": "Agregar idioma que deseas aprender",
  "profile.hint_interests": "Elegir intereses",
  "profile.hint_intent": "Elegir intención de aprendizaje",
  "profile.report": "Reportar",
  "profile.block": "Bloquear",
  "profile.endorse_btn": "Reconocer",
  "profile.endorse_success_toast": "🏅 Reconocimiento enviado. ¡Gracias!",
  "profile.no_endorsements": "Aún sin reconocimientos",
  "profile.chat_hours": "{count} horas de práctica",
  "profile.conversations": "{count} conversaciones",
  "profile.endorse_title": "Reconocer a {name}",
  "profile.endorse_desc": "Elige lo que te gustaría reconocer tras hablar con {name} — sin calificaciones, solo apreciación cualitativa.",
  "profile.endorse_already_given": "✓ ya reconocido/a",
  "profile.sending": "Enviando...",
  "profile.submit_endorse": "Enviar reconocimiento",
  "profile.lang_proficiency": "Dominio nativo",
  "profile.social_knowledge": "Conocimiento cultural/social",
  "profile.niche_expertise": "Experiencia profunda",
  "profile.friendliness": "Amigable",
  "profile.trust_activity_other": "Reconocimientos de la comunidad",
  "profile.report_success_toast": "Reporte enviado. ¡Gracias!",
  "profile.block_success_toast": "Bloqueado/a {name}",
  "profile.like_success_toast": "💜 Le diste me gusta a {name} — ¡inicia una conversación!",
  "profile.loading_error_other": "Error al cargar el perfil",
  "profile.user_not_found": "Usuario no encontrado",
  "profile.message_btn": "Mensaje",
  "profile.basic_info": "Información básica",
  "profile.avatar": "Imagen de avatar",
  "profile.select_image": "Seleccionar foto",
  "profile.delete_image": "Eliminar foto",
  "profile.avatar_hint": "JPG/PNG — la imagen se comprimirá automáticamente.",
  "profile.avatar_error": "No se puede leer esta foto, intenta con otra.",
  "profile.dob": "Fecha de nacimiento",
  "profile.gender": "Género",
  "profile.gender_private": "No divulgar",
  "profile.gender_male": "Masculino",
  "profile.gender_female": "Femenino",
  "profile.gender_other": "Otro",
  "profile.city": "Ciudad",
  "profile.city_placeholder": "Ej. Madrid",
  "profile.display_name": "Nombre visible",
  "profile.empty_name_error": "El nombre visible no puede estar vacío.",
  "profile.lang_selection_error": "Por favor selecciona al menos 1 idioma que puedas enseñar y 1 idioma para aprender.",
  "profile.timezone_label": "Tu zona horaria",
  "profile.slots_title": "Disponibilidad (máx. 2)",
  "profile.slots_selected": "{count}/2 seleccionados",
  "profile.slots_time": "Hora",
  "profile.slots_hint": "Los horarios disponibles ayudan a los compañeros a solicitar horarios de chat más fácilmente.",
  "profile.matching_criteria": "Criterios de emparejamiento",
  "profile.preferred_language": "Idioma preferido",
  "profile.no_preference": "Sin preferencia",
  "profile.desired_level": "Nivel deseado del compañero",
  "profile.any_level": "Cualquiera",
  "profile.edit_subtitle": "Un perfil completo te otorga más coincidencias — actualízalo en cualquier momento.",
  "profile.this_is_you": "Este es tu perfil",
  "profile.your_name": "Tu nombre",
  "profile.change_avatar": "Cambiar foto de perfil",
  "profile.preview": "Vista previa",
  "profile.preview_hint": "Así te ven los demás en Descubrir.",
  "profile.preview_speaks": "Habla:",
  "profile.preview_learns": "Aprende:",
  "profile.preview_not_added": "No agregado",
  "profile.preview_online": "Activo/a ahora",
  "profile.preview_like": "Me gusta",
  "profile.shared_interests": "Intereses compartidos",
  "profile.interests_hint": "Elige temas sobre los que disfrutes hablar.",
  "profile.intent_hint": "Nos ayuda a sugerir mejores compañeros.",
  "profile.no_posts_other": "Aún no hay publicaciones compartidas.",

  // Chat
  "chat.say_hi": "Di hola para iniciar la conversación 👋",
  "chat.you": "Tú: ",
  "chat.photo": "📷 Foto",
  "chat.schedule_invite": "📅 Invitación de horario",
  "chat.translate_fail": "Error de traducción, inténtalo más tarde",
  "chat.schedule_fail": "Error al enviar invitación de horario",
  "chat.respond_fail": "Error al responder a la invitación",
  "chat.title": "Mensajes",
  "chat.search_placeholder": "Buscar conversaciones...",
  "chat.no_match": "No se encontraron conversaciones",
  "chat.empty_conversations": "Aún no hay conversaciones",
  "chat.empty_hint": "Ve a Descubrir para encontrar compañeros de práctica.",
  "chat.go_discover": "Ir a Descubrir",
  "chat.select_chat": "Seleccionar una conversación",
  "chat.select_chat_hint": "Empieza a practicar con tu compañero.",
  "chat.user_local_time": "(tu hora)",
  "chat.schedule_btn_tooltip": "Programar chat",
  "chat.trans_modal_tooltip": "Tablero de traducción",
  "chat.view_profile": "Ver perfil",
  "chat.report": "Reportar",
  "chat.block": "Bloquear",
  "chat.partner_availability": "Horarios libres de {name}:",
  "chat.overlap_badge": "✓ ¡Horarios libres en común!",
  "chat.reconnecting": "Reconectando...",
  "chat.save_word_popup": "Guardar palabra",
  "chat.matched_title": "¡Habéis coincidido!",
  "chat.matched_desc": "Envía un saludo para empezar a practicar.",
  "chat.invite_sent": "Enviaste una invitación",
  "chat.invite_received": "{name} te invitó a chatear",
  "chat.local_time_hint": "(según la zona horaria de tu computadora)",
  "chat.accept": "Aceptar",
  "chat.decline": "Rechazar",
  "chat.cancel": "Cancelar",
  "chat.status_accepted": "✅ Aceptado — se recordará 30 min antes",
  "chat.status_expired": "⌛ Expirado (sin respuesta en 48h)",
  "chat.status_declined": "❌ Rechazado",
  "chat.status_cancelled": "🚫 Cancelado",
  "chat.cancel_reason_label": "Razón: {reason}",
  "chat.cancel_modal_title": "Cancelar chat programado",
  "chat.cancel_modal_placeholder": "Ingresa una razón para la cancelación...",
  "chat.cancel_success_toast": "Chat programado cancelado con éxito",
  "chat.status_sending": "Enviando...",
  "chat.status_read": "Leído",
  "chat.status_sent": "Enviado",
  "chat.react_tooltip": "Agregar reacción",
  "chat.emoji_tooltip": "Emoji",
  "chat.send_img_tooltip": "Enviar foto",
  "chat.input_placeholder": "Escribe un mensaje...",
  "chat.report_success": "Reporte enviado. ¡Gracias!",
  "chat.block_success": "Bloqueado/a {name}",
  "chat.word_save_exists": "\"{term}\" ya está en tu cuaderno",
  "chat.word_save_success": "✅ Guardada \"{term}\" en el cuaderno de vocabulario",
  "chat.translating": "Traduciendo...",
  "chat.hide": "Ocultar",
  "chat.translate": "Traducir",
  "chat.save_word": "Guardar palabra",

  // Forgot Password
  "forgot.title": "Contraseña olvidada",
  "forgot.subtitle": "Ingresa tu correo electrónico para recibir un enlace de restablecimiento",
  "forgot.success_message": "Si el correo electrónico es válido, hemos enviado un enlace de restablecimiento. El enlace expirará en 30 minutos.",
  "forgot.back_to_login": "Volver a iniciar sesión",
  "forgot.email_placeholder": "Tu correo electrónico",
  "forgot.sending": "Enviando...",
  "forgot.submit": "Enviar enlace de restablecimiento",

  // Onboarding
  "onboarding.step_languages": "Idiomas",
  "onboarding.step_interests": "Intereses",
  "onboarding.step_complete": "Finalización",
  "onboarding.error_lang_selection": "Por favor selecciona al menos 1 idioma que puedas enseñar y 1 idioma para aprender.",
  "onboarding.error_bio_empty": "Por favor escribe una biografía personal.",
  "onboarding.teach_title": "Hablo (puedo enseñar)",
  "onboarding.select_lang": "Seleccionar idioma",
  "onboarding.add_btn": "Agregar",
  "onboarding.learn_title": "Quiero aprender",
  "onboarding.loading": "Guardando...",
  "onboarding.continue_btn": "Continuar",
  "onboarding.interests_title": "Tus intereses",
  "onboarding.interests_subtitle": "Selecciona temas que te interesen (opcional).",
  "onboarding.back_btn": "Atrás",
  "onboarding.profile_title": "Completa tu perfil",
  "onboarding.profile_subtitle": "Un poco sobre ti te ayudará a conseguir coincidencias fácilmente.",
  "onboarding.bio_label": "Presentación personal (Bio)",
  "onboarding.bio_placeholder": "Ej. Estoy aprendiendo inglés para estudiar en el extranjero. Me encanta el café en los fines de semana...",
  "onboarding.intent_label": "Intención principal de aprendizaje",
  "onboarding.finish_btn": "Finalizar y Descubrir",
  "onboarding.level_1": "Principiante",
  "onboarding.level_2": "Elemental",
  "onboarding.level_3": "Intermedio",
  "onboarding.level_4": "Intermedio alto",
  "onboarding.level_5": "Fluido",
  "onboarding.intent_casual": "Conversación informal",
  "onboarding.intent_exam": "Preparación para exámenes (IELTS, JLPT...)",
  "onboarding.intent_travel": "Viajes",
  "onboarding.intent_work": "Trabajo",

  // Notifications
  "notifications.title": "Notificaciones",
  "notifications.empty": "No tienes notificaciones.",
  "notifications.mark_all_read": "Marcar todo como leído",
  "notifications.follow_message": "{name} comenzó a seguirte.",
  "notifications.new_post_message": "{name} publicó una nueva actualización.",
  "notifications.like_message": "A {name} le gustaste.",
  "notifications.match_message": "¡Tú y {name} habéis coincidido!",

  // Topics
  "topics.travel": "Viajes",
  "topics.music": "Música",
  "topics.movies": "Películas",
  "topics.food": "Comida",
  "topics.sports": "Deportes",
  "topics.tech": "Tecnología",
  "topics.books": "Libros",
  "topics.game": "Videojuegos",
  "topics.culture": "Cultura",
  "topics.exams": "Exámenes (IELTS/TOEIC...)",

  // Call
  "call.start_tooltip": "Llamada de voz",
  "call.start_video_tooltip": "Videollamada",
  "call.calling": "Llamando…",
  "call.incoming_title": "{name} te está llamando",
  "call.incoming_audio": "Llamada de voz entrante",
  "call.incoming_video": "Videollamada entrante",
  "call.accept": "Aceptar",
  "call.accept_audio_only": "Responder sin cámara",
  "call.decline": "Rechazar",
  "call.hang_up": "Colgar",
  "call.mute": "Silenciar",
  "call.unmute": "Activar micrófono",
  "call.camera_off": "Desactivar cámara",
  "call.camera_on": "Activar cámara",
  "call.switch_camera": "Cambiar cámara frontal/trasera",
  "call.partner_camera_off": "Tu compañero/a desactivó su cámara",
  "call.network_unstable": "Conexión débil…",
  "call.rejected": "Tu compañero/a rechazó la llamada",
  "call.no_answer": "Sin respuesta",
  "call.partner_busy": "{name} está en otra llamada",
  "call.partner_offline": "{name} no está en línea",
  "call.failed": "Conexión perdida, la llamada finalizó",
  "call.ended_max_duration": "La llamada alcanzó el límite de 30 minutos",
  "call.timeout_warning": "La llamada finalizará automáticamente en {minutes} minutos",
  "call.error_insecure": "Tu navegador bloqueó el micrófono porque la página no usa HTTPS",
  "call.error_permission": "Permite el acceso al micrófono en la configuración de tu navegador",
  "call.error_no_device": "No se encontró ningún micrófono",
  "call.error_camera_busy": "La cámara está siendo usada por otra aplicación o pestaña — continuando con llamada de voz",
  "call.error_camera_permission": "La cámara está bloqueada — la llamada continúa, pero tu compañero/a no te verá",
  "call.error_unknown": "No se pudo iniciar la llamada",
  "call.log_ended": "Llamada de voz · {duration}",
  "call.log_ended_video": "Videollamada · {duration}",
  "call.log_rejected": "Llamada rechazada",
  "call.log_missed_outgoing": "Llamaste pero nadie respondió",
  "call.log_missed_incoming": "Llamada perdida"
};

// Build nested es object strictly following en.json key structure
function buildNestedObject(sourceObj, prefix = '') {
  const result = {};
  for (const key of Object.keys(sourceObj)) {
    const fullPath = prefix ? `${prefix}.${key}` : key;
    if (typeof sourceObj[key] === 'object' && sourceObj[key] !== null && !Array.isArray(sourceObj[key])) {
      result[key] = buildNestedObject(sourceObj[key], fullPath);
    } else {
      if (esMap[fullPath]) {
        result[key] = esMap[fullPath];
      } else {
        console.warn(`Missing Spanish translation for key: ${fullPath}`);
        result[key] = sourceObj[key]; // fallback to English string if missing
      }
    }
  }
  return result;
}

const esNested = buildNestedObject(en);

fs.writeFileSync(esPath, JSON.stringify(esNested, null, 2), 'utf8');
console.log('Successfully re-generated es.json strictly based on en.json structure and English keys!');
